## This notebook uses each one of the 52 prediction models trained on autoML.ipynb to generate a gaussian_kde. Applied on the validation split (half) for the supernovae from type IA.

In [1]:
%load_ext autoreload
%autoreload 2
import os 
import sys
import h2o

import pandas as pd

In [2]:
module_path = os.path.abspath(os.path.join('..','..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from src.modeling.functions_autoML import (read_models,
                                           gen_models_predictions,
                                           gen_gaussian_kde, 
                                           print_gaussian_kde,
                                           gen_df_gaussian_kde)

In [3]:
df = pd.read_pickle("../../data/structured/df.pkl")
#IA Filter
df = df.loc[df.type_bool == True]

In [4]:
BEST_MODEL = 'StackedEnsemble_AllModels_AutoML_20201223_115349.zip'

In [5]:
h2o.init(ip="localhost", port=54323)

Checking whether there is an H2O instance running at http://localhost:54323 ..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "11.0.16" 2022-07-19; OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04); OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
  Starting server from /home/fm/Projects/photometric-redshift-prediction/.photometric_redshift_prediction/lib/python3.8/site-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmp5d7lldte
  JVM stdout: /tmp/tmp5d7lldte/h2o_fm_started_from_python.out
  JVM stderr: /tmp/tmp5d7lldte/h2o_fm_started_from_python.err
  Server is running at http://127.0.0.1:54323
Connecting to H2O server at http://127.0.0.1:54323 ... successful.
Warning: Your H2O cluster version is too old (1 year, 2 months and 6 days)! Please download and install the latest version from http://h2o.ai/download/

--------------------------  ------------------------------------------------------------------
H2O_cluster_uptime:         04 secs
H2O_cluster_timezone:       Europe/Paris
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.32.1.6
H2O_cluster_version_age:    1 year, 2 months and 6 days !!!
H2O_cluster_name:           H2O_from_python_fm_b8ou83
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    1.922 Gb
H2O_cluster_total_cores:    4
H2O_cluster_allowed_cores:  4
H2O_cluster_status:         accepting new members, healthy
H2O_connection_url:         http://127.0.0.1:54323
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, XGBoost, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.8.10 final
--------------------------  ------------------------------------------------------------------

### Creating DataFrame with predictions

In [6]:
!pwd

/home/fm/Projects/photometric-redshift-prediction/notebooks/modeling

In [8]:
# read_models('../../models/models/mojo_50_ensemble')
# s = read_models('../../models/mojo_50_ensemble_08validation_lowerzhalf')

s = read_models('../../models/models/mojo_50_ensemble')

generic Model Build progress: |███████████████████████████████████████████| 100%
Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_17


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,70.0,70.0,56286.0,7.0,7.0,7.0,38.0,85.0,59.4

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.002796988672348969
RMSE: 0.0528865641949727
MAE: 0.03930626413839705
RMSLE: 0.02975009489215282
Mean Residual Deviance: 0.002796988672348969

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.008565752435562443
RMSE: 0.09255135026331297
MAE: 0.07075825450227256
RMSLE: 0.05327637685687936
Mean Residual Deviance: 0.008565752435562443

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07075825,0.0015950237,0.073111095,0.0697754,0.07021934,0.06911009,0.07157535
1,mean_residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
2,mse,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
3,r2,0.83073425,0.007195892,0.82004786,0.8361518,0.8382571,0.828117,0.83109754
4,residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
5,rmse,0.09253432,0.0019849439,0.09514227,0.090731815,0.091737635,0.09412287,0.09093701
6,rmsle,0.05326346,0.0013115642,0.054599006,0.051951602,0.05274927,0.05473171,0.052285712

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:16,2.644 sec,0.0,0.225214,0.185965,0.050721
1,,2020-12-23 12:54:16,2.682 sec,5.0,0.152731,0.126670,0.023327
2,,2020-12-23 12:54:16,2.703 sec,10.0,0.114317,0.094761,0.013068
3,,2020-12-23 12:54:16,2.723 sec,15.0,0.093848,0.076676,0.008807
4,,2020-12-23 12:54:16,2.746 sec,20.0,0.083360,0.066580,0.006949
5,,2020-12-23 12:54:16,2.779 sec,25.0,0.077449,0.060510,0.005998
6,,2020-12-23 12:54:16,2.804 sec,30.0,0.073213,0.056345,0.005360
7,,2020-12-23 12:54:16,2.827 sec,35.0,0.069713,0.053233,0.004860
8,,2020-12-23 12:54:16,2.850 sec,40.0,0.066686,0.050517,0.004447
9,,2020-12-23 12:54:16,2.876 sec,45.0,0.064059,0.048304,0.004104
10,,2020-12-23 12:54:16,2.909 sec,50.0,0.061136,0.045976,0.003738
11,,2020-12-23 12:54:16,2.934 sec,55.0,0.058957,0.044253,0.003476
12,,2020-12-23 12:54:16,2.961 sec,60.0,0.056785,0.042487,0.003225
13,,2020-12-23 12:54:16,2.983 sec,65.0,0.054885,0.040978,0.003012
14,,2020-12-23 12:54:16,3.006 sec,70.0,0.052887,0.039306,0.002797

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           417.634766           1.000000    0.691143
1       f10            30.944672           0.074095    0.051210
2        f3            29.945110           0.071702    0.049556
3       f15            11.459804           0.027440    0.018965
4        f5            10.429785           0.024973    0.017260
5       f20            10.251256           0.024546    0.016965
6        f2             9.859209           0.023607    0.016316
7       f19             8.878176           0.021258    0.014692
8       f12             8.301757           0.019878    0.013739
9       f18             8.120420           0.019444    0.013438
10      f13             7.664119           0.018351    0.012683
11       f4             7.198557           0.017236    0.011913
12       f8             7.032873           0.016840    0.011639
13       f6             6.048911           0.014484    0.010010
14       f7             5.914305           0.014161    0.009788
15       f9             5.534474           0.013252    0.009159
16      f16             5.280519           0.012644    0.008739
17      f17             4.892844           0.011716    0.008097
18      f14             4.451653           0.010659    0.007367
19      f11             4.423503           0.010592    0.007320

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_17


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,70.0,70.0,56286.0,7.0,7.0,7.0,38.0,85.0,59.4

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.002796988672348969
RMSE: 0.0528865641949727
MAE: 0.03930626413839705
RMSLE: 0.02975009489215282
Mean Residual Deviance: 0.002796988672348969

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.008565752435562443
RMSE: 0.09255135026331297
MAE: 0.07075825450227256
RMSLE: 0.05327637685687936
Mean Residual Deviance: 0.008565752435562443

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07075825,0.0015950237,0.073111095,0.0697754,0.07021934,0.06911009,0.07157535
1,mean_residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
2,mse,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
3,r2,0.83073425,0.007195892,0.82004786,0.8361518,0.8382571,0.828117,0.83109754
4,residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
5,rmse,0.09253432,0.0019849439,0.09514227,0.090731815,0.091737635,0.09412287,0.09093701
6,rmsle,0.05326346,0.0013115642,0.054599006,0.051951602,0.05274927,0.05473171,0.052285712

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:16,2.644 sec,0.0,0.225214,0.185965,0.050721
1,,2020-12-23 12:54:16,2.682 sec,5.0,0.152731,0.126670,0.023327
2,,2020-12-23 12:54:16,2.703 sec,10.0,0.114317,0.094761,0.013068
3,,2020-12-23 12:54:16,2.723 sec,15.0,0.093848,0.076676,0.008807
4,,2020-12-23 12:54:16,2.746 sec,20.0,0.083360,0.066580,0.006949
5,,2020-12-23 12:54:16,2.779 sec,25.0,0.077449,0.060510,0.005998
6,,2020-12-23 12:54:16,2.804 sec,30.0,0.073213,0.056345,0.005360
7,,2020-12-23 12:54:16,2.827 sec,35.0,0.069713,0.053233,0.004860
8,,2020-12-23 12:54:16,2.850 sec,40.0,0.066686,0.050517,0.004447
9,,2020-12-23 12:54:16,2.876 sec,45.0,0.064059,0.048304,0.004104
10,,2020-12-23 12:54:16,2.909 sec,50.0,0.061136,0.045976,0.003738
11,,2020-12-23 12:54:16,2.934 sec,55.0,0.058957,0.044253,0.003476
12,,2020-12-23 12:54:16,2.961 sec,60.0,0.056785,0.042487,0.003225
13,,2020-12-23 12:54:16,2.983 sec,65.0,0.054885,0.040978,0.003012
14,,2020-12-23 12:54:16,3.006 sec,70.0,0.052887,0.039306,0.002797

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           417.634766           1.000000    0.691143
1       f10            30.944672           0.074095    0.051210
2        f3            29.945110           0.071702    0.049556
3       f15            11.459804           0.027440    0.018965
4        f5            10.429785           0.024973    0.017260
5       f20            10.251256           0.024546    0.016965
6        f2             9.859209           0.023607    0.016316
7       f19             8.878176           0.021258    0.014692
8       f12             8.301757           0.019878    0.013739
9       f18             8.120420           0.019444    0.013438
10      f13             7.664119           0.018351    0.012683
11       f4             7.198557           0.017236    0.011913
12       f8             7.032873           0.016840    0.011639
13       f6             6.048911           0.014484    0.010010
14       f7             5.914305           0.014161    0.009788
15       f9             5.534474           0.013252    0.009159
16      f16             5.280519           0.012644    0.008739
17      f17             4.892844           0.011716    0.008097
18      f14             4.451653           0.010659    0.007367
19      f11             4.423503           0.010592    0.007320

generic Model Build progress: |███████████████████████████████████████████| 100%
Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_18


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,70.0,70.0,56286.0,7.0,7.0,7.0,38.0,85.0,59.4

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.002796988672348969
RMSE: 0.0528865641949727
MAE: 0.03930626413839705
RMSLE: 0.02975009489215282
Mean Residual Deviance: 0.002796988672348969

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.008565752435562443
RMSE: 0.09255135026331297
MAE: 0.07075825450227256
RMSLE: 0.05327637685687936
Mean Residual Deviance: 0.008565752435562443

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07075825,0.0015950237,0.073111095,0.0697754,0.07021934,0.06911009,0.07157535
1,mean_residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
2,mse,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
3,r2,0.83073425,0.007195892,0.82004786,0.8361518,0.8382571,0.828117,0.83109754
4,residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
5,rmse,0.09253432,0.0019849439,0.09514227,0.090731815,0.091737635,0.09412287,0.09093701
6,rmsle,0.05326346,0.0013115642,0.054599006,0.051951602,0.05274927,0.05473171,0.052285712

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:16,2.644 sec,0.0,0.225214,0.185965,0.050721
1,,2020-12-23 12:54:16,2.682 sec,5.0,0.152731,0.126670,0.023327
2,,2020-12-23 12:54:16,2.703 sec,10.0,0.114317,0.094761,0.013068
3,,2020-12-23 12:54:16,2.723 sec,15.0,0.093848,0.076676,0.008807
4,,2020-12-23 12:54:16,2.746 sec,20.0,0.083360,0.066580,0.006949
5,,2020-12-23 12:54:16,2.779 sec,25.0,0.077449,0.060510,0.005998
6,,2020-12-23 12:54:16,2.804 sec,30.0,0.073213,0.056345,0.005360
7,,2020-12-23 12:54:16,2.827 sec,35.0,0.069713,0.053233,0.004860
8,,2020-12-23 12:54:16,2.850 sec,40.0,0.066686,0.050517,0.004447
9,,2020-12-23 12:54:16,2.876 sec,45.0,0.064059,0.048304,0.004104
10,,2020-12-23 12:54:16,2.909 sec,50.0,0.061136,0.045976,0.003738
11,,2020-12-23 12:54:16,2.934 sec,55.0,0.058957,0.044253,0.003476
12,,2020-12-23 12:54:16,2.961 sec,60.0,0.056785,0.042487,0.003225
13,,2020-12-23 12:54:16,2.983 sec,65.0,0.054885,0.040978,0.003012
14,,2020-12-23 12:54:16,3.006 sec,70.0,0.052887,0.039306,0.002797

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           417.634766           1.000000    0.691143
1       f10            30.944672           0.074095    0.051210
2        f3            29.945110           0.071702    0.049556
3       f15            11.459804           0.027440    0.018965
4        f5            10.429785           0.024973    0.017260
5       f20            10.251256           0.024546    0.016965
6        f2             9.859209           0.023607    0.016316
7       f19             8.878176           0.021258    0.014692
8       f12             8.301757           0.019878    0.013739
9       f18             8.120420           0.019444    0.013438
10      f13             7.664119           0.018351    0.012683
11       f4             7.198557           0.017236    0.011913
12       f8             7.032873           0.016840    0.011639
13       f6             6.048911           0.014484    0.010010
14       f7             5.914305           0.014161    0.009788
15       f9             5.534474           0.013252    0.009159
16      f16             5.280519           0.012644    0.008739
17      f17             4.892844           0.011716    0.008097
18      f14             4.451653           0.010659    0.007367
19      f11             4.423503           0.010592    0.007320

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_18


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,70.0,70.0,56286.0,7.0,7.0,7.0,38.0,85.0,59.4

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.002796988672348969
RMSE: 0.0528865641949727
MAE: 0.03930626413839705
RMSLE: 0.02975009489215282
Mean Residual Deviance: 0.002796988672348969

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.008565752435562443
RMSE: 0.09255135026331297
MAE: 0.07075825450227256
RMSLE: 0.05327637685687936
Mean Residual Deviance: 0.008565752435562443

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07075825,0.0015950237,0.073111095,0.0697754,0.07021934,0.06911009,0.07157535
1,mean_residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
2,mse,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
3,r2,0.83073425,0.007195892,0.82004786,0.8361518,0.8382571,0.828117,0.83109754
4,residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
5,rmse,0.09253432,0.0019849439,0.09514227,0.090731815,0.091737635,0.09412287,0.09093701
6,rmsle,0.05326346,0.0013115642,0.054599006,0.051951602,0.05274927,0.05473171,0.052285712

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:16,2.644 sec,0.0,0.225214,0.185965,0.050721
1,,2020-12-23 12:54:16,2.682 sec,5.0,0.152731,0.126670,0.023327
2,,2020-12-23 12:54:16,2.703 sec,10.0,0.114317,0.094761,0.013068
3,,2020-12-23 12:54:16,2.723 sec,15.0,0.093848,0.076676,0.008807
4,,2020-12-23 12:54:16,2.746 sec,20.0,0.083360,0.066580,0.006949
5,,2020-12-23 12:54:16,2.779 sec,25.0,0.077449,0.060510,0.005998
6,,2020-12-23 12:54:16,2.804 sec,30.0,0.073213,0.056345,0.005360
7,,2020-12-23 12:54:16,2.827 sec,35.0,0.069713,0.053233,0.004860
8,,2020-12-23 12:54:16,2.850 sec,40.0,0.066686,0.050517,0.004447
9,,2020-12-23 12:54:16,2.876 sec,45.0,0.064059,0.048304,0.004104
10,,2020-12-23 12:54:16,2.909 sec,50.0,0.061136,0.045976,0.003738
11,,2020-12-23 12:54:16,2.934 sec,55.0,0.058957,0.044253,0.003476
12,,2020-12-23 12:54:16,2.961 sec,60.0,0.056785,0.042487,0.003225
13,,2020-12-23 12:54:16,2.983 sec,65.0,0.054885,0.040978,0.003012
14,,2020-12-23 12:54:16,3.006 sec,70.0,0.052887,0.039306,0.002797

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           417.634766           1.000000    0.691143
1       f10            30.944672           0.074095    0.051210
2        f3            29.945110           0.071702    0.049556
3       f15            11.459804           0.027440    0.018965
4        f5            10.429785           0.024973    0.017260
5       f20            10.251256           0.024546    0.016965
6        f2             9.859209           0.023607    0.016316
7       f19             8.878176           0.021258    0.014692
8       f12             8.301757           0.019878    0.013739
9       f18             8.120420           0.019444    0.013438
10      f13             7.664119           0.018351    0.012683
11       f4             7.198557           0.017236    0.011913
12       f8             7.032873           0.016840    0.011639
13       f6             6.048911           0.014484    0.010010
14       f7             5.914305           0.014161    0.009788
15       f9             5.534474           0.013252    0.009159
16      f16             5.280519           0.012644    0.008739
17      f17             4.892844           0.011716    0.008097
18      f14             4.451653           0.010659    0.007367
19      f11             4.423503           0.010592    0.007320

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_18


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,70.0,70.0,56286.0,7.0,7.0,7.0,38.0,85.0,59.4

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.002796988672348969
RMSE: 0.0528865641949727
MAE: 0.03930626413839705
RMSLE: 0.02975009489215282
Mean Residual Deviance: 0.002796988672348969

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.008565752435562443
RMSE: 0.09255135026331297
MAE: 0.07075825450227256
RMSLE: 0.05327637685687936
Mean Residual Deviance: 0.008565752435562443

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07075825,0.0015950237,0.073111095,0.0697754,0.07021934,0.06911009,0.07157535
1,mean_residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
2,mse,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
3,r2,0.83073425,0.007195892,0.82004786,0.8361518,0.8382571,0.828117,0.83109754
4,residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
5,rmse,0.09253432,0.0019849439,0.09514227,0.090731815,0.091737635,0.09412287,0.09093701
6,rmsle,0.05326346,0.0013115642,0.054599006,0.051951602,0.05274927,0.05473171,0.052285712

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:16,2.644 sec,0.0,0.225214,0.185965,0.050721
1,,2020-12-23 12:54:16,2.682 sec,5.0,0.152731,0.126670,0.023327
2,,2020-12-23 12:54:16,2.703 sec,10.0,0.114317,0.094761,0.013068
3,,2020-12-23 12:54:16,2.723 sec,15.0,0.093848,0.076676,0.008807
4,,2020-12-23 12:54:16,2.746 sec,20.0,0.083360,0.066580,0.006949
5,,2020-12-23 12:54:16,2.779 sec,25.0,0.077449,0.060510,0.005998
6,,2020-12-23 12:54:16,2.804 sec,30.0,0.073213,0.056345,0.005360
7,,2020-12-23 12:54:16,2.827 sec,35.0,0.069713,0.053233,0.004860
8,,2020-12-23 12:54:16,2.850 sec,40.0,0.066686,0.050517,0.004447
9,,2020-12-23 12:54:16,2.876 sec,45.0,0.064059,0.048304,0.004104
10,,2020-12-23 12:54:16,2.909 sec,50.0,0.061136,0.045976,0.003738
11,,2020-12-23 12:54:16,2.934 sec,55.0,0.058957,0.044253,0.003476
12,,2020-12-23 12:54:16,2.961 sec,60.0,0.056785,0.042487,0.003225
13,,2020-12-23 12:54:16,2.983 sec,65.0,0.054885,0.040978,0.003012
14,,2020-12-23 12:54:16,3.006 sec,70.0,0.052887,0.039306,0.002797

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           417.634766           1.000000    0.691143
1       f10            30.944672           0.074095    0.051210
2        f3            29.945110           0.071702    0.049556
3       f15            11.459804           0.027440    0.018965
4        f5            10.429785           0.024973    0.017260
5       f20            10.251256           0.024546    0.016965
6        f2             9.859209           0.023607    0.016316
7       f19             8.878176           0.021258    0.014692
8       f12             8.301757           0.019878    0.013739
9       f18             8.120420           0.019444    0.013438
10      f13             7.664119           0.018351    0.012683
11       f4             7.198557           0.017236    0.011913
12       f8             7.032873           0.016840    0.011639
13       f6             6.048911           0.014484    0.010010
14       f7             5.914305           0.014161    0.009788
15       f9             5.534474           0.013252    0.009159
16      f16             5.280519           0.012644    0.008739
17      f17             4.892844           0.011716    0.008097
18      f14             4.451653           0.010659    0.007367
19      f11             4.423503           0.010592    0.007320

generic Model Build progress: |███████████████████████████████████████████| 100%
Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_19


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 261.501 weights/biases, 3,0 MB, 481.090 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,10.0,,,,,,,,,
1,,2,500,RectifierDropout,40.0,0.0,0.0,0.03817,0.028977,0.0,-0.013168,0.330038,-0.19164,0.185584
2,,3,500,RectifierDropout,40.0,0.0,0.0,0.23029,0.195647,0.0,-0.050904,0.12373,0.491002,0.390195
3,,4,1,Linear,,0.0,0.0,0.004966,0.004063,0.0,0.007173,0.041931,-0.449505,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.00729760535706338
RMSE: 0.08542602271593464
MAE: 0.06745764204101454
RMSLE: 0.04904390537064369
Mean Residual Deviance: 0.00729760535706338

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.011205257468311535
RMSE: 0.10585488873127936
MAE: 0.07584706143863312
RMSLE: NaN
Mean Residual Deviance: 0.011205257468311535

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07584706,0.0043794643,0.07674681,0.0745725,0.08297606,0.07189869,0.07304125
1,mean_residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
2,mse,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
3,r2,0.7796035,0.081327595,0.7971968,0.8180189,0.6354796,0.82662797,0.82069415
4,residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
5,rmse,0.10451367,0.018780014,0.10100256,0.09562069,0.13771963,0.09452969,0.09369576
6,rmsle,0.05666129,0.0035071012,0.06182133,0.05573497,NaN,0.055020355,0.054068506

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:37:40,0.000 sec,None,0.000000,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:37:44,19 min 59.490 sec,2816 obs/sec,3.761961,1,9593.0,0.127662,0.016297,0.095618,0.678685
2,,2020-12-23 13:37:50,20 min 5.659 sec,3128 obs/sec,11.313725,3,28850.0,0.101872,0.010378,0.078483,0.795392
3,,2020-12-23 13:37:55,20 min 10.809 sec,3433 obs/sec,18.859216,5,48091.0,0.096810,0.009372,0.075154,0.815222
4,,2020-12-23 13:38:00,20 min 15.899 sec,3604 obs/sec,26.410588,7,67347.0,0.100598,0.010120,0.079679,0.800480
5,,2020-12-23 13:38:06,20 min 22.459 sec,3871 obs/sec,37.749412,10,96261.0,0.090665,0.008220,0.071071,0.837937
6,,2020-12-23 13:38:13,20 min 29.228 sec,4013 obs/sec,49.066667,13,125120.0,0.096235,0.009261,0.075875,0.817410
7,,2020-12-23 13:38:19,20 min 34.979 sec,4210 obs/sec,60.378824,16,153966.0,0.088622,0.007854,0.069724,0.845155
8,,2020-12-23 13:38:24,20 min 40.424 sec,4399 obs/sec,71.689412,19,182808.0,0.089274,0.007970,0.069652,0.842869
9,,2020-12-23 13:38:30,20 min 45.689 sec,4562 obs/sec,83.000000,22,211650.0,0.086114,0.007416,0.066870,0.853797
10,,2020-12-23 13:38:35,20 min 50.916 sec,4693 obs/sec,94.312549,25,240497.0,0.089938,0.008089,0.070322,0.840523
11,,2020-12-23 13:38:40,20 min 56.026 sec,4809 obs/sec,105.636471,28,269373.0,0.090976,0.008277,0.070919,0.836822
12,,2020-12-23 13:38:46,21 min 2.099 sec,4990 obs/sec,120.728235,32,307857.0,0.083847,0.007030,0.065468,0.861393
13,,2020-12-23 13:38:52,21 min 8.019 sec,5150 obs/sec,135.852941,36,346425.0,0.083117,0.006908,0.064599,0.863797
14,,2020-12-23 13:38:58,21 min 14.161 sec,5269 obs/sec,150.974118,40,384984.0,0.088831,0.007891,0.069896,0.844424
15,,2020-12-23 13:39:05,21 min 20.911 sec,5338 obs/sec,166.048627,44,423424.0,0.101316,0.010265,0.079926,0.797620
16,,2020-12-23 13:39:11,21 min 27.051 sec,5327 obs/sec,177.370196,47,452294.0,0.080107,0.006417,0.061539,0.873483
17,,2020-12-23 13:39:16,21 min 32.118 sec,5369 obs/sec,188.662745,50,481090.0,0.085426,0.007298,0.067458,0.856123

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.156319
1        f4             0.493175           0.493175    0.077093
2        f2             0.459908           0.459908    0.071892
3        f3             0.398930           0.398930    0.062360
4       f12             0.321844           0.321844    0.050310
5       f10             0.311592           0.311592    0.048708
6       f15             0.302689           0.302689    0.047316
7        f8             0.293541           0.293541    0.045886
8        f6             0.287389           0.287389    0.044924
9        f9             0.256456           0.256456    0.040089
10      f13             0.251343           0.251343    0.039290
11      f16             0.240312           0.240312    0.037565
12       f5             0.239611           0.239611    0.037456
13      f17             0.237875           0.237875    0.037184
14      f18             0.231972           0.231972    0.036262
15      f11             0.223080           0.223080    0.034872
16       f7             0.222850           0.222850    0.034836
17      f19             0.212779           0.212779    0.033261
18      f14             0.208843           0.208843    0.032646
19      f20             0.202992           0.202992    0.031731

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_18


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,70.0,70.0,56286.0,7.0,7.0,7.0,38.0,85.0,59.4

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.002796988672348969
RMSE: 0.0528865641949727
MAE: 0.03930626413839705
RMSLE: 0.02975009489215282
Mean Residual Deviance: 0.002796988672348969

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.008565752435562443
RMSE: 0.09255135026331297
MAE: 0.07075825450227256
RMSLE: 0.05327637685687936
Mean Residual Deviance: 0.008565752435562443

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07075825,0.0015950237,0.073111095,0.0697754,0.07021934,0.06911009,0.07157535
1,mean_residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
2,mse,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
3,r2,0.83073425,0.007195892,0.82004786,0.8361518,0.8382571,0.828117,0.83109754
4,residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
5,rmse,0.09253432,0.0019849439,0.09514227,0.090731815,0.091737635,0.09412287,0.09093701
6,rmsle,0.05326346,0.0013115642,0.054599006,0.051951602,0.05274927,0.05473171,0.052285712

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:16,2.644 sec,0.0,0.225214,0.185965,0.050721
1,,2020-12-23 12:54:16,2.682 sec,5.0,0.152731,0.126670,0.023327
2,,2020-12-23 12:54:16,2.703 sec,10.0,0.114317,0.094761,0.013068
3,,2020-12-23 12:54:16,2.723 sec,15.0,0.093848,0.076676,0.008807
4,,2020-12-23 12:54:16,2.746 sec,20.0,0.083360,0.066580,0.006949
5,,2020-12-23 12:54:16,2.779 sec,25.0,0.077449,0.060510,0.005998
6,,2020-12-23 12:54:16,2.804 sec,30.0,0.073213,0.056345,0.005360
7,,2020-12-23 12:54:16,2.827 sec,35.0,0.069713,0.053233,0.004860
8,,2020-12-23 12:54:16,2.850 sec,40.0,0.066686,0.050517,0.004447
9,,2020-12-23 12:54:16,2.876 sec,45.0,0.064059,0.048304,0.004104
10,,2020-12-23 12:54:16,2.909 sec,50.0,0.061136,0.045976,0.003738
11,,2020-12-23 12:54:16,2.934 sec,55.0,0.058957,0.044253,0.003476
12,,2020-12-23 12:54:16,2.961 sec,60.0,0.056785,0.042487,0.003225
13,,2020-12-23 12:54:16,2.983 sec,65.0,0.054885,0.040978,0.003012
14,,2020-12-23 12:54:16,3.006 sec,70.0,0.052887,0.039306,0.002797

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           417.634766           1.000000    0.691143
1       f10            30.944672           0.074095    0.051210
2        f3            29.945110           0.071702    0.049556
3       f15            11.459804           0.027440    0.018965
4        f5            10.429785           0.024973    0.017260
5       f20            10.251256           0.024546    0.016965
6        f2             9.859209           0.023607    0.016316
7       f19             8.878176           0.021258    0.014692
8       f12             8.301757           0.019878    0.013739
9       f18             8.120420           0.019444    0.013438
10      f13             7.664119           0.018351    0.012683
11       f4             7.198557           0.017236    0.011913
12       f8             7.032873           0.016840    0.011639
13       f6             6.048911           0.014484    0.010010
14       f7             5.914305           0.014161    0.009788
15       f9             5.534474           0.013252    0.009159
16      f16             5.280519           0.012644    0.008739
17      f17             4.892844           0.011716    0.008097
18      f14             4.451653           0.010659    0.007367
19      f11             4.423503           0.010592    0.007320

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_19


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 261.501 weights/biases, 3,0 MB, 481.090 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,10.0,,,,,,,,,
1,,2,500,RectifierDropout,40.0,0.0,0.0,0.03817,0.028977,0.0,-0.013168,0.330038,-0.19164,0.185584
2,,3,500,RectifierDropout,40.0,0.0,0.0,0.23029,0.195647,0.0,-0.050904,0.12373,0.491002,0.390195
3,,4,1,Linear,,0.0,0.0,0.004966,0.004063,0.0,0.007173,0.041931,-0.449505,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.00729760535706338
RMSE: 0.08542602271593464
MAE: 0.06745764204101454
RMSLE: 0.04904390537064369
Mean Residual Deviance: 0.00729760535706338

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.011205257468311535
RMSE: 0.10585488873127936
MAE: 0.07584706143863312
RMSLE: NaN
Mean Residual Deviance: 0.011205257468311535

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07584706,0.0043794643,0.07674681,0.0745725,0.08297606,0.07189869,0.07304125
1,mean_residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
2,mse,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
3,r2,0.7796035,0.081327595,0.7971968,0.8180189,0.6354796,0.82662797,0.82069415
4,residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
5,rmse,0.10451367,0.018780014,0.10100256,0.09562069,0.13771963,0.09452969,0.09369576
6,rmsle,0.05666129,0.0035071012,0.06182133,0.05573497,NaN,0.055020355,0.054068506

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:37:40,0.000 sec,None,0.000000,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:37:44,19 min 59.490 sec,2816 obs/sec,3.761961,1,9593.0,0.127662,0.016297,0.095618,0.678685
2,,2020-12-23 13:37:50,20 min 5.659 sec,3128 obs/sec,11.313725,3,28850.0,0.101872,0.010378,0.078483,0.795392
3,,2020-12-23 13:37:55,20 min 10.809 sec,3433 obs/sec,18.859216,5,48091.0,0.096810,0.009372,0.075154,0.815222
4,,2020-12-23 13:38:00,20 min 15.899 sec,3604 obs/sec,26.410588,7,67347.0,0.100598,0.010120,0.079679,0.800480
5,,2020-12-23 13:38:06,20 min 22.459 sec,3871 obs/sec,37.749412,10,96261.0,0.090665,0.008220,0.071071,0.837937
6,,2020-12-23 13:38:13,20 min 29.228 sec,4013 obs/sec,49.066667,13,125120.0,0.096235,0.009261,0.075875,0.817410
7,,2020-12-23 13:38:19,20 min 34.979 sec,4210 obs/sec,60.378824,16,153966.0,0.088622,0.007854,0.069724,0.845155
8,,2020-12-23 13:38:24,20 min 40.424 sec,4399 obs/sec,71.689412,19,182808.0,0.089274,0.007970,0.069652,0.842869
9,,2020-12-23 13:38:30,20 min 45.689 sec,4562 obs/sec,83.000000,22,211650.0,0.086114,0.007416,0.066870,0.853797
10,,2020-12-23 13:38:35,20 min 50.916 sec,4693 obs/sec,94.312549,25,240497.0,0.089938,0.008089,0.070322,0.840523
11,,2020-12-23 13:38:40,20 min 56.026 sec,4809 obs/sec,105.636471,28,269373.0,0.090976,0.008277,0.070919,0.836822
12,,2020-12-23 13:38:46,21 min 2.099 sec,4990 obs/sec,120.728235,32,307857.0,0.083847,0.007030,0.065468,0.861393
13,,2020-12-23 13:38:52,21 min 8.019 sec,5150 obs/sec,135.852941,36,346425.0,0.083117,0.006908,0.064599,0.863797
14,,2020-12-23 13:38:58,21 min 14.161 sec,5269 obs/sec,150.974118,40,384984.0,0.088831,0.007891,0.069896,0.844424
15,,2020-12-23 13:39:05,21 min 20.911 sec,5338 obs/sec,166.048627,44,423424.0,0.101316,0.010265,0.079926,0.797620
16,,2020-12-23 13:39:11,21 min 27.051 sec,5327 obs/sec,177.370196,47,452294.0,0.080107,0.006417,0.061539,0.873483
17,,2020-12-23 13:39:16,21 min 32.118 sec,5369 obs/sec,188.662745,50,481090.0,0.085426,0.007298,0.067458,0.856123

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.156319
1        f4             0.493175           0.493175    0.077093
2        f2             0.459908           0.459908    0.071892
3        f3             0.398930           0.398930    0.062360
4       f12             0.321844           0.321844    0.050310
5       f10             0.311592           0.311592    0.048708
6       f15             0.302689           0.302689    0.047316
7        f8             0.293541           0.293541    0.045886
8        f6             0.287389           0.287389    0.044924
9        f9             0.256456           0.256456    0.040089
10      f13             0.251343           0.251343    0.039290
11      f16             0.240312           0.240312    0.037565
12       f5             0.239611           0.239611    0.037456
13      f17             0.237875           0.237875    0.037184
14      f18             0.231972           0.231972    0.036262
15      f11             0.223080           0.223080    0.034872
16       f7             0.222850           0.222850    0.034836
17      f19             0.212779           0.212779    0.033261
18      f14             0.208843           0.208843    0.032646
19      f20             0.202992           0.202992    0.031731

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_18


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,70.0,70.0,56286.0,7.0,7.0,7.0,38.0,85.0,59.4

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.002796988672348969
RMSE: 0.0528865641949727
MAE: 0.03930626413839705
RMSLE: 0.02975009489215282
Mean Residual Deviance: 0.002796988672348969

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.008565752435562443
RMSE: 0.09255135026331297
MAE: 0.07075825450227256
RMSLE: 0.05327637685687936
Mean Residual Deviance: 0.008565752435562443

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07075825,0.0015950237,0.073111095,0.0697754,0.07021934,0.06911009,0.07157535
1,mean_residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
2,mse,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
3,r2,0.83073425,0.007195892,0.82004786,0.8361518,0.8382571,0.828117,0.83109754
4,residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
5,rmse,0.09253432,0.0019849439,0.09514227,0.090731815,0.091737635,0.09412287,0.09093701
6,rmsle,0.05326346,0.0013115642,0.054599006,0.051951602,0.05274927,0.05473171,0.052285712

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:16,2.644 sec,0.0,0.225214,0.185965,0.050721
1,,2020-12-23 12:54:16,2.682 sec,5.0,0.152731,0.126670,0.023327
2,,2020-12-23 12:54:16,2.703 sec,10.0,0.114317,0.094761,0.013068
3,,2020-12-23 12:54:16,2.723 sec,15.0,0.093848,0.076676,0.008807
4,,2020-12-23 12:54:16,2.746 sec,20.0,0.083360,0.066580,0.006949
5,,2020-12-23 12:54:16,2.779 sec,25.0,0.077449,0.060510,0.005998
6,,2020-12-23 12:54:16,2.804 sec,30.0,0.073213,0.056345,0.005360
7,,2020-12-23 12:54:16,2.827 sec,35.0,0.069713,0.053233,0.004860
8,,2020-12-23 12:54:16,2.850 sec,40.0,0.066686,0.050517,0.004447
9,,2020-12-23 12:54:16,2.876 sec,45.0,0.064059,0.048304,0.004104
10,,2020-12-23 12:54:16,2.909 sec,50.0,0.061136,0.045976,0.003738
11,,2020-12-23 12:54:16,2.934 sec,55.0,0.058957,0.044253,0.003476
12,,2020-12-23 12:54:16,2.961 sec,60.0,0.056785,0.042487,0.003225
13,,2020-12-23 12:54:16,2.983 sec,65.0,0.054885,0.040978,0.003012
14,,2020-12-23 12:54:16,3.006 sec,70.0,0.052887,0.039306,0.002797

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           417.634766           1.000000    0.691143
1       f10            30.944672           0.074095    0.051210
2        f3            29.945110           0.071702    0.049556
3       f15            11.459804           0.027440    0.018965
4        f5            10.429785           0.024973    0.017260
5       f20            10.251256           0.024546    0.016965
6        f2             9.859209           0.023607    0.016316
7       f19             8.878176           0.021258    0.014692
8       f12             8.301757           0.019878    0.013739
9       f18             8.120420           0.019444    0.013438
10      f13             7.664119           0.018351    0.012683
11       f4             7.198557           0.017236    0.011913
12       f8             7.032873           0.016840    0.011639
13       f6             6.048911           0.014484    0.010010
14       f7             5.914305           0.014161    0.009788
15       f9             5.534474           0.013252    0.009159
16      f16             5.280519           0.012644    0.008739
17      f17             4.892844           0.011716    0.008097
18      f14             4.451653           0.010659    0.007367
19      f11             4.423503           0.010592    0.007320

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_19


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 261.501 weights/biases, 3,0 MB, 481.090 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,10.0,,,,,,,,,
1,,2,500,RectifierDropout,40.0,0.0,0.0,0.03817,0.028977,0.0,-0.013168,0.330038,-0.19164,0.185584
2,,3,500,RectifierDropout,40.0,0.0,0.0,0.23029,0.195647,0.0,-0.050904,0.12373,0.491002,0.390195
3,,4,1,Linear,,0.0,0.0,0.004966,0.004063,0.0,0.007173,0.041931,-0.449505,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.00729760535706338
RMSE: 0.08542602271593464
MAE: 0.06745764204101454
RMSLE: 0.04904390537064369
Mean Residual Deviance: 0.00729760535706338

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.011205257468311535
RMSE: 0.10585488873127936
MAE: 0.07584706143863312
RMSLE: NaN
Mean Residual Deviance: 0.011205257468311535

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07584706,0.0043794643,0.07674681,0.0745725,0.08297606,0.07189869,0.07304125
1,mean_residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
2,mse,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
3,r2,0.7796035,0.081327595,0.7971968,0.8180189,0.6354796,0.82662797,0.82069415
4,residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
5,rmse,0.10451367,0.018780014,0.10100256,0.09562069,0.13771963,0.09452969,0.09369576
6,rmsle,0.05666129,0.0035071012,0.06182133,0.05573497,NaN,0.055020355,0.054068506

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:37:40,0.000 sec,None,0.000000,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:37:44,19 min 59.490 sec,2816 obs/sec,3.761961,1,9593.0,0.127662,0.016297,0.095618,0.678685
2,,2020-12-23 13:37:50,20 min 5.659 sec,3128 obs/sec,11.313725,3,28850.0,0.101872,0.010378,0.078483,0.795392
3,,2020-12-23 13:37:55,20 min 10.809 sec,3433 obs/sec,18.859216,5,48091.0,0.096810,0.009372,0.075154,0.815222
4,,2020-12-23 13:38:00,20 min 15.899 sec,3604 obs/sec,26.410588,7,67347.0,0.100598,0.010120,0.079679,0.800480
5,,2020-12-23 13:38:06,20 min 22.459 sec,3871 obs/sec,37.749412,10,96261.0,0.090665,0.008220,0.071071,0.837937
6,,2020-12-23 13:38:13,20 min 29.228 sec,4013 obs/sec,49.066667,13,125120.0,0.096235,0.009261,0.075875,0.817410
7,,2020-12-23 13:38:19,20 min 34.979 sec,4210 obs/sec,60.378824,16,153966.0,0.088622,0.007854,0.069724,0.845155
8,,2020-12-23 13:38:24,20 min 40.424 sec,4399 obs/sec,71.689412,19,182808.0,0.089274,0.007970,0.069652,0.842869
9,,2020-12-23 13:38:30,20 min 45.689 sec,4562 obs/sec,83.000000,22,211650.0,0.086114,0.007416,0.066870,0.853797
10,,2020-12-23 13:38:35,20 min 50.916 sec,4693 obs/sec,94.312549,25,240497.0,0.089938,0.008089,0.070322,0.840523
11,,2020-12-23 13:38:40,20 min 56.026 sec,4809 obs/sec,105.636471,28,269373.0,0.090976,0.008277,0.070919,0.836822
12,,2020-12-23 13:38:46,21 min 2.099 sec,4990 obs/sec,120.728235,32,307857.0,0.083847,0.007030,0.065468,0.861393
13,,2020-12-23 13:38:52,21 min 8.019 sec,5150 obs/sec,135.852941,36,346425.0,0.083117,0.006908,0.064599,0.863797
14,,2020-12-23 13:38:58,21 min 14.161 sec,5269 obs/sec,150.974118,40,384984.0,0.088831,0.007891,0.069896,0.844424
15,,2020-12-23 13:39:05,21 min 20.911 sec,5338 obs/sec,166.048627,44,423424.0,0.101316,0.010265,0.079926,0.797620
16,,2020-12-23 13:39:11,21 min 27.051 sec,5327 obs/sec,177.370196,47,452294.0,0.080107,0.006417,0.061539,0.873483
17,,2020-12-23 13:39:16,21 min 32.118 sec,5369 obs/sec,188.662745,50,481090.0,0.085426,0.007298,0.067458,0.856123

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.156319
1        f4             0.493175           0.493175    0.077093
2        f2             0.459908           0.459908    0.071892
3        f3             0.398930           0.398930    0.062360
4       f12             0.321844           0.321844    0.050310
5       f10             0.311592           0.311592    0.048708
6       f15             0.302689           0.302689    0.047316
7        f8             0.293541           0.293541    0.045886
8        f6             0.287389           0.287389    0.044924
9        f9             0.256456           0.256456    0.040089
10      f13             0.251343           0.251343    0.039290
11      f16             0.240312           0.240312    0.037565
12       f5             0.239611           0.239611    0.037456
13      f17             0.237875           0.237875    0.037184
14      f18             0.231972           0.231972    0.036262
15      f11             0.223080           0.223080    0.034872
16       f7             0.222850           0.222850    0.034836
17      f19             0.212779           0.212779    0.033261
18      f14             0.208843           0.208843    0.032646
19      f20             0.202992           0.202992    0.031731

generic Model Build progress: |███████████████████████████████████████████| 100%
Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_20


Model Summary:

     number_of_trees
0               66.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.0025619836264292946
RMSE: 0.050616041196732235
MAE: 0.037218359029468365
RMSLE: 0.02969996879826354
Mean Residual Deviance: 0.0025619836264292946

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.00960723226988264
RMSE: 0.09801648978555925
MAE: 0.07469173306197513
RMSLE: 0.0567924452238901
Mean Residual Deviance: 0.00960723226988264

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.074691735,5.725854E-4,0.07488511,0.07421965,0.07481219,0.07405527,0.075486444
1,mean_residual_deviance,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
2,mse,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
3,r2,0.81016636,0.007088534,0.79900324,0.8179848,0.81403804,0.8101439,0.8096617
4,residual_deviance,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
5,rmse,0.09800092,0.0019531453,0.10055173,0.09562964,0.09836645,0.098921575,0.09653521
6,rmsle,0.056777377,0.0014626358,0.058009323,0.05469224,0.057631172,0.057767715,0.05578643

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:40,3.144 sec,0.0,0.321817,0.275443,0.103566
1,,2020-12-23 12:54:40,3.182 sec,5.0,0.126302,0.100556,0.015952
2,,2020-12-23 12:54:40,3.218 sec,10.0,0.094670,0.074348,0.008962
3,,2020-12-23 12:54:40,3.255 sec,15.0,0.083996,0.064563,0.007055
4,,2020-12-23 12:54:40,3.300 sec,20.0,0.077379,0.058583,0.005988
5,,2020-12-23 12:54:40,3.340 sec,25.0,0.072255,0.054362,0.005221
6,,2020-12-23 12:54:40,3.382 sec,30.0,0.067800,0.050808,0.004597
7,,2020-12-23 12:54:40,3.421 sec,35.0,0.064439,0.048038,0.004152
8,,2020-12-23 12:54:40,3.469 sec,40.0,0.061331,0.045627,0.003761
9,,2020-12-23 12:54:40,3.508 sec,45.0,0.058635,0.043507,0.003438
10,,2020-12-23 12:54:40,3.563 sec,50.0,0.056371,0.041778,0.003178
11,,2020-12-23 12:54:40,3.604 sec,55.0,0.054163,0.040042,0.002934
12,,2020-12-23 12:54:40,3.658 sec,60.0,0.052323,0.038622,0.002738
13,,2020-12-23 12:54:40,3.701 sec,65.0,0.050900,0.037458,0.002591
14,,2020-12-23 12:54:40,3.719 sec,66.0,0.050616,0.037218,0.002562

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           102.506783           1.000000    0.599223
1       f10            19.639147           0.191589    0.114804
2        f5            10.862881           0.105972    0.063501
3        f3             5.370502           0.052392    0.031394
4        f2             4.630992           0.045177    0.027071
5       f11             3.341065           0.032594    0.019531
6        f4             3.227701           0.031488    0.018868
7       f20             2.737843           0.026709    0.016005
8       f18             2.179754           0.021264    0.012742
9       f19             1.921421           0.018744    0.011232
10      f12             1.849532           0.018043    0.010812
11      f15             1.829120           0.017844    0.010692
12      f13             1.791575           0.017478    0.010473
13       f6             1.544740           0.015070    0.009030
14      f16             1.534647           0.014971    0.008971
15       f8             1.505961           0.014691    0.008803
16       f9             1.348663           0.013157    0.007884
17       f7             1.189082           0.011600    0.006951
18      f14             1.028377           0.010032    0.006012
19      f17             1.026396           0.010013    0.006000

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_18


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,70.0,70.0,56286.0,7.0,7.0,7.0,38.0,85.0,59.4

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.002796988672348969
RMSE: 0.0528865641949727
MAE: 0.03930626413839705
RMSLE: 0.02975009489215282
Mean Residual Deviance: 0.002796988672348969

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.008565752435562443
RMSE: 0.09255135026331297
MAE: 0.07075825450227256
RMSLE: 0.05327637685687936
Mean Residual Deviance: 0.008565752435562443

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07075825,0.0015950237,0.073111095,0.0697754,0.07021934,0.06911009,0.07157535
1,mean_residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
2,mse,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
3,r2,0.83073425,0.007195892,0.82004786,0.8361518,0.8382571,0.828117,0.83109754
4,residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
5,rmse,0.09253432,0.0019849439,0.09514227,0.090731815,0.091737635,0.09412287,0.09093701
6,rmsle,0.05326346,0.0013115642,0.054599006,0.051951602,0.05274927,0.05473171,0.052285712

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:16,2.644 sec,0.0,0.225214,0.185965,0.050721
1,,2020-12-23 12:54:16,2.682 sec,5.0,0.152731,0.126670,0.023327
2,,2020-12-23 12:54:16,2.703 sec,10.0,0.114317,0.094761,0.013068
3,,2020-12-23 12:54:16,2.723 sec,15.0,0.093848,0.076676,0.008807
4,,2020-12-23 12:54:16,2.746 sec,20.0,0.083360,0.066580,0.006949
5,,2020-12-23 12:54:16,2.779 sec,25.0,0.077449,0.060510,0.005998
6,,2020-12-23 12:54:16,2.804 sec,30.0,0.073213,0.056345,0.005360
7,,2020-12-23 12:54:16,2.827 sec,35.0,0.069713,0.053233,0.004860
8,,2020-12-23 12:54:16,2.850 sec,40.0,0.066686,0.050517,0.004447
9,,2020-12-23 12:54:16,2.876 sec,45.0,0.064059,0.048304,0.004104
10,,2020-12-23 12:54:16,2.909 sec,50.0,0.061136,0.045976,0.003738
11,,2020-12-23 12:54:16,2.934 sec,55.0,0.058957,0.044253,0.003476
12,,2020-12-23 12:54:16,2.961 sec,60.0,0.056785,0.042487,0.003225
13,,2020-12-23 12:54:16,2.983 sec,65.0,0.054885,0.040978,0.003012
14,,2020-12-23 12:54:16,3.006 sec,70.0,0.052887,0.039306,0.002797

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           417.634766           1.000000    0.691143
1       f10            30.944672           0.074095    0.051210
2        f3            29.945110           0.071702    0.049556
3       f15            11.459804           0.027440    0.018965
4        f5            10.429785           0.024973    0.017260
5       f20            10.251256           0.024546    0.016965
6        f2             9.859209           0.023607    0.016316
7       f19             8.878176           0.021258    0.014692
8       f12             8.301757           0.019878    0.013739
9       f18             8.120420           0.019444    0.013438
10      f13             7.664119           0.018351    0.012683
11       f4             7.198557           0.017236    0.011913
12       f8             7.032873           0.016840    0.011639
13       f6             6.048911           0.014484    0.010010
14       f7             5.914305           0.014161    0.009788
15       f9             5.534474           0.013252    0.009159
16      f16             5.280519           0.012644    0.008739
17      f17             4.892844           0.011716    0.008097
18      f14             4.451653           0.010659    0.007367
19      f11             4.423503           0.010592    0.007320

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_19


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 261.501 weights/biases, 3,0 MB, 481.090 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,10.0,,,,,,,,,
1,,2,500,RectifierDropout,40.0,0.0,0.0,0.03817,0.028977,0.0,-0.013168,0.330038,-0.19164,0.185584
2,,3,500,RectifierDropout,40.0,0.0,0.0,0.23029,0.195647,0.0,-0.050904,0.12373,0.491002,0.390195
3,,4,1,Linear,,0.0,0.0,0.004966,0.004063,0.0,0.007173,0.041931,-0.449505,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.00729760535706338
RMSE: 0.08542602271593464
MAE: 0.06745764204101454
RMSLE: 0.04904390537064369
Mean Residual Deviance: 0.00729760535706338

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.011205257468311535
RMSE: 0.10585488873127936
MAE: 0.07584706143863312
RMSLE: NaN
Mean Residual Deviance: 0.011205257468311535

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07584706,0.0043794643,0.07674681,0.0745725,0.08297606,0.07189869,0.07304125
1,mean_residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
2,mse,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
3,r2,0.7796035,0.081327595,0.7971968,0.8180189,0.6354796,0.82662797,0.82069415
4,residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
5,rmse,0.10451367,0.018780014,0.10100256,0.09562069,0.13771963,0.09452969,0.09369576
6,rmsle,0.05666129,0.0035071012,0.06182133,0.05573497,NaN,0.055020355,0.054068506

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:37:40,0.000 sec,None,0.000000,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:37:44,19 min 59.490 sec,2816 obs/sec,3.761961,1,9593.0,0.127662,0.016297,0.095618,0.678685
2,,2020-12-23 13:37:50,20 min 5.659 sec,3128 obs/sec,11.313725,3,28850.0,0.101872,0.010378,0.078483,0.795392
3,,2020-12-23 13:37:55,20 min 10.809 sec,3433 obs/sec,18.859216,5,48091.0,0.096810,0.009372,0.075154,0.815222
4,,2020-12-23 13:38:00,20 min 15.899 sec,3604 obs/sec,26.410588,7,67347.0,0.100598,0.010120,0.079679,0.800480
5,,2020-12-23 13:38:06,20 min 22.459 sec,3871 obs/sec,37.749412,10,96261.0,0.090665,0.008220,0.071071,0.837937
6,,2020-12-23 13:38:13,20 min 29.228 sec,4013 obs/sec,49.066667,13,125120.0,0.096235,0.009261,0.075875,0.817410
7,,2020-12-23 13:38:19,20 min 34.979 sec,4210 obs/sec,60.378824,16,153966.0,0.088622,0.007854,0.069724,0.845155
8,,2020-12-23 13:38:24,20 min 40.424 sec,4399 obs/sec,71.689412,19,182808.0,0.089274,0.007970,0.069652,0.842869
9,,2020-12-23 13:38:30,20 min 45.689 sec,4562 obs/sec,83.000000,22,211650.0,0.086114,0.007416,0.066870,0.853797
10,,2020-12-23 13:38:35,20 min 50.916 sec,4693 obs/sec,94.312549,25,240497.0,0.089938,0.008089,0.070322,0.840523
11,,2020-12-23 13:38:40,20 min 56.026 sec,4809 obs/sec,105.636471,28,269373.0,0.090976,0.008277,0.070919,0.836822
12,,2020-12-23 13:38:46,21 min 2.099 sec,4990 obs/sec,120.728235,32,307857.0,0.083847,0.007030,0.065468,0.861393
13,,2020-12-23 13:38:52,21 min 8.019 sec,5150 obs/sec,135.852941,36,346425.0,0.083117,0.006908,0.064599,0.863797
14,,2020-12-23 13:38:58,21 min 14.161 sec,5269 obs/sec,150.974118,40,384984.0,0.088831,0.007891,0.069896,0.844424
15,,2020-12-23 13:39:05,21 min 20.911 sec,5338 obs/sec,166.048627,44,423424.0,0.101316,0.010265,0.079926,0.797620
16,,2020-12-23 13:39:11,21 min 27.051 sec,5327 obs/sec,177.370196,47,452294.0,0.080107,0.006417,0.061539,0.873483
17,,2020-12-23 13:39:16,21 min 32.118 sec,5369 obs/sec,188.662745,50,481090.0,0.085426,0.007298,0.067458,0.856123

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.156319
1        f4             0.493175           0.493175    0.077093
2        f2             0.459908           0.459908    0.071892
3        f3             0.398930           0.398930    0.062360
4       f12             0.321844           0.321844    0.050310
5       f10             0.311592           0.311592    0.048708
6       f15             0.302689           0.302689    0.047316
7        f8             0.293541           0.293541    0.045886
8        f6             0.287389           0.287389    0.044924
9        f9             0.256456           0.256456    0.040089
10      f13             0.251343           0.251343    0.039290
11      f16             0.240312           0.240312    0.037565
12       f5             0.239611           0.239611    0.037456
13      f17             0.237875           0.237875    0.037184
14      f18             0.231972           0.231972    0.036262
15      f11             0.223080           0.223080    0.034872
16       f7             0.222850           0.222850    0.034836
17      f19             0.212779           0.212779    0.033261
18      f14             0.208843           0.208843    0.032646
19      f20             0.202992           0.202992    0.031731

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_20


Model Summary:

     number_of_trees
0               66.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.0025619836264292946
RMSE: 0.050616041196732235
MAE: 0.037218359029468365
RMSLE: 0.02969996879826354
Mean Residual Deviance: 0.0025619836264292946

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.00960723226988264
RMSE: 0.09801648978555925
MAE: 0.07469173306197513
RMSLE: 0.0567924452238901
Mean Residual Deviance: 0.00960723226988264

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.074691735,5.725854E-4,0.07488511,0.07421965,0.07481219,0.07405527,0.075486444
1,mean_residual_deviance,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
2,mse,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
3,r2,0.81016636,0.007088534,0.79900324,0.8179848,0.81403804,0.8101439,0.8096617
4,residual_deviance,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
5,rmse,0.09800092,0.0019531453,0.10055173,0.09562964,0.09836645,0.098921575,0.09653521
6,rmsle,0.056777377,0.0014626358,0.058009323,0.05469224,0.057631172,0.057767715,0.05578643

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:40,3.144 sec,0.0,0.321817,0.275443,0.103566
1,,2020-12-23 12:54:40,3.182 sec,5.0,0.126302,0.100556,0.015952
2,,2020-12-23 12:54:40,3.218 sec,10.0,0.094670,0.074348,0.008962
3,,2020-12-23 12:54:40,3.255 sec,15.0,0.083996,0.064563,0.007055
4,,2020-12-23 12:54:40,3.300 sec,20.0,0.077379,0.058583,0.005988
5,,2020-12-23 12:54:40,3.340 sec,25.0,0.072255,0.054362,0.005221
6,,2020-12-23 12:54:40,3.382 sec,30.0,0.067800,0.050808,0.004597
7,,2020-12-23 12:54:40,3.421 sec,35.0,0.064439,0.048038,0.004152
8,,2020-12-23 12:54:40,3.469 sec,40.0,0.061331,0.045627,0.003761
9,,2020-12-23 12:54:40,3.508 sec,45.0,0.058635,0.043507,0.003438
10,,2020-12-23 12:54:40,3.563 sec,50.0,0.056371,0.041778,0.003178
11,,2020-12-23 12:54:40,3.604 sec,55.0,0.054163,0.040042,0.002934
12,,2020-12-23 12:54:40,3.658 sec,60.0,0.052323,0.038622,0.002738
13,,2020-12-23 12:54:40,3.701 sec,65.0,0.050900,0.037458,0.002591
14,,2020-12-23 12:54:40,3.719 sec,66.0,0.050616,0.037218,0.002562

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           102.506783           1.000000    0.599223
1       f10            19.639147           0.191589    0.114804
2        f5            10.862881           0.105972    0.063501
3        f3             5.370502           0.052392    0.031394
4        f2             4.630992           0.045177    0.027071
5       f11             3.341065           0.032594    0.019531
6        f4             3.227701           0.031488    0.018868
7       f20             2.737843           0.026709    0.016005
8       f18             2.179754           0.021264    0.012742
9       f19             1.921421           0.018744    0.011232
10      f12             1.849532           0.018043    0.010812
11      f15             1.829120           0.017844    0.010692
12      f13             1.791575           0.017478    0.010473
13       f6             1.544740           0.015070    0.009030
14      f16             1.534647           0.014971    0.008971
15       f8             1.505961           0.014691    0.008803
16       f9             1.348663           0.013157    0.007884
17       f7             1.189082           0.011600    0.006951
18      f14             1.028377           0.010032    0.006012
19      f17             1.026396           0.010013    0.006000

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_18


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,70.0,70.0,56286.0,7.0,7.0,7.0,38.0,85.0,59.4

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.002796988672348969
RMSE: 0.0528865641949727
MAE: 0.03930626413839705
RMSLE: 0.02975009489215282
Mean Residual Deviance: 0.002796988672348969

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.008565752435562443
RMSE: 0.09255135026331297
MAE: 0.07075825450227256
RMSLE: 0.05327637685687936
Mean Residual Deviance: 0.008565752435562443

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07075825,0.0015950237,0.073111095,0.0697754,0.07021934,0.06911009,0.07157535
1,mean_residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
2,mse,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
3,r2,0.83073425,0.007195892,0.82004786,0.8361518,0.8382571,0.828117,0.83109754
4,residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
5,rmse,0.09253432,0.0019849439,0.09514227,0.090731815,0.091737635,0.09412287,0.09093701
6,rmsle,0.05326346,0.0013115642,0.054599006,0.051951602,0.05274927,0.05473171,0.052285712

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:16,2.644 sec,0.0,0.225214,0.185965,0.050721
1,,2020-12-23 12:54:16,2.682 sec,5.0,0.152731,0.126670,0.023327
2,,2020-12-23 12:54:16,2.703 sec,10.0,0.114317,0.094761,0.013068
3,,2020-12-23 12:54:16,2.723 sec,15.0,0.093848,0.076676,0.008807
4,,2020-12-23 12:54:16,2.746 sec,20.0,0.083360,0.066580,0.006949
5,,2020-12-23 12:54:16,2.779 sec,25.0,0.077449,0.060510,0.005998
6,,2020-12-23 12:54:16,2.804 sec,30.0,0.073213,0.056345,0.005360
7,,2020-12-23 12:54:16,2.827 sec,35.0,0.069713,0.053233,0.004860
8,,2020-12-23 12:54:16,2.850 sec,40.0,0.066686,0.050517,0.004447
9,,2020-12-23 12:54:16,2.876 sec,45.0,0.064059,0.048304,0.004104
10,,2020-12-23 12:54:16,2.909 sec,50.0,0.061136,0.045976,0.003738
11,,2020-12-23 12:54:16,2.934 sec,55.0,0.058957,0.044253,0.003476
12,,2020-12-23 12:54:16,2.961 sec,60.0,0.056785,0.042487,0.003225
13,,2020-12-23 12:54:16,2.983 sec,65.0,0.054885,0.040978,0.003012
14,,2020-12-23 12:54:16,3.006 sec,70.0,0.052887,0.039306,0.002797

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           417.634766           1.000000    0.691143
1       f10            30.944672           0.074095    0.051210
2        f3            29.945110           0.071702    0.049556
3       f15            11.459804           0.027440    0.018965
4        f5            10.429785           0.024973    0.017260
5       f20            10.251256           0.024546    0.016965
6        f2             9.859209           0.023607    0.016316
7       f19             8.878176           0.021258    0.014692
8       f12             8.301757           0.019878    0.013739
9       f18             8.120420           0.019444    0.013438
10      f13             7.664119           0.018351    0.012683
11       f4             7.198557           0.017236    0.011913
12       f8             7.032873           0.016840    0.011639
13       f6             6.048911           0.014484    0.010010
14       f7             5.914305           0.014161    0.009788
15       f9             5.534474           0.013252    0.009159
16      f16             5.280519           0.012644    0.008739
17      f17             4.892844           0.011716    0.008097
18      f14             4.451653           0.010659    0.007367
19      f11             4.423503           0.010592    0.007320

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_19


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 261.501 weights/biases, 3,0 MB, 481.090 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,10.0,,,,,,,,,
1,,2,500,RectifierDropout,40.0,0.0,0.0,0.03817,0.028977,0.0,-0.013168,0.330038,-0.19164,0.185584
2,,3,500,RectifierDropout,40.0,0.0,0.0,0.23029,0.195647,0.0,-0.050904,0.12373,0.491002,0.390195
3,,4,1,Linear,,0.0,0.0,0.004966,0.004063,0.0,0.007173,0.041931,-0.449505,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.00729760535706338
RMSE: 0.08542602271593464
MAE: 0.06745764204101454
RMSLE: 0.04904390537064369
Mean Residual Deviance: 0.00729760535706338

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.011205257468311535
RMSE: 0.10585488873127936
MAE: 0.07584706143863312
RMSLE: NaN
Mean Residual Deviance: 0.011205257468311535

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07584706,0.0043794643,0.07674681,0.0745725,0.08297606,0.07189869,0.07304125
1,mean_residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
2,mse,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
3,r2,0.7796035,0.081327595,0.7971968,0.8180189,0.6354796,0.82662797,0.82069415
4,residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
5,rmse,0.10451367,0.018780014,0.10100256,0.09562069,0.13771963,0.09452969,0.09369576
6,rmsle,0.05666129,0.0035071012,0.06182133,0.05573497,NaN,0.055020355,0.054068506

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:37:40,0.000 sec,None,0.000000,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:37:44,19 min 59.490 sec,2816 obs/sec,3.761961,1,9593.0,0.127662,0.016297,0.095618,0.678685
2,,2020-12-23 13:37:50,20 min 5.659 sec,3128 obs/sec,11.313725,3,28850.0,0.101872,0.010378,0.078483,0.795392
3,,2020-12-23 13:37:55,20 min 10.809 sec,3433 obs/sec,18.859216,5,48091.0,0.096810,0.009372,0.075154,0.815222
4,,2020-12-23 13:38:00,20 min 15.899 sec,3604 obs/sec,26.410588,7,67347.0,0.100598,0.010120,0.079679,0.800480
5,,2020-12-23 13:38:06,20 min 22.459 sec,3871 obs/sec,37.749412,10,96261.0,0.090665,0.008220,0.071071,0.837937
6,,2020-12-23 13:38:13,20 min 29.228 sec,4013 obs/sec,49.066667,13,125120.0,0.096235,0.009261,0.075875,0.817410
7,,2020-12-23 13:38:19,20 min 34.979 sec,4210 obs/sec,60.378824,16,153966.0,0.088622,0.007854,0.069724,0.845155
8,,2020-12-23 13:38:24,20 min 40.424 sec,4399 obs/sec,71.689412,19,182808.0,0.089274,0.007970,0.069652,0.842869
9,,2020-12-23 13:38:30,20 min 45.689 sec,4562 obs/sec,83.000000,22,211650.0,0.086114,0.007416,0.066870,0.853797
10,,2020-12-23 13:38:35,20 min 50.916 sec,4693 obs/sec,94.312549,25,240497.0,0.089938,0.008089,0.070322,0.840523
11,,2020-12-23 13:38:40,20 min 56.026 sec,4809 obs/sec,105.636471,28,269373.0,0.090976,0.008277,0.070919,0.836822
12,,2020-12-23 13:38:46,21 min 2.099 sec,4990 obs/sec,120.728235,32,307857.0,0.083847,0.007030,0.065468,0.861393
13,,2020-12-23 13:38:52,21 min 8.019 sec,5150 obs/sec,135.852941,36,346425.0,0.083117,0.006908,0.064599,0.863797
14,,2020-12-23 13:38:58,21 min 14.161 sec,5269 obs/sec,150.974118,40,384984.0,0.088831,0.007891,0.069896,0.844424
15,,2020-12-23 13:39:05,21 min 20.911 sec,5338 obs/sec,166.048627,44,423424.0,0.101316,0.010265,0.079926,0.797620
16,,2020-12-23 13:39:11,21 min 27.051 sec,5327 obs/sec,177.370196,47,452294.0,0.080107,0.006417,0.061539,0.873483
17,,2020-12-23 13:39:16,21 min 32.118 sec,5369 obs/sec,188.662745,50,481090.0,0.085426,0.007298,0.067458,0.856123

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.156319
1        f4             0.493175           0.493175    0.077093
2        f2             0.459908           0.459908    0.071892
3        f3             0.398930           0.398930    0.062360
4       f12             0.321844           0.321844    0.050310
5       f10             0.311592           0.311592    0.048708
6       f15             0.302689           0.302689    0.047316
7        f8             0.293541           0.293541    0.045886
8        f6             0.287389           0.287389    0.044924
9        f9             0.256456           0.256456    0.040089
10      f13             0.251343           0.251343    0.039290
11      f16             0.240312           0.240312    0.037565
12       f5             0.239611           0.239611    0.037456
13      f17             0.237875           0.237875    0.037184
14      f18             0.231972           0.231972    0.036262
15      f11             0.223080           0.223080    0.034872
16       f7             0.222850           0.222850    0.034836
17      f19             0.212779           0.212779    0.033261
18      f14             0.208843           0.208843    0.032646
19      f20             0.202992           0.202992    0.031731

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_20


Model Summary:

     number_of_trees
0               66.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.0025619836264292946
RMSE: 0.050616041196732235
MAE: 0.037218359029468365
RMSLE: 0.02969996879826354
Mean Residual Deviance: 0.0025619836264292946

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.00960723226988264
RMSE: 0.09801648978555925
MAE: 0.07469173306197513
RMSLE: 0.0567924452238901
Mean Residual Deviance: 0.00960723226988264

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.074691735,5.725854E-4,0.07488511,0.07421965,0.07481219,0.07405527,0.075486444
1,mean_residual_deviance,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
2,mse,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
3,r2,0.81016636,0.007088534,0.79900324,0.8179848,0.81403804,0.8101439,0.8096617
4,residual_deviance,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
5,rmse,0.09800092,0.0019531453,0.10055173,0.09562964,0.09836645,0.098921575,0.09653521
6,rmsle,0.056777377,0.0014626358,0.058009323,0.05469224,0.057631172,0.057767715,0.05578643

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:40,3.144 sec,0.0,0.321817,0.275443,0.103566
1,,2020-12-23 12:54:40,3.182 sec,5.0,0.126302,0.100556,0.015952
2,,2020-12-23 12:54:40,3.218 sec,10.0,0.094670,0.074348,0.008962
3,,2020-12-23 12:54:40,3.255 sec,15.0,0.083996,0.064563,0.007055
4,,2020-12-23 12:54:40,3.300 sec,20.0,0.077379,0.058583,0.005988
5,,2020-12-23 12:54:40,3.340 sec,25.0,0.072255,0.054362,0.005221
6,,2020-12-23 12:54:40,3.382 sec,30.0,0.067800,0.050808,0.004597
7,,2020-12-23 12:54:40,3.421 sec,35.0,0.064439,0.048038,0.004152
8,,2020-12-23 12:54:40,3.469 sec,40.0,0.061331,0.045627,0.003761
9,,2020-12-23 12:54:40,3.508 sec,45.0,0.058635,0.043507,0.003438
10,,2020-12-23 12:54:40,3.563 sec,50.0,0.056371,0.041778,0.003178
11,,2020-12-23 12:54:40,3.604 sec,55.0,0.054163,0.040042,0.002934
12,,2020-12-23 12:54:40,3.658 sec,60.0,0.052323,0.038622,0.002738
13,,2020-12-23 12:54:40,3.701 sec,65.0,0.050900,0.037458,0.002591
14,,2020-12-23 12:54:40,3.719 sec,66.0,0.050616,0.037218,0.002562

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           102.506783           1.000000    0.599223
1       f10            19.639147           0.191589    0.114804
2        f5            10.862881           0.105972    0.063501
3        f3             5.370502           0.052392    0.031394
4        f2             4.630992           0.045177    0.027071
5       f11             3.341065           0.032594    0.019531
6        f4             3.227701           0.031488    0.018868
7       f20             2.737843           0.026709    0.016005
8       f18             2.179754           0.021264    0.012742
9       f19             1.921421           0.018744    0.011232
10      f12             1.849532           0.018043    0.010812
11      f15             1.829120           0.017844    0.010692
12      f13             1.791575           0.017478    0.010473
13       f6             1.544740           0.015070    0.009030
14      f16             1.534647           0.014971    0.008971
15       f8             1.505961           0.014691    0.008803
16       f9             1.348663           0.013157    0.007884
17       f7             1.189082           0.011600    0.006951
18      f14             1.028377           0.010032    0.006012
19      f17             1.026396           0.010013    0.006000

generic Model Build progress: |███████████████████████████████████████████| 100%
Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_21


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 261.501 weights/biases, 3,0 MB, 495.026 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,15.0,,,,,,,,,
1,,2,500,RectifierDropout,50.0,0.0,0.0,0.026827,0.025393,0.0,-0.009272,0.243334,-0.136184,0.159472
2,,3,500,RectifierDropout,50.0,0.0,0.0,0.149113,0.187165,0.0,-0.038966,0.083189,0.339939,0.256063
3,,4,1,Linear,,0.0,0.0,0.00539,0.00577,0.0,0.02981,0.06136,-0.760539,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.009972619466394538
RMSE: 0.09986300349175634
MAE: 0.07856480604502232
RMSLE: 0.056257833557788614
Mean Residual Deviance: 0.009972619466394538

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.009885179205877049
RMSE: 0.09942423852299322
MAE: 0.07551967978711813
RMSLE: 0.06587140651189652
Mean Residual Deviance: 0.009885179205877049

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07551968,0.006375736,0.07344144,0.071399465,0.086805485,0.072270736,0.073681265
1,mean_residual_deviance,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
2,mse,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
3,r2,0.8051752,0.03584341,0.8090461,0.83599246,0.7436621,0.8146722,0.82250315
4,residual_deviance,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
5,rmse,0.09904585,0.009688791,0.098007485,0.09077592,0.11548919,0.097734764,0.0932219
6,rmsle,0.06443256,0.015308772,0.06754833,0.054155853,0.089891285,0.057095427,0.053471938

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:45:36,0.000 sec,None,0.000000,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:45:39,27 min 55.032 sec,2919 obs/sec,3.233333,1,8245.0,0.142408,0.020280,0.110545,0.600168
2,,2020-12-23 13:45:46,28 min 1.597 sec,3624 obs/sec,12.943529,4,33006.0,0.104535,0.010928,0.080842,0.784558
3,,2020-12-23 13:45:51,28 min 7.201 sec,4007 obs/sec,22.678039,7,57829.0,0.097969,0.009598,0.075471,0.810772
4,,2020-12-23 13:45:56,28 min 12.288 sec,4292 obs/sec,32.380784,10,82571.0,0.096646,0.009340,0.075071,0.815848
5,,2020-12-23 13:46:03,28 min 18.433 sec,4606 obs/sec,45.314118,14,115551.0,0.098875,0.009776,0.076765,0.807256
6,,2020-12-23 13:46:08,28 min 24.042 sec,4882 obs/sec,58.244706,18,148524.0,0.090599,0.008208,0.069619,0.838172
7,,2020-12-23 13:46:14,28 min 29.403 sec,5116 obs/sec,71.207059,22,181578.0,0.090302,0.008154,0.069710,0.839231
8,,2020-12-23 13:46:19,28 min 34.589 sec,5312 obs/sec,84.152941,26,214590.0,0.105434,0.011116,0.082695,0.780837
9,,2020-12-23 13:46:25,28 min 40.765 sec,5526 obs/sec,100.275294,31,255702.0,0.090187,0.008134,0.069992,0.839639
10,,2020-12-23 13:46:30,28 min 46.299 sec,5612 obs/sec,113.212549,35,288692.0,0.084437,0.007130,0.064736,0.859435
11,,2020-12-23 13:46:36,28 min 51.711 sec,5697 obs/sec,126.183922,39,321769.0,0.094398,0.008911,0.074301,0.824315
12,,2020-12-23 13:46:42,28 min 57.993 sec,5716 obs/sec,139.075686,43,354643.0,0.082500,0.006806,0.062321,0.865812
13,,2020-12-23 13:46:50,29 min 5.557 sec,5836 obs/sec,158.520000,49,404226.0,0.101721,0.010347,0.080325,0.795998
14,,2020-12-23 13:46:56,29 min 11.611 sec,5945 obs/sec,174.715686,54,445525.0,0.091092,0.008298,0.070872,0.836404
15,,2020-12-23 13:47:02,29 min 17.664 sec,6037 obs/sec,190.857255,59,486686.0,0.084253,0.007099,0.065004,0.860048
16,,2020-12-23 13:47:03,29 min 19.049 sec,6063 obs/sec,194.127843,60,495026.0,0.099863,0.009973,0.078565,0.803384

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.131165
1        f2             0.637619           0.637619    0.083633
2        f4             0.589834           0.589834    0.077365
3        f3             0.481249           0.481249    0.063123
4       f12             0.394811           0.394811    0.051785
5       f10             0.389506           0.389506    0.051089
6        f8             0.378280           0.378280    0.049617
7        f6             0.348589           0.348589    0.045723
8       f15             0.329514           0.329514    0.043221
9       f13             0.306080           0.306080    0.040147
10       f9             0.305232           0.305232    0.040036
11      f18             0.301962           0.301962    0.039607
12       f5             0.297882           0.297882    0.039072
13      f17             0.293638           0.293638    0.038515
14      f16             0.285793           0.285793    0.037486
15      f19             0.275833           0.275833    0.036180
16      f14             0.267679           0.267679    0.035110
17      f11             0.261115           0.261115    0.034249
18       f7             0.240698           0.240698    0.031571
19      f20             0.238684           0.238684    0.031307

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_18


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,70.0,70.0,56286.0,7.0,7.0,7.0,38.0,85.0,59.4

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.002796988672348969
RMSE: 0.0528865641949727
MAE: 0.03930626413839705
RMSLE: 0.02975009489215282
Mean Residual Deviance: 0.002796988672348969

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.008565752435562443
RMSE: 0.09255135026331297
MAE: 0.07075825450227256
RMSLE: 0.05327637685687936
Mean Residual Deviance: 0.008565752435562443

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07075825,0.0015950237,0.073111095,0.0697754,0.07021934,0.06911009,0.07157535
1,mean_residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
2,mse,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
3,r2,0.83073425,0.007195892,0.82004786,0.8361518,0.8382571,0.828117,0.83109754
4,residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
5,rmse,0.09253432,0.0019849439,0.09514227,0.090731815,0.091737635,0.09412287,0.09093701
6,rmsle,0.05326346,0.0013115642,0.054599006,0.051951602,0.05274927,0.05473171,0.052285712

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:16,2.644 sec,0.0,0.225214,0.185965,0.050721
1,,2020-12-23 12:54:16,2.682 sec,5.0,0.152731,0.126670,0.023327
2,,2020-12-23 12:54:16,2.703 sec,10.0,0.114317,0.094761,0.013068
3,,2020-12-23 12:54:16,2.723 sec,15.0,0.093848,0.076676,0.008807
4,,2020-12-23 12:54:16,2.746 sec,20.0,0.083360,0.066580,0.006949
5,,2020-12-23 12:54:16,2.779 sec,25.0,0.077449,0.060510,0.005998
6,,2020-12-23 12:54:16,2.804 sec,30.0,0.073213,0.056345,0.005360
7,,2020-12-23 12:54:16,2.827 sec,35.0,0.069713,0.053233,0.004860
8,,2020-12-23 12:54:16,2.850 sec,40.0,0.066686,0.050517,0.004447
9,,2020-12-23 12:54:16,2.876 sec,45.0,0.064059,0.048304,0.004104
10,,2020-12-23 12:54:16,2.909 sec,50.0,0.061136,0.045976,0.003738
11,,2020-12-23 12:54:16,2.934 sec,55.0,0.058957,0.044253,0.003476
12,,2020-12-23 12:54:16,2.961 sec,60.0,0.056785,0.042487,0.003225
13,,2020-12-23 12:54:16,2.983 sec,65.0,0.054885,0.040978,0.003012
14,,2020-12-23 12:54:16,3.006 sec,70.0,0.052887,0.039306,0.002797

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           417.634766           1.000000    0.691143
1       f10            30.944672           0.074095    0.051210
2        f3            29.945110           0.071702    0.049556
3       f15            11.459804           0.027440    0.018965
4        f5            10.429785           0.024973    0.017260
5       f20            10.251256           0.024546    0.016965
6        f2             9.859209           0.023607    0.016316
7       f19             8.878176           0.021258    0.014692
8       f12             8.301757           0.019878    0.013739
9       f18             8.120420           0.019444    0.013438
10      f13             7.664119           0.018351    0.012683
11       f4             7.198557           0.017236    0.011913
12       f8             7.032873           0.016840    0.011639
13       f6             6.048911           0.014484    0.010010
14       f7             5.914305           0.014161    0.009788
15       f9             5.534474           0.013252    0.009159
16      f16             5.280519           0.012644    0.008739
17      f17             4.892844           0.011716    0.008097
18      f14             4.451653           0.010659    0.007367
19      f11             4.423503           0.010592    0.007320

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_19


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 261.501 weights/biases, 3,0 MB, 481.090 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,10.0,,,,,,,,,
1,,2,500,RectifierDropout,40.0,0.0,0.0,0.03817,0.028977,0.0,-0.013168,0.330038,-0.19164,0.185584
2,,3,500,RectifierDropout,40.0,0.0,0.0,0.23029,0.195647,0.0,-0.050904,0.12373,0.491002,0.390195
3,,4,1,Linear,,0.0,0.0,0.004966,0.004063,0.0,0.007173,0.041931,-0.449505,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.00729760535706338
RMSE: 0.08542602271593464
MAE: 0.06745764204101454
RMSLE: 0.04904390537064369
Mean Residual Deviance: 0.00729760535706338

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.011205257468311535
RMSE: 0.10585488873127936
MAE: 0.07584706143863312
RMSLE: NaN
Mean Residual Deviance: 0.011205257468311535

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07584706,0.0043794643,0.07674681,0.0745725,0.08297606,0.07189869,0.07304125
1,mean_residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
2,mse,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
3,r2,0.7796035,0.081327595,0.7971968,0.8180189,0.6354796,0.82662797,0.82069415
4,residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
5,rmse,0.10451367,0.018780014,0.10100256,0.09562069,0.13771963,0.09452969,0.09369576
6,rmsle,0.05666129,0.0035071012,0.06182133,0.05573497,NaN,0.055020355,0.054068506

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:37:40,0.000 sec,None,0.000000,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:37:44,19 min 59.490 sec,2816 obs/sec,3.761961,1,9593.0,0.127662,0.016297,0.095618,0.678685
2,,2020-12-23 13:37:50,20 min 5.659 sec,3128 obs/sec,11.313725,3,28850.0,0.101872,0.010378,0.078483,0.795392
3,,2020-12-23 13:37:55,20 min 10.809 sec,3433 obs/sec,18.859216,5,48091.0,0.096810,0.009372,0.075154,0.815222
4,,2020-12-23 13:38:00,20 min 15.899 sec,3604 obs/sec,26.410588,7,67347.0,0.100598,0.010120,0.079679,0.800480
5,,2020-12-23 13:38:06,20 min 22.459 sec,3871 obs/sec,37.749412,10,96261.0,0.090665,0.008220,0.071071,0.837937
6,,2020-12-23 13:38:13,20 min 29.228 sec,4013 obs/sec,49.066667,13,125120.0,0.096235,0.009261,0.075875,0.817410
7,,2020-12-23 13:38:19,20 min 34.979 sec,4210 obs/sec,60.378824,16,153966.0,0.088622,0.007854,0.069724,0.845155
8,,2020-12-23 13:38:24,20 min 40.424 sec,4399 obs/sec,71.689412,19,182808.0,0.089274,0.007970,0.069652,0.842869
9,,2020-12-23 13:38:30,20 min 45.689 sec,4562 obs/sec,83.000000,22,211650.0,0.086114,0.007416,0.066870,0.853797
10,,2020-12-23 13:38:35,20 min 50.916 sec,4693 obs/sec,94.312549,25,240497.0,0.089938,0.008089,0.070322,0.840523
11,,2020-12-23 13:38:40,20 min 56.026 sec,4809 obs/sec,105.636471,28,269373.0,0.090976,0.008277,0.070919,0.836822
12,,2020-12-23 13:38:46,21 min 2.099 sec,4990 obs/sec,120.728235,32,307857.0,0.083847,0.007030,0.065468,0.861393
13,,2020-12-23 13:38:52,21 min 8.019 sec,5150 obs/sec,135.852941,36,346425.0,0.083117,0.006908,0.064599,0.863797
14,,2020-12-23 13:38:58,21 min 14.161 sec,5269 obs/sec,150.974118,40,384984.0,0.088831,0.007891,0.069896,0.844424
15,,2020-12-23 13:39:05,21 min 20.911 sec,5338 obs/sec,166.048627,44,423424.0,0.101316,0.010265,0.079926,0.797620
16,,2020-12-23 13:39:11,21 min 27.051 sec,5327 obs/sec,177.370196,47,452294.0,0.080107,0.006417,0.061539,0.873483
17,,2020-12-23 13:39:16,21 min 32.118 sec,5369 obs/sec,188.662745,50,481090.0,0.085426,0.007298,0.067458,0.856123

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.156319
1        f4             0.493175           0.493175    0.077093
2        f2             0.459908           0.459908    0.071892
3        f3             0.398930           0.398930    0.062360
4       f12             0.321844           0.321844    0.050310
5       f10             0.311592           0.311592    0.048708
6       f15             0.302689           0.302689    0.047316
7        f8             0.293541           0.293541    0.045886
8        f6             0.287389           0.287389    0.044924
9        f9             0.256456           0.256456    0.040089
10      f13             0.251343           0.251343    0.039290
11      f16             0.240312           0.240312    0.037565
12       f5             0.239611           0.239611    0.037456
13      f17             0.237875           0.237875    0.037184
14      f18             0.231972           0.231972    0.036262
15      f11             0.223080           0.223080    0.034872
16       f7             0.222850           0.222850    0.034836
17      f19             0.212779           0.212779    0.033261
18      f14             0.208843           0.208843    0.032646
19      f20             0.202992           0.202992    0.031731

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_20


Model Summary:

     number_of_trees
0               66.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.0025619836264292946
RMSE: 0.050616041196732235
MAE: 0.037218359029468365
RMSLE: 0.02969996879826354
Mean Residual Deviance: 0.0025619836264292946

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.00960723226988264
RMSE: 0.09801648978555925
MAE: 0.07469173306197513
RMSLE: 0.0567924452238901
Mean Residual Deviance: 0.00960723226988264

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.074691735,5.725854E-4,0.07488511,0.07421965,0.07481219,0.07405527,0.075486444
1,mean_residual_deviance,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
2,mse,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
3,r2,0.81016636,0.007088534,0.79900324,0.8179848,0.81403804,0.8101439,0.8096617
4,residual_deviance,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
5,rmse,0.09800092,0.0019531453,0.10055173,0.09562964,0.09836645,0.098921575,0.09653521
6,rmsle,0.056777377,0.0014626358,0.058009323,0.05469224,0.057631172,0.057767715,0.05578643

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:40,3.144 sec,0.0,0.321817,0.275443,0.103566
1,,2020-12-23 12:54:40,3.182 sec,5.0,0.126302,0.100556,0.015952
2,,2020-12-23 12:54:40,3.218 sec,10.0,0.094670,0.074348,0.008962
3,,2020-12-23 12:54:40,3.255 sec,15.0,0.083996,0.064563,0.007055
4,,2020-12-23 12:54:40,3.300 sec,20.0,0.077379,0.058583,0.005988
5,,2020-12-23 12:54:40,3.340 sec,25.0,0.072255,0.054362,0.005221
6,,2020-12-23 12:54:40,3.382 sec,30.0,0.067800,0.050808,0.004597
7,,2020-12-23 12:54:40,3.421 sec,35.0,0.064439,0.048038,0.004152
8,,2020-12-23 12:54:40,3.469 sec,40.0,0.061331,0.045627,0.003761
9,,2020-12-23 12:54:40,3.508 sec,45.0,0.058635,0.043507,0.003438
10,,2020-12-23 12:54:40,3.563 sec,50.0,0.056371,0.041778,0.003178
11,,2020-12-23 12:54:40,3.604 sec,55.0,0.054163,0.040042,0.002934
12,,2020-12-23 12:54:40,3.658 sec,60.0,0.052323,0.038622,0.002738
13,,2020-12-23 12:54:40,3.701 sec,65.0,0.050900,0.037458,0.002591
14,,2020-12-23 12:54:40,3.719 sec,66.0,0.050616,0.037218,0.002562

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           102.506783           1.000000    0.599223
1       f10            19.639147           0.191589    0.114804
2        f5            10.862881           0.105972    0.063501
3        f3             5.370502           0.052392    0.031394
4        f2             4.630992           0.045177    0.027071
5       f11             3.341065           0.032594    0.019531
6        f4             3.227701           0.031488    0.018868
7       f20             2.737843           0.026709    0.016005
8       f18             2.179754           0.021264    0.012742
9       f19             1.921421           0.018744    0.011232
10      f12             1.849532           0.018043    0.010812
11      f15             1.829120           0.017844    0.010692
12      f13             1.791575           0.017478    0.010473
13       f6             1.544740           0.015070    0.009030
14      f16             1.534647           0.014971    0.008971
15       f8             1.505961           0.014691    0.008803
16       f9             1.348663           0.013157    0.007884
17       f7             1.189082           0.011600    0.006951
18      f14             1.028377           0.010032    0.006012
19      f17             1.026396           0.010013    0.006000

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_21


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 261.501 weights/biases, 3,0 MB, 495.026 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,15.0,,,,,,,,,
1,,2,500,RectifierDropout,50.0,0.0,0.0,0.026827,0.025393,0.0,-0.009272,0.243334,-0.136184,0.159472
2,,3,500,RectifierDropout,50.0,0.0,0.0,0.149113,0.187165,0.0,-0.038966,0.083189,0.339939,0.256063
3,,4,1,Linear,,0.0,0.0,0.00539,0.00577,0.0,0.02981,0.06136,-0.760539,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.009972619466394538
RMSE: 0.09986300349175634
MAE: 0.07856480604502232
RMSLE: 0.056257833557788614
Mean Residual Deviance: 0.009972619466394538

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.009885179205877049
RMSE: 0.09942423852299322
MAE: 0.07551967978711813
RMSLE: 0.06587140651189652
Mean Residual Deviance: 0.009885179205877049

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07551968,0.006375736,0.07344144,0.071399465,0.086805485,0.072270736,0.073681265
1,mean_residual_deviance,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
2,mse,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
3,r2,0.8051752,0.03584341,0.8090461,0.83599246,0.7436621,0.8146722,0.82250315
4,residual_deviance,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
5,rmse,0.09904585,0.009688791,0.098007485,0.09077592,0.11548919,0.097734764,0.0932219
6,rmsle,0.06443256,0.015308772,0.06754833,0.054155853,0.089891285,0.057095427,0.053471938

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:45:36,0.000 sec,None,0.000000,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:45:39,27 min 55.032 sec,2919 obs/sec,3.233333,1,8245.0,0.142408,0.020280,0.110545,0.600168
2,,2020-12-23 13:45:46,28 min 1.597 sec,3624 obs/sec,12.943529,4,33006.0,0.104535,0.010928,0.080842,0.784558
3,,2020-12-23 13:45:51,28 min 7.201 sec,4007 obs/sec,22.678039,7,57829.0,0.097969,0.009598,0.075471,0.810772
4,,2020-12-23 13:45:56,28 min 12.288 sec,4292 obs/sec,32.380784,10,82571.0,0.096646,0.009340,0.075071,0.815848
5,,2020-12-23 13:46:03,28 min 18.433 sec,4606 obs/sec,45.314118,14,115551.0,0.098875,0.009776,0.076765,0.807256
6,,2020-12-23 13:46:08,28 min 24.042 sec,4882 obs/sec,58.244706,18,148524.0,0.090599,0.008208,0.069619,0.838172
7,,2020-12-23 13:46:14,28 min 29.403 sec,5116 obs/sec,71.207059,22,181578.0,0.090302,0.008154,0.069710,0.839231
8,,2020-12-23 13:46:19,28 min 34.589 sec,5312 obs/sec,84.152941,26,214590.0,0.105434,0.011116,0.082695,0.780837
9,,2020-12-23 13:46:25,28 min 40.765 sec,5526 obs/sec,100.275294,31,255702.0,0.090187,0.008134,0.069992,0.839639
10,,2020-12-23 13:46:30,28 min 46.299 sec,5612 obs/sec,113.212549,35,288692.0,0.084437,0.007130,0.064736,0.859435
11,,2020-12-23 13:46:36,28 min 51.711 sec,5697 obs/sec,126.183922,39,321769.0,0.094398,0.008911,0.074301,0.824315
12,,2020-12-23 13:46:42,28 min 57.993 sec,5716 obs/sec,139.075686,43,354643.0,0.082500,0.006806,0.062321,0.865812
13,,2020-12-23 13:46:50,29 min 5.557 sec,5836 obs/sec,158.520000,49,404226.0,0.101721,0.010347,0.080325,0.795998
14,,2020-12-23 13:46:56,29 min 11.611 sec,5945 obs/sec,174.715686,54,445525.0,0.091092,0.008298,0.070872,0.836404
15,,2020-12-23 13:47:02,29 min 17.664 sec,6037 obs/sec,190.857255,59,486686.0,0.084253,0.007099,0.065004,0.860048
16,,2020-12-23 13:47:03,29 min 19.049 sec,6063 obs/sec,194.127843,60,495026.0,0.099863,0.009973,0.078565,0.803384

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.131165
1        f2             0.637619           0.637619    0.083633
2        f4             0.589834           0.589834    0.077365
3        f3             0.481249           0.481249    0.063123
4       f12             0.394811           0.394811    0.051785
5       f10             0.389506           0.389506    0.051089
6        f8             0.378280           0.378280    0.049617
7        f6             0.348589           0.348589    0.045723
8       f15             0.329514           0.329514    0.043221
9       f13             0.306080           0.306080    0.040147
10       f9             0.305232           0.305232    0.040036
11      f18             0.301962           0.301962    0.039607
12       f5             0.297882           0.297882    0.039072
13      f17             0.293638           0.293638    0.038515
14      f16             0.285793           0.285793    0.037486
15      f19             0.275833           0.275833    0.036180
16      f14             0.267679           0.267679    0.035110
17      f11             0.261115           0.261115    0.034249
18       f7             0.240698           0.240698    0.031571
19      f20             0.238684           0.238684    0.031307

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_18


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,70.0,70.0,56286.0,7.0,7.0,7.0,38.0,85.0,59.4

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.002796988672348969
RMSE: 0.0528865641949727
MAE: 0.03930626413839705
RMSLE: 0.02975009489215282
Mean Residual Deviance: 0.002796988672348969

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.008565752435562443
RMSE: 0.09255135026331297
MAE: 0.07075825450227256
RMSLE: 0.05327637685687936
Mean Residual Deviance: 0.008565752435562443

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07075825,0.0015950237,0.073111095,0.0697754,0.07021934,0.06911009,0.07157535
1,mean_residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
2,mse,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
3,r2,0.83073425,0.007195892,0.82004786,0.8361518,0.8382571,0.828117,0.83109754
4,residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
5,rmse,0.09253432,0.0019849439,0.09514227,0.090731815,0.091737635,0.09412287,0.09093701
6,rmsle,0.05326346,0.0013115642,0.054599006,0.051951602,0.05274927,0.05473171,0.052285712

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:16,2.644 sec,0.0,0.225214,0.185965,0.050721
1,,2020-12-23 12:54:16,2.682 sec,5.0,0.152731,0.126670,0.023327
2,,2020-12-23 12:54:16,2.703 sec,10.0,0.114317,0.094761,0.013068
3,,2020-12-23 12:54:16,2.723 sec,15.0,0.093848,0.076676,0.008807
4,,2020-12-23 12:54:16,2.746 sec,20.0,0.083360,0.066580,0.006949
5,,2020-12-23 12:54:16,2.779 sec,25.0,0.077449,0.060510,0.005998
6,,2020-12-23 12:54:16,2.804 sec,30.0,0.073213,0.056345,0.005360
7,,2020-12-23 12:54:16,2.827 sec,35.0,0.069713,0.053233,0.004860
8,,2020-12-23 12:54:16,2.850 sec,40.0,0.066686,0.050517,0.004447
9,,2020-12-23 12:54:16,2.876 sec,45.0,0.064059,0.048304,0.004104
10,,2020-12-23 12:54:16,2.909 sec,50.0,0.061136,0.045976,0.003738
11,,2020-12-23 12:54:16,2.934 sec,55.0,0.058957,0.044253,0.003476
12,,2020-12-23 12:54:16,2.961 sec,60.0,0.056785,0.042487,0.003225
13,,2020-12-23 12:54:16,2.983 sec,65.0,0.054885,0.040978,0.003012
14,,2020-12-23 12:54:16,3.006 sec,70.0,0.052887,0.039306,0.002797

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           417.634766           1.000000    0.691143
1       f10            30.944672           0.074095    0.051210
2        f3            29.945110           0.071702    0.049556
3       f15            11.459804           0.027440    0.018965
4        f5            10.429785           0.024973    0.017260
5       f20            10.251256           0.024546    0.016965
6        f2             9.859209           0.023607    0.016316
7       f19             8.878176           0.021258    0.014692
8       f12             8.301757           0.019878    0.013739
9       f18             8.120420           0.019444    0.013438
10      f13             7.664119           0.018351    0.012683
11       f4             7.198557           0.017236    0.011913
12       f8             7.032873           0.016840    0.011639
13       f6             6.048911           0.014484    0.010010
14       f7             5.914305           0.014161    0.009788
15       f9             5.534474           0.013252    0.009159
16      f16             5.280519           0.012644    0.008739
17      f17             4.892844           0.011716    0.008097
18      f14             4.451653           0.010659    0.007367
19      f11             4.423503           0.010592    0.007320

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_19


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 261.501 weights/biases, 3,0 MB, 481.090 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,10.0,,,,,,,,,
1,,2,500,RectifierDropout,40.0,0.0,0.0,0.03817,0.028977,0.0,-0.013168,0.330038,-0.19164,0.185584
2,,3,500,RectifierDropout,40.0,0.0,0.0,0.23029,0.195647,0.0,-0.050904,0.12373,0.491002,0.390195
3,,4,1,Linear,,0.0,0.0,0.004966,0.004063,0.0,0.007173,0.041931,-0.449505,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.00729760535706338
RMSE: 0.08542602271593464
MAE: 0.06745764204101454
RMSLE: 0.04904390537064369
Mean Residual Deviance: 0.00729760535706338

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.011205257468311535
RMSE: 0.10585488873127936
MAE: 0.07584706143863312
RMSLE: NaN
Mean Residual Deviance: 0.011205257468311535

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07584706,0.0043794643,0.07674681,0.0745725,0.08297606,0.07189869,0.07304125
1,mean_residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
2,mse,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
3,r2,0.7796035,0.081327595,0.7971968,0.8180189,0.6354796,0.82662797,0.82069415
4,residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
5,rmse,0.10451367,0.018780014,0.10100256,0.09562069,0.13771963,0.09452969,0.09369576
6,rmsle,0.05666129,0.0035071012,0.06182133,0.05573497,NaN,0.055020355,0.054068506

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:37:40,0.000 sec,None,0.000000,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:37:44,19 min 59.490 sec,2816 obs/sec,3.761961,1,9593.0,0.127662,0.016297,0.095618,0.678685
2,,2020-12-23 13:37:50,20 min 5.659 sec,3128 obs/sec,11.313725,3,28850.0,0.101872,0.010378,0.078483,0.795392
3,,2020-12-23 13:37:55,20 min 10.809 sec,3433 obs/sec,18.859216,5,48091.0,0.096810,0.009372,0.075154,0.815222
4,,2020-12-23 13:38:00,20 min 15.899 sec,3604 obs/sec,26.410588,7,67347.0,0.100598,0.010120,0.079679,0.800480
5,,2020-12-23 13:38:06,20 min 22.459 sec,3871 obs/sec,37.749412,10,96261.0,0.090665,0.008220,0.071071,0.837937
6,,2020-12-23 13:38:13,20 min 29.228 sec,4013 obs/sec,49.066667,13,125120.0,0.096235,0.009261,0.075875,0.817410
7,,2020-12-23 13:38:19,20 min 34.979 sec,4210 obs/sec,60.378824,16,153966.0,0.088622,0.007854,0.069724,0.845155
8,,2020-12-23 13:38:24,20 min 40.424 sec,4399 obs/sec,71.689412,19,182808.0,0.089274,0.007970,0.069652,0.842869
9,,2020-12-23 13:38:30,20 min 45.689 sec,4562 obs/sec,83.000000,22,211650.0,0.086114,0.007416,0.066870,0.853797
10,,2020-12-23 13:38:35,20 min 50.916 sec,4693 obs/sec,94.312549,25,240497.0,0.089938,0.008089,0.070322,0.840523
11,,2020-12-23 13:38:40,20 min 56.026 sec,4809 obs/sec,105.636471,28,269373.0,0.090976,0.008277,0.070919,0.836822
12,,2020-12-23 13:38:46,21 min 2.099 sec,4990 obs/sec,120.728235,32,307857.0,0.083847,0.007030,0.065468,0.861393
13,,2020-12-23 13:38:52,21 min 8.019 sec,5150 obs/sec,135.852941,36,346425.0,0.083117,0.006908,0.064599,0.863797
14,,2020-12-23 13:38:58,21 min 14.161 sec,5269 obs/sec,150.974118,40,384984.0,0.088831,0.007891,0.069896,0.844424
15,,2020-12-23 13:39:05,21 min 20.911 sec,5338 obs/sec,166.048627,44,423424.0,0.101316,0.010265,0.079926,0.797620
16,,2020-12-23 13:39:11,21 min 27.051 sec,5327 obs/sec,177.370196,47,452294.0,0.080107,0.006417,0.061539,0.873483
17,,2020-12-23 13:39:16,21 min 32.118 sec,5369 obs/sec,188.662745,50,481090.0,0.085426,0.007298,0.067458,0.856123

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.156319
1        f4             0.493175           0.493175    0.077093
2        f2             0.459908           0.459908    0.071892
3        f3             0.398930           0.398930    0.062360
4       f12             0.321844           0.321844    0.050310
5       f10             0.311592           0.311592    0.048708
6       f15             0.302689           0.302689    0.047316
7        f8             0.293541           0.293541    0.045886
8        f6             0.287389           0.287389    0.044924
9        f9             0.256456           0.256456    0.040089
10      f13             0.251343           0.251343    0.039290
11      f16             0.240312           0.240312    0.037565
12       f5             0.239611           0.239611    0.037456
13      f17             0.237875           0.237875    0.037184
14      f18             0.231972           0.231972    0.036262
15      f11             0.223080           0.223080    0.034872
16       f7             0.222850           0.222850    0.034836
17      f19             0.212779           0.212779    0.033261
18      f14             0.208843           0.208843    0.032646
19      f20             0.202992           0.202992    0.031731

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_20


Model Summary:

     number_of_trees
0               66.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.0025619836264292946
RMSE: 0.050616041196732235
MAE: 0.037218359029468365
RMSLE: 0.02969996879826354
Mean Residual Deviance: 0.0025619836264292946

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.00960723226988264
RMSE: 0.09801648978555925
MAE: 0.07469173306197513
RMSLE: 0.0567924452238901
Mean Residual Deviance: 0.00960723226988264

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.074691735,5.725854E-4,0.07488511,0.07421965,0.07481219,0.07405527,0.075486444
1,mean_residual_deviance,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
2,mse,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
3,r2,0.81016636,0.007088534,0.79900324,0.8179848,0.81403804,0.8101439,0.8096617
4,residual_deviance,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
5,rmse,0.09800092,0.0019531453,0.10055173,0.09562964,0.09836645,0.098921575,0.09653521
6,rmsle,0.056777377,0.0014626358,0.058009323,0.05469224,0.057631172,0.057767715,0.05578643

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:40,3.144 sec,0.0,0.321817,0.275443,0.103566
1,,2020-12-23 12:54:40,3.182 sec,5.0,0.126302,0.100556,0.015952
2,,2020-12-23 12:54:40,3.218 sec,10.0,0.094670,0.074348,0.008962
3,,2020-12-23 12:54:40,3.255 sec,15.0,0.083996,0.064563,0.007055
4,,2020-12-23 12:54:40,3.300 sec,20.0,0.077379,0.058583,0.005988
5,,2020-12-23 12:54:40,3.340 sec,25.0,0.072255,0.054362,0.005221
6,,2020-12-23 12:54:40,3.382 sec,30.0,0.067800,0.050808,0.004597
7,,2020-12-23 12:54:40,3.421 sec,35.0,0.064439,0.048038,0.004152
8,,2020-12-23 12:54:40,3.469 sec,40.0,0.061331,0.045627,0.003761
9,,2020-12-23 12:54:40,3.508 sec,45.0,0.058635,0.043507,0.003438
10,,2020-12-23 12:54:40,3.563 sec,50.0,0.056371,0.041778,0.003178
11,,2020-12-23 12:54:40,3.604 sec,55.0,0.054163,0.040042,0.002934
12,,2020-12-23 12:54:40,3.658 sec,60.0,0.052323,0.038622,0.002738
13,,2020-12-23 12:54:40,3.701 sec,65.0,0.050900,0.037458,0.002591
14,,2020-12-23 12:54:40,3.719 sec,66.0,0.050616,0.037218,0.002562

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           102.506783           1.000000    0.599223
1       f10            19.639147           0.191589    0.114804
2        f5            10.862881           0.105972    0.063501
3        f3             5.370502           0.052392    0.031394
4        f2             4.630992           0.045177    0.027071
5       f11             3.341065           0.032594    0.019531
6        f4             3.227701           0.031488    0.018868
7       f20             2.737843           0.026709    0.016005
8       f18             2.179754           0.021264    0.012742
9       f19             1.921421           0.018744    0.011232
10      f12             1.849532           0.018043    0.010812
11      f15             1.829120           0.017844    0.010692
12      f13             1.791575           0.017478    0.010473
13       f6             1.544740           0.015070    0.009030
14      f16             1.534647           0.014971    0.008971
15       f8             1.505961           0.014691    0.008803
16       f9             1.348663           0.013157    0.007884
17       f7             1.189082           0.011600    0.006951
18      f14             1.028377           0.010032    0.006012
19      f17             1.026396           0.010013    0.006000

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_21


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 261.501 weights/biases, 3,0 MB, 495.026 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,15.0,,,,,,,,,
1,,2,500,RectifierDropout,50.0,0.0,0.0,0.026827,0.025393,0.0,-0.009272,0.243334,-0.136184,0.159472
2,,3,500,RectifierDropout,50.0,0.0,0.0,0.149113,0.187165,0.0,-0.038966,0.083189,0.339939,0.256063
3,,4,1,Linear,,0.0,0.0,0.00539,0.00577,0.0,0.02981,0.06136,-0.760539,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.009972619466394538
RMSE: 0.09986300349175634
MAE: 0.07856480604502232
RMSLE: 0.056257833557788614
Mean Residual Deviance: 0.009972619466394538

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.009885179205877049
RMSE: 0.09942423852299322
MAE: 0.07551967978711813
RMSLE: 0.06587140651189652
Mean Residual Deviance: 0.009885179205877049

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07551968,0.006375736,0.07344144,0.071399465,0.086805485,0.072270736,0.073681265
1,mean_residual_deviance,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
2,mse,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
3,r2,0.8051752,0.03584341,0.8090461,0.83599246,0.7436621,0.8146722,0.82250315
4,residual_deviance,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
5,rmse,0.09904585,0.009688791,0.098007485,0.09077592,0.11548919,0.097734764,0.0932219
6,rmsle,0.06443256,0.015308772,0.06754833,0.054155853,0.089891285,0.057095427,0.053471938

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:45:36,0.000 sec,None,0.000000,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:45:39,27 min 55.032 sec,2919 obs/sec,3.233333,1,8245.0,0.142408,0.020280,0.110545,0.600168
2,,2020-12-23 13:45:46,28 min 1.597 sec,3624 obs/sec,12.943529,4,33006.0,0.104535,0.010928,0.080842,0.784558
3,,2020-12-23 13:45:51,28 min 7.201 sec,4007 obs/sec,22.678039,7,57829.0,0.097969,0.009598,0.075471,0.810772
4,,2020-12-23 13:45:56,28 min 12.288 sec,4292 obs/sec,32.380784,10,82571.0,0.096646,0.009340,0.075071,0.815848
5,,2020-12-23 13:46:03,28 min 18.433 sec,4606 obs/sec,45.314118,14,115551.0,0.098875,0.009776,0.076765,0.807256
6,,2020-12-23 13:46:08,28 min 24.042 sec,4882 obs/sec,58.244706,18,148524.0,0.090599,0.008208,0.069619,0.838172
7,,2020-12-23 13:46:14,28 min 29.403 sec,5116 obs/sec,71.207059,22,181578.0,0.090302,0.008154,0.069710,0.839231
8,,2020-12-23 13:46:19,28 min 34.589 sec,5312 obs/sec,84.152941,26,214590.0,0.105434,0.011116,0.082695,0.780837
9,,2020-12-23 13:46:25,28 min 40.765 sec,5526 obs/sec,100.275294,31,255702.0,0.090187,0.008134,0.069992,0.839639
10,,2020-12-23 13:46:30,28 min 46.299 sec,5612 obs/sec,113.212549,35,288692.0,0.084437,0.007130,0.064736,0.859435
11,,2020-12-23 13:46:36,28 min 51.711 sec,5697 obs/sec,126.183922,39,321769.0,0.094398,0.008911,0.074301,0.824315
12,,2020-12-23 13:46:42,28 min 57.993 sec,5716 obs/sec,139.075686,43,354643.0,0.082500,0.006806,0.062321,0.865812
13,,2020-12-23 13:46:50,29 min 5.557 sec,5836 obs/sec,158.520000,49,404226.0,0.101721,0.010347,0.080325,0.795998
14,,2020-12-23 13:46:56,29 min 11.611 sec,5945 obs/sec,174.715686,54,445525.0,0.091092,0.008298,0.070872,0.836404
15,,2020-12-23 13:47:02,29 min 17.664 sec,6037 obs/sec,190.857255,59,486686.0,0.084253,0.007099,0.065004,0.860048
16,,2020-12-23 13:47:03,29 min 19.049 sec,6063 obs/sec,194.127843,60,495026.0,0.099863,0.009973,0.078565,0.803384

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.131165
1        f2             0.637619           0.637619    0.083633
2        f4             0.589834           0.589834    0.077365
3        f3             0.481249           0.481249    0.063123
4       f12             0.394811           0.394811    0.051785
5       f10             0.389506           0.389506    0.051089
6        f8             0.378280           0.378280    0.049617
7        f6             0.348589           0.348589    0.045723
8       f15             0.329514           0.329514    0.043221
9       f13             0.306080           0.306080    0.040147
10       f9             0.305232           0.305232    0.040036
11      f18             0.301962           0.301962    0.039607
12       f5             0.297882           0.297882    0.039072
13      f17             0.293638           0.293638    0.038515
14      f16             0.285793           0.285793    0.037486
15      f19             0.275833           0.275833    0.036180
16      f14             0.267679           0.267679    0.035110
17      f11             0.261115           0.261115    0.034249
18       f7             0.240698           0.240698    0.031571
19      f20             0.238684           0.238684    0.031307

generic Model Build progress: |███████████████████████████████████████████| 100%
Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_22


Model Summary:

     number_of_trees
0               43.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.002260333920867384
RMSE: 0.047542969205418624
MAE: 0.035049596801400185
RMSLE: 0.028076606198473145
Mean Residual Deviance: 0.002260333920867384

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.009986792238562525
RMSE: 0.09993393937278028
MAE: 0.07677360511147509
RMSLE: 0.05770586533382064
Mean Residual Deviance: 0.009986792238562525

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.076773606,7.063424E-4,0.07746537,0.075637944,0.07660845,0.076992534,0.07716373
1,mean_residual_deviance,0.009986793,2.471236E-4,0.0103765195,0.009879778,0.010000139,0.009974662,0.009702863
2,mse,0.009986793,2.471236E-4,0.0103765195,0.009879778,0.010000139,0.009974662,0.009702863
3,r2,0.80263644,0.0055270367,0.7937178,0.803361,0.8078076,0.8064734,0.8018224
4,residual_deviance,0.009986793,2.471236E-4,0.0103765195,0.009879778,0.010000139,0.009974662,0.009702863
5,rmse,0.099927865,0.0012321956,0.1018652,0.09939707,0.100000694,0.09987323,0.09850311
6,rmsle,0.05770098,8.3948066E-4,0.05862482,0.05716455,0.0581384,0.058045592,0.05653154

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:59,22.822 sec,0.0,0.321817,0.275443,0.103566
1,,2020-12-23 12:54:59,22.856 sec,5.0,0.110461,0.087462,0.012202
2,,2020-12-23 12:54:59,22.885 sec,10.0,0.082611,0.063498,0.006825
3,,2020-12-23 12:54:59,22.914 sec,15.0,0.071601,0.054183,0.005127
4,,2020-12-23 12:54:59,22.957 sec,20.0,0.064077,0.048107,0.004106
5,,2020-12-23 12:54:59,23.003 sec,25.0,0.059070,0.044043,0.003489
6,,2020-12-23 12:54:59,23.044 sec,30.0,0.054623,0.040475,0.002984
7,,2020-12-23 12:54:59,23.080 sec,35.0,0.050772,0.037537,0.002578
8,,2020-12-23 12:55:00,23.110 sec,40.0,0.048583,0.035902,0.002360
9,,2020-12-23 12:55:00,23.135 sec,43.0,0.047543,0.035050,0.002260

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1            63.723656           1.000000    0.451197
1       f10            18.385826           0.288524    0.130181
2        f3            15.180560           0.238225    0.107486
3        f2             8.255027           0.129544    0.058450
4        f6             5.159658           0.080969    0.036533
5        f8             4.830294           0.075801    0.034201
6        f4             3.801014           0.059648    0.026913
7       f12             3.482932           0.054657    0.024661
8       f18             1.998178           0.031357    0.014148
9       f15             1.832631           0.028759    0.012976
10      f19             1.802032           0.028279    0.012759
11       f9             1.725510           0.027078    0.012218
12      f17             1.669308           0.026196    0.011820
13      f20             1.665487           0.026136    0.011793
14      f16             1.629153           0.025566    0.011535
15       f7             1.409099           0.022113    0.009977
16      f13             1.376493           0.021601    0.009746
17      f11             1.118854           0.017558    0.007922
18      f14             1.109735           0.017415    0.007858
19       f5             1.076862           0.016899    0.007625

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_18


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,70.0,70.0,56286.0,7.0,7.0,7.0,38.0,85.0,59.4

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.002796988672348969
RMSE: 0.0528865641949727
MAE: 0.03930626413839705
RMSLE: 0.02975009489215282
Mean Residual Deviance: 0.002796988672348969

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.008565752435562443
RMSE: 0.09255135026331297
MAE: 0.07075825450227256
RMSLE: 0.05327637685687936
Mean Residual Deviance: 0.008565752435562443

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07075825,0.0015950237,0.073111095,0.0697754,0.07021934,0.06911009,0.07157535
1,mean_residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
2,mse,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
3,r2,0.83073425,0.007195892,0.82004786,0.8361518,0.8382571,0.828117,0.83109754
4,residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
5,rmse,0.09253432,0.0019849439,0.09514227,0.090731815,0.091737635,0.09412287,0.09093701
6,rmsle,0.05326346,0.0013115642,0.054599006,0.051951602,0.05274927,0.05473171,0.052285712

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:16,2.644 sec,0.0,0.225214,0.185965,0.050721
1,,2020-12-23 12:54:16,2.682 sec,5.0,0.152731,0.126670,0.023327
2,,2020-12-23 12:54:16,2.703 sec,10.0,0.114317,0.094761,0.013068
3,,2020-12-23 12:54:16,2.723 sec,15.0,0.093848,0.076676,0.008807
4,,2020-12-23 12:54:16,2.746 sec,20.0,0.083360,0.066580,0.006949
5,,2020-12-23 12:54:16,2.779 sec,25.0,0.077449,0.060510,0.005998
6,,2020-12-23 12:54:16,2.804 sec,30.0,0.073213,0.056345,0.005360
7,,2020-12-23 12:54:16,2.827 sec,35.0,0.069713,0.053233,0.004860
8,,2020-12-23 12:54:16,2.850 sec,40.0,0.066686,0.050517,0.004447
9,,2020-12-23 12:54:16,2.876 sec,45.0,0.064059,0.048304,0.004104
10,,2020-12-23 12:54:16,2.909 sec,50.0,0.061136,0.045976,0.003738
11,,2020-12-23 12:54:16,2.934 sec,55.0,0.058957,0.044253,0.003476
12,,2020-12-23 12:54:16,2.961 sec,60.0,0.056785,0.042487,0.003225
13,,2020-12-23 12:54:16,2.983 sec,65.0,0.054885,0.040978,0.003012
14,,2020-12-23 12:54:16,3.006 sec,70.0,0.052887,0.039306,0.002797

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           417.634766           1.000000    0.691143
1       f10            30.944672           0.074095    0.051210
2        f3            29.945110           0.071702    0.049556
3       f15            11.459804           0.027440    0.018965
4        f5            10.429785           0.024973    0.017260
5       f20            10.251256           0.024546    0.016965
6        f2             9.859209           0.023607    0.016316
7       f19             8.878176           0.021258    0.014692
8       f12             8.301757           0.019878    0.013739
9       f18             8.120420           0.019444    0.013438
10      f13             7.664119           0.018351    0.012683
11       f4             7.198557           0.017236    0.011913
12       f8             7.032873           0.016840    0.011639
13       f6             6.048911           0.014484    0.010010
14       f7             5.914305           0.014161    0.009788
15       f9             5.534474           0.013252    0.009159
16      f16             5.280519           0.012644    0.008739
17      f17             4.892844           0.011716    0.008097
18      f14             4.451653           0.010659    0.007367
19      f11             4.423503           0.010592    0.007320

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_19


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 261.501 weights/biases, 3,0 MB, 481.090 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,10.0,,,,,,,,,
1,,2,500,RectifierDropout,40.0,0.0,0.0,0.03817,0.028977,0.0,-0.013168,0.330038,-0.19164,0.185584
2,,3,500,RectifierDropout,40.0,0.0,0.0,0.23029,0.195647,0.0,-0.050904,0.12373,0.491002,0.390195
3,,4,1,Linear,,0.0,0.0,0.004966,0.004063,0.0,0.007173,0.041931,-0.449505,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.00729760535706338
RMSE: 0.08542602271593464
MAE: 0.06745764204101454
RMSLE: 0.04904390537064369
Mean Residual Deviance: 0.00729760535706338

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.011205257468311535
RMSE: 0.10585488873127936
MAE: 0.07584706143863312
RMSLE: NaN
Mean Residual Deviance: 0.011205257468311535

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07584706,0.0043794643,0.07674681,0.0745725,0.08297606,0.07189869,0.07304125
1,mean_residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
2,mse,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
3,r2,0.7796035,0.081327595,0.7971968,0.8180189,0.6354796,0.82662797,0.82069415
4,residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
5,rmse,0.10451367,0.018780014,0.10100256,0.09562069,0.13771963,0.09452969,0.09369576
6,rmsle,0.05666129,0.0035071012,0.06182133,0.05573497,NaN,0.055020355,0.054068506

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:37:40,0.000 sec,None,0.000000,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:37:44,19 min 59.490 sec,2816 obs/sec,3.761961,1,9593.0,0.127662,0.016297,0.095618,0.678685
2,,2020-12-23 13:37:50,20 min 5.659 sec,3128 obs/sec,11.313725,3,28850.0,0.101872,0.010378,0.078483,0.795392
3,,2020-12-23 13:37:55,20 min 10.809 sec,3433 obs/sec,18.859216,5,48091.0,0.096810,0.009372,0.075154,0.815222
4,,2020-12-23 13:38:00,20 min 15.899 sec,3604 obs/sec,26.410588,7,67347.0,0.100598,0.010120,0.079679,0.800480
5,,2020-12-23 13:38:06,20 min 22.459 sec,3871 obs/sec,37.749412,10,96261.0,0.090665,0.008220,0.071071,0.837937
6,,2020-12-23 13:38:13,20 min 29.228 sec,4013 obs/sec,49.066667,13,125120.0,0.096235,0.009261,0.075875,0.817410
7,,2020-12-23 13:38:19,20 min 34.979 sec,4210 obs/sec,60.378824,16,153966.0,0.088622,0.007854,0.069724,0.845155
8,,2020-12-23 13:38:24,20 min 40.424 sec,4399 obs/sec,71.689412,19,182808.0,0.089274,0.007970,0.069652,0.842869
9,,2020-12-23 13:38:30,20 min 45.689 sec,4562 obs/sec,83.000000,22,211650.0,0.086114,0.007416,0.066870,0.853797
10,,2020-12-23 13:38:35,20 min 50.916 sec,4693 obs/sec,94.312549,25,240497.0,0.089938,0.008089,0.070322,0.840523
11,,2020-12-23 13:38:40,20 min 56.026 sec,4809 obs/sec,105.636471,28,269373.0,0.090976,0.008277,0.070919,0.836822
12,,2020-12-23 13:38:46,21 min 2.099 sec,4990 obs/sec,120.728235,32,307857.0,0.083847,0.007030,0.065468,0.861393
13,,2020-12-23 13:38:52,21 min 8.019 sec,5150 obs/sec,135.852941,36,346425.0,0.083117,0.006908,0.064599,0.863797
14,,2020-12-23 13:38:58,21 min 14.161 sec,5269 obs/sec,150.974118,40,384984.0,0.088831,0.007891,0.069896,0.844424
15,,2020-12-23 13:39:05,21 min 20.911 sec,5338 obs/sec,166.048627,44,423424.0,0.101316,0.010265,0.079926,0.797620
16,,2020-12-23 13:39:11,21 min 27.051 sec,5327 obs/sec,177.370196,47,452294.0,0.080107,0.006417,0.061539,0.873483
17,,2020-12-23 13:39:16,21 min 32.118 sec,5369 obs/sec,188.662745,50,481090.0,0.085426,0.007298,0.067458,0.856123

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.156319
1        f4             0.493175           0.493175    0.077093
2        f2             0.459908           0.459908    0.071892
3        f3             0.398930           0.398930    0.062360
4       f12             0.321844           0.321844    0.050310
5       f10             0.311592           0.311592    0.048708
6       f15             0.302689           0.302689    0.047316
7        f8             0.293541           0.293541    0.045886
8        f6             0.287389           0.287389    0.044924
9        f9             0.256456           0.256456    0.040089
10      f13             0.251343           0.251343    0.039290
11      f16             0.240312           0.240312    0.037565
12       f5             0.239611           0.239611    0.037456
13      f17             0.237875           0.237875    0.037184
14      f18             0.231972           0.231972    0.036262
15      f11             0.223080           0.223080    0.034872
16       f7             0.222850           0.222850    0.034836
17      f19             0.212779           0.212779    0.033261
18      f14             0.208843           0.208843    0.032646
19      f20             0.202992           0.202992    0.031731

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_20


Model Summary:

     number_of_trees
0               66.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.0025619836264292946
RMSE: 0.050616041196732235
MAE: 0.037218359029468365
RMSLE: 0.02969996879826354
Mean Residual Deviance: 0.0025619836264292946

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.00960723226988264
RMSE: 0.09801648978555925
MAE: 0.07469173306197513
RMSLE: 0.0567924452238901
Mean Residual Deviance: 0.00960723226988264

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.074691735,5.725854E-4,0.07488511,0.07421965,0.07481219,0.07405527,0.075486444
1,mean_residual_deviance,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
2,mse,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
3,r2,0.81016636,0.007088534,0.79900324,0.8179848,0.81403804,0.8101439,0.8096617
4,residual_deviance,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
5,rmse,0.09800092,0.0019531453,0.10055173,0.09562964,0.09836645,0.098921575,0.09653521
6,rmsle,0.056777377,0.0014626358,0.058009323,0.05469224,0.057631172,0.057767715,0.05578643

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:40,3.144 sec,0.0,0.321817,0.275443,0.103566
1,,2020-12-23 12:54:40,3.182 sec,5.0,0.126302,0.100556,0.015952
2,,2020-12-23 12:54:40,3.218 sec,10.0,0.094670,0.074348,0.008962
3,,2020-12-23 12:54:40,3.255 sec,15.0,0.083996,0.064563,0.007055
4,,2020-12-23 12:54:40,3.300 sec,20.0,0.077379,0.058583,0.005988
5,,2020-12-23 12:54:40,3.340 sec,25.0,0.072255,0.054362,0.005221
6,,2020-12-23 12:54:40,3.382 sec,30.0,0.067800,0.050808,0.004597
7,,2020-12-23 12:54:40,3.421 sec,35.0,0.064439,0.048038,0.004152
8,,2020-12-23 12:54:40,3.469 sec,40.0,0.061331,0.045627,0.003761
9,,2020-12-23 12:54:40,3.508 sec,45.0,0.058635,0.043507,0.003438
10,,2020-12-23 12:54:40,3.563 sec,50.0,0.056371,0.041778,0.003178
11,,2020-12-23 12:54:40,3.604 sec,55.0,0.054163,0.040042,0.002934
12,,2020-12-23 12:54:40,3.658 sec,60.0,0.052323,0.038622,0.002738
13,,2020-12-23 12:54:40,3.701 sec,65.0,0.050900,0.037458,0.002591
14,,2020-12-23 12:54:40,3.719 sec,66.0,0.050616,0.037218,0.002562

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           102.506783           1.000000    0.599223
1       f10            19.639147           0.191589    0.114804
2        f5            10.862881           0.105972    0.063501
3        f3             5.370502           0.052392    0.031394
4        f2             4.630992           0.045177    0.027071
5       f11             3.341065           0.032594    0.019531
6        f4             3.227701           0.031488    0.018868
7       f20             2.737843           0.026709    0.016005
8       f18             2.179754           0.021264    0.012742
9       f19             1.921421           0.018744    0.011232
10      f12             1.849532           0.018043    0.010812
11      f15             1.829120           0.017844    0.010692
12      f13             1.791575           0.017478    0.010473
13       f6             1.544740           0.015070    0.009030
14      f16             1.534647           0.014971    0.008971
15       f8             1.505961           0.014691    0.008803
16       f9             1.348663           0.013157    0.007884
17       f7             1.189082           0.011600    0.006951
18      f14             1.028377           0.010032    0.006012
19      f17             1.026396           0.010013    0.006000

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_21


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 261.501 weights/biases, 3,0 MB, 495.026 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,15.0,,,,,,,,,
1,,2,500,RectifierDropout,50.0,0.0,0.0,0.026827,0.025393,0.0,-0.009272,0.243334,-0.136184,0.159472
2,,3,500,RectifierDropout,50.0,0.0,0.0,0.149113,0.187165,0.0,-0.038966,0.083189,0.339939,0.256063
3,,4,1,Linear,,0.0,0.0,0.00539,0.00577,0.0,0.02981,0.06136,-0.760539,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.009972619466394538
RMSE: 0.09986300349175634
MAE: 0.07856480604502232
RMSLE: 0.056257833557788614
Mean Residual Deviance: 0.009972619466394538

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.009885179205877049
RMSE: 0.09942423852299322
MAE: 0.07551967978711813
RMSLE: 0.06587140651189652
Mean Residual Deviance: 0.009885179205877049

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07551968,0.006375736,0.07344144,0.071399465,0.086805485,0.072270736,0.073681265
1,mean_residual_deviance,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
2,mse,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
3,r2,0.8051752,0.03584341,0.8090461,0.83599246,0.7436621,0.8146722,0.82250315
4,residual_deviance,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
5,rmse,0.09904585,0.009688791,0.098007485,0.09077592,0.11548919,0.097734764,0.0932219
6,rmsle,0.06443256,0.015308772,0.06754833,0.054155853,0.089891285,0.057095427,0.053471938

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:45:36,0.000 sec,None,0.000000,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:45:39,27 min 55.032 sec,2919 obs/sec,3.233333,1,8245.0,0.142408,0.020280,0.110545,0.600168
2,,2020-12-23 13:45:46,28 min 1.597 sec,3624 obs/sec,12.943529,4,33006.0,0.104535,0.010928,0.080842,0.784558
3,,2020-12-23 13:45:51,28 min 7.201 sec,4007 obs/sec,22.678039,7,57829.0,0.097969,0.009598,0.075471,0.810772
4,,2020-12-23 13:45:56,28 min 12.288 sec,4292 obs/sec,32.380784,10,82571.0,0.096646,0.009340,0.075071,0.815848
5,,2020-12-23 13:46:03,28 min 18.433 sec,4606 obs/sec,45.314118,14,115551.0,0.098875,0.009776,0.076765,0.807256
6,,2020-12-23 13:46:08,28 min 24.042 sec,4882 obs/sec,58.244706,18,148524.0,0.090599,0.008208,0.069619,0.838172
7,,2020-12-23 13:46:14,28 min 29.403 sec,5116 obs/sec,71.207059,22,181578.0,0.090302,0.008154,0.069710,0.839231
8,,2020-12-23 13:46:19,28 min 34.589 sec,5312 obs/sec,84.152941,26,214590.0,0.105434,0.011116,0.082695,0.780837
9,,2020-12-23 13:46:25,28 min 40.765 sec,5526 obs/sec,100.275294,31,255702.0,0.090187,0.008134,0.069992,0.839639
10,,2020-12-23 13:46:30,28 min 46.299 sec,5612 obs/sec,113.212549,35,288692.0,0.084437,0.007130,0.064736,0.859435
11,,2020-12-23 13:46:36,28 min 51.711 sec,5697 obs/sec,126.183922,39,321769.0,0.094398,0.008911,0.074301,0.824315
12,,2020-12-23 13:46:42,28 min 57.993 sec,5716 obs/sec,139.075686,43,354643.0,0.082500,0.006806,0.062321,0.865812
13,,2020-12-23 13:46:50,29 min 5.557 sec,5836 obs/sec,158.520000,49,404226.0,0.101721,0.010347,0.080325,0.795998
14,,2020-12-23 13:46:56,29 min 11.611 sec,5945 obs/sec,174.715686,54,445525.0,0.091092,0.008298,0.070872,0.836404
15,,2020-12-23 13:47:02,29 min 17.664 sec,6037 obs/sec,190.857255,59,486686.0,0.084253,0.007099,0.065004,0.860048
16,,2020-12-23 13:47:03,29 min 19.049 sec,6063 obs/sec,194.127843,60,495026.0,0.099863,0.009973,0.078565,0.803384

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.131165
1        f2             0.637619           0.637619    0.083633
2        f4             0.589834           0.589834    0.077365
3        f3             0.481249           0.481249    0.063123
4       f12             0.394811           0.394811    0.051785
5       f10             0.389506           0.389506    0.051089
6        f8             0.378280           0.378280    0.049617
7        f6             0.348589           0.348589    0.045723
8       f15             0.329514           0.329514    0.043221
9       f13             0.306080           0.306080    0.040147
10       f9             0.305232           0.305232    0.040036
11      f18             0.301962           0.301962    0.039607
12       f5             0.297882           0.297882    0.039072
13      f17             0.293638           0.293638    0.038515
14      f16             0.285793           0.285793    0.037486
15      f19             0.275833           0.275833    0.036180
16      f14             0.267679           0.267679    0.035110
17      f11             0.261115           0.261115    0.034249
18       f7             0.240698           0.240698    0.031571
19      f20             0.238684           0.238684    0.031307

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_22


Model Summary:

     number_of_trees
0               43.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.002260333920867384
RMSE: 0.047542969205418624
MAE: 0.035049596801400185
RMSLE: 0.028076606198473145
Mean Residual Deviance: 0.002260333920867384

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.009986792238562525
RMSE: 0.09993393937278028
MAE: 0.07677360511147509
RMSLE: 0.05770586533382064
Mean Residual Deviance: 0.009986792238562525

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.076773606,7.063424E-4,0.07746537,0.075637944,0.07660845,0.076992534,0.07716373
1,mean_residual_deviance,0.009986793,2.471236E-4,0.0103765195,0.009879778,0.010000139,0.009974662,0.009702863
2,mse,0.009986793,2.471236E-4,0.0103765195,0.009879778,0.010000139,0.009974662,0.009702863
3,r2,0.80263644,0.0055270367,0.7937178,0.803361,0.8078076,0.8064734,0.8018224
4,residual_deviance,0.009986793,2.471236E-4,0.0103765195,0.009879778,0.010000139,0.009974662,0.009702863
5,rmse,0.099927865,0.0012321956,0.1018652,0.09939707,0.100000694,0.09987323,0.09850311
6,rmsle,0.05770098,8.3948066E-4,0.05862482,0.05716455,0.0581384,0.058045592,0.05653154

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:59,22.822 sec,0.0,0.321817,0.275443,0.103566
1,,2020-12-23 12:54:59,22.856 sec,5.0,0.110461,0.087462,0.012202
2,,2020-12-23 12:54:59,22.885 sec,10.0,0.082611,0.063498,0.006825
3,,2020-12-23 12:54:59,22.914 sec,15.0,0.071601,0.054183,0.005127
4,,2020-12-23 12:54:59,22.957 sec,20.0,0.064077,0.048107,0.004106
5,,2020-12-23 12:54:59,23.003 sec,25.0,0.059070,0.044043,0.003489
6,,2020-12-23 12:54:59,23.044 sec,30.0,0.054623,0.040475,0.002984
7,,2020-12-23 12:54:59,23.080 sec,35.0,0.050772,0.037537,0.002578
8,,2020-12-23 12:55:00,23.110 sec,40.0,0.048583,0.035902,0.002360
9,,2020-12-23 12:55:00,23.135 sec,43.0,0.047543,0.035050,0.002260

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1            63.723656           1.000000    0.451197
1       f10            18.385826           0.288524    0.130181
2        f3            15.180560           0.238225    0.107486
3        f2             8.255027           0.129544    0.058450
4        f6             5.159658           0.080969    0.036533
5        f8             4.830294           0.075801    0.034201
6        f4             3.801014           0.059648    0.026913
7       f12             3.482932           0.054657    0.024661
8       f18             1.998178           0.031357    0.014148
9       f15             1.832631           0.028759    0.012976
10      f19             1.802032           0.028279    0.012759
11       f9             1.725510           0.027078    0.012218
12      f17             1.669308           0.026196    0.011820
13      f20             1.665487           0.026136    0.011793
14      f16             1.629153           0.025566    0.011535
15       f7             1.409099           0.022113    0.009977
16      f13             1.376493           0.021601    0.009746
17      f11             1.118854           0.017558    0.007922
18      f14             1.109735           0.017415    0.007858
19       f5             1.076862           0.016899    0.007625

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_18


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,70.0,70.0,56286.0,7.0,7.0,7.0,38.0,85.0,59.4

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.002796988672348969
RMSE: 0.0528865641949727
MAE: 0.03930626413839705
RMSLE: 0.02975009489215282
Mean Residual Deviance: 0.002796988672348969

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.008565752435562443
RMSE: 0.09255135026331297
MAE: 0.07075825450227256
RMSLE: 0.05327637685687936
Mean Residual Deviance: 0.008565752435562443

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07075825,0.0015950237,0.073111095,0.0697754,0.07021934,0.06911009,0.07157535
1,mean_residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
2,mse,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
3,r2,0.83073425,0.007195892,0.82004786,0.8361518,0.8382571,0.828117,0.83109754
4,residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
5,rmse,0.09253432,0.0019849439,0.09514227,0.090731815,0.091737635,0.09412287,0.09093701
6,rmsle,0.05326346,0.0013115642,0.054599006,0.051951602,0.05274927,0.05473171,0.052285712

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:16,2.644 sec,0.0,0.225214,0.185965,0.050721
1,,2020-12-23 12:54:16,2.682 sec,5.0,0.152731,0.126670,0.023327
2,,2020-12-23 12:54:16,2.703 sec,10.0,0.114317,0.094761,0.013068
3,,2020-12-23 12:54:16,2.723 sec,15.0,0.093848,0.076676,0.008807
4,,2020-12-23 12:54:16,2.746 sec,20.0,0.083360,0.066580,0.006949
5,,2020-12-23 12:54:16,2.779 sec,25.0,0.077449,0.060510,0.005998
6,,2020-12-23 12:54:16,2.804 sec,30.0,0.073213,0.056345,0.005360
7,,2020-12-23 12:54:16,2.827 sec,35.0,0.069713,0.053233,0.004860
8,,2020-12-23 12:54:16,2.850 sec,40.0,0.066686,0.050517,0.004447
9,,2020-12-23 12:54:16,2.876 sec,45.0,0.064059,0.048304,0.004104
10,,2020-12-23 12:54:16,2.909 sec,50.0,0.061136,0.045976,0.003738
11,,2020-12-23 12:54:16,2.934 sec,55.0,0.058957,0.044253,0.003476
12,,2020-12-23 12:54:16,2.961 sec,60.0,0.056785,0.042487,0.003225
13,,2020-12-23 12:54:16,2.983 sec,65.0,0.054885,0.040978,0.003012
14,,2020-12-23 12:54:16,3.006 sec,70.0,0.052887,0.039306,0.002797

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           417.634766           1.000000    0.691143
1       f10            30.944672           0.074095    0.051210
2        f3            29.945110           0.071702    0.049556
3       f15            11.459804           0.027440    0.018965
4        f5            10.429785           0.024973    0.017260
5       f20            10.251256           0.024546    0.016965
6        f2             9.859209           0.023607    0.016316
7       f19             8.878176           0.021258    0.014692
8       f12             8.301757           0.019878    0.013739
9       f18             8.120420           0.019444    0.013438
10      f13             7.664119           0.018351    0.012683
11       f4             7.198557           0.017236    0.011913
12       f8             7.032873           0.016840    0.011639
13       f6             6.048911           0.014484    0.010010
14       f7             5.914305           0.014161    0.009788
15       f9             5.534474           0.013252    0.009159
16      f16             5.280519           0.012644    0.008739
17      f17             4.892844           0.011716    0.008097
18      f14             4.451653           0.010659    0.007367
19      f11             4.423503           0.010592    0.007320

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_19


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 261.501 weights/biases, 3,0 MB, 481.090 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,10.0,,,,,,,,,
1,,2,500,RectifierDropout,40.0,0.0,0.0,0.03817,0.028977,0.0,-0.013168,0.330038,-0.19164,0.185584
2,,3,500,RectifierDropout,40.0,0.0,0.0,0.23029,0.195647,0.0,-0.050904,0.12373,0.491002,0.390195
3,,4,1,Linear,,0.0,0.0,0.004966,0.004063,0.0,0.007173,0.041931,-0.449505,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.00729760535706338
RMSE: 0.08542602271593464
MAE: 0.06745764204101454
RMSLE: 0.04904390537064369
Mean Residual Deviance: 0.00729760535706338

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.011205257468311535
RMSE: 0.10585488873127936
MAE: 0.07584706143863312
RMSLE: NaN
Mean Residual Deviance: 0.011205257468311535

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07584706,0.0043794643,0.07674681,0.0745725,0.08297606,0.07189869,0.07304125
1,mean_residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
2,mse,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
3,r2,0.7796035,0.081327595,0.7971968,0.8180189,0.6354796,0.82662797,0.82069415
4,residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
5,rmse,0.10451367,0.018780014,0.10100256,0.09562069,0.13771963,0.09452969,0.09369576
6,rmsle,0.05666129,0.0035071012,0.06182133,0.05573497,NaN,0.055020355,0.054068506

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:37:40,0.000 sec,None,0.000000,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:37:44,19 min 59.490 sec,2816 obs/sec,3.761961,1,9593.0,0.127662,0.016297,0.095618,0.678685
2,,2020-12-23 13:37:50,20 min 5.659 sec,3128 obs/sec,11.313725,3,28850.0,0.101872,0.010378,0.078483,0.795392
3,,2020-12-23 13:37:55,20 min 10.809 sec,3433 obs/sec,18.859216,5,48091.0,0.096810,0.009372,0.075154,0.815222
4,,2020-12-23 13:38:00,20 min 15.899 sec,3604 obs/sec,26.410588,7,67347.0,0.100598,0.010120,0.079679,0.800480
5,,2020-12-23 13:38:06,20 min 22.459 sec,3871 obs/sec,37.749412,10,96261.0,0.090665,0.008220,0.071071,0.837937
6,,2020-12-23 13:38:13,20 min 29.228 sec,4013 obs/sec,49.066667,13,125120.0,0.096235,0.009261,0.075875,0.817410
7,,2020-12-23 13:38:19,20 min 34.979 sec,4210 obs/sec,60.378824,16,153966.0,0.088622,0.007854,0.069724,0.845155
8,,2020-12-23 13:38:24,20 min 40.424 sec,4399 obs/sec,71.689412,19,182808.0,0.089274,0.007970,0.069652,0.842869
9,,2020-12-23 13:38:30,20 min 45.689 sec,4562 obs/sec,83.000000,22,211650.0,0.086114,0.007416,0.066870,0.853797
10,,2020-12-23 13:38:35,20 min 50.916 sec,4693 obs/sec,94.312549,25,240497.0,0.089938,0.008089,0.070322,0.840523
11,,2020-12-23 13:38:40,20 min 56.026 sec,4809 obs/sec,105.636471,28,269373.0,0.090976,0.008277,0.070919,0.836822
12,,2020-12-23 13:38:46,21 min 2.099 sec,4990 obs/sec,120.728235,32,307857.0,0.083847,0.007030,0.065468,0.861393
13,,2020-12-23 13:38:52,21 min 8.019 sec,5150 obs/sec,135.852941,36,346425.0,0.083117,0.006908,0.064599,0.863797
14,,2020-12-23 13:38:58,21 min 14.161 sec,5269 obs/sec,150.974118,40,384984.0,0.088831,0.007891,0.069896,0.844424
15,,2020-12-23 13:39:05,21 min 20.911 sec,5338 obs/sec,166.048627,44,423424.0,0.101316,0.010265,0.079926,0.797620
16,,2020-12-23 13:39:11,21 min 27.051 sec,5327 obs/sec,177.370196,47,452294.0,0.080107,0.006417,0.061539,0.873483
17,,2020-12-23 13:39:16,21 min 32.118 sec,5369 obs/sec,188.662745,50,481090.0,0.085426,0.007298,0.067458,0.856123

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.156319
1        f4             0.493175           0.493175    0.077093
2        f2             0.459908           0.459908    0.071892
3        f3             0.398930           0.398930    0.062360
4       f12             0.321844           0.321844    0.050310
5       f10             0.311592           0.311592    0.048708
6       f15             0.302689           0.302689    0.047316
7        f8             0.293541           0.293541    0.045886
8        f6             0.287389           0.287389    0.044924
9        f9             0.256456           0.256456    0.040089
10      f13             0.251343           0.251343    0.039290
11      f16             0.240312           0.240312    0.037565
12       f5             0.239611           0.239611    0.037456
13      f17             0.237875           0.237875    0.037184
14      f18             0.231972           0.231972    0.036262
15      f11             0.223080           0.223080    0.034872
16       f7             0.222850           0.222850    0.034836
17      f19             0.212779           0.212779    0.033261
18      f14             0.208843           0.208843    0.032646
19      f20             0.202992           0.202992    0.031731

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_20


Model Summary:

     number_of_trees
0               66.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.0025619836264292946
RMSE: 0.050616041196732235
MAE: 0.037218359029468365
RMSLE: 0.02969996879826354
Mean Residual Deviance: 0.0025619836264292946

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.00960723226988264
RMSE: 0.09801648978555925
MAE: 0.07469173306197513
RMSLE: 0.0567924452238901
Mean Residual Deviance: 0.00960723226988264

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.074691735,5.725854E-4,0.07488511,0.07421965,0.07481219,0.07405527,0.075486444
1,mean_residual_deviance,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
2,mse,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
3,r2,0.81016636,0.007088534,0.79900324,0.8179848,0.81403804,0.8101439,0.8096617
4,residual_deviance,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
5,rmse,0.09800092,0.0019531453,0.10055173,0.09562964,0.09836645,0.098921575,0.09653521
6,rmsle,0.056777377,0.0014626358,0.058009323,0.05469224,0.057631172,0.057767715,0.05578643

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:40,3.144 sec,0.0,0.321817,0.275443,0.103566
1,,2020-12-23 12:54:40,3.182 sec,5.0,0.126302,0.100556,0.015952
2,,2020-12-23 12:54:40,3.218 sec,10.0,0.094670,0.074348,0.008962
3,,2020-12-23 12:54:40,3.255 sec,15.0,0.083996,0.064563,0.007055
4,,2020-12-23 12:54:40,3.300 sec,20.0,0.077379,0.058583,0.005988
5,,2020-12-23 12:54:40,3.340 sec,25.0,0.072255,0.054362,0.005221
6,,2020-12-23 12:54:40,3.382 sec,30.0,0.067800,0.050808,0.004597
7,,2020-12-23 12:54:40,3.421 sec,35.0,0.064439,0.048038,0.004152
8,,2020-12-23 12:54:40,3.469 sec,40.0,0.061331,0.045627,0.003761
9,,2020-12-23 12:54:40,3.508 sec,45.0,0.058635,0.043507,0.003438
10,,2020-12-23 12:54:40,3.563 sec,50.0,0.056371,0.041778,0.003178
11,,2020-12-23 12:54:40,3.604 sec,55.0,0.054163,0.040042,0.002934
12,,2020-12-23 12:54:40,3.658 sec,60.0,0.052323,0.038622,0.002738
13,,2020-12-23 12:54:40,3.701 sec,65.0,0.050900,0.037458,0.002591
14,,2020-12-23 12:54:40,3.719 sec,66.0,0.050616,0.037218,0.002562

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           102.506783           1.000000    0.599223
1       f10            19.639147           0.191589    0.114804
2        f5            10.862881           0.105972    0.063501
3        f3             5.370502           0.052392    0.031394
4        f2             4.630992           0.045177    0.027071
5       f11             3.341065           0.032594    0.019531
6        f4             3.227701           0.031488    0.018868
7       f20             2.737843           0.026709    0.016005
8       f18             2.179754           0.021264    0.012742
9       f19             1.921421           0.018744    0.011232
10      f12             1.849532           0.018043    0.010812
11      f15             1.829120           0.017844    0.010692
12      f13             1.791575           0.017478    0.010473
13       f6             1.544740           0.015070    0.009030
14      f16             1.534647           0.014971    0.008971
15       f8             1.505961           0.014691    0.008803
16       f9             1.348663           0.013157    0.007884
17       f7             1.189082           0.011600    0.006951
18      f14             1.028377           0.010032    0.006012
19      f17             1.026396           0.010013    0.006000

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_21


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 261.501 weights/biases, 3,0 MB, 495.026 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,15.0,,,,,,,,,
1,,2,500,RectifierDropout,50.0,0.0,0.0,0.026827,0.025393,0.0,-0.009272,0.243334,-0.136184,0.159472
2,,3,500,RectifierDropout,50.0,0.0,0.0,0.149113,0.187165,0.0,-0.038966,0.083189,0.339939,0.256063
3,,4,1,Linear,,0.0,0.0,0.00539,0.00577,0.0,0.02981,0.06136,-0.760539,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.009972619466394538
RMSE: 0.09986300349175634
MAE: 0.07856480604502232
RMSLE: 0.056257833557788614
Mean Residual Deviance: 0.009972619466394538

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.009885179205877049
RMSE: 0.09942423852299322
MAE: 0.07551967978711813
RMSLE: 0.06587140651189652
Mean Residual Deviance: 0.009885179205877049

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07551968,0.006375736,0.07344144,0.071399465,0.086805485,0.072270736,0.073681265
1,mean_residual_deviance,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
2,mse,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
3,r2,0.8051752,0.03584341,0.8090461,0.83599246,0.7436621,0.8146722,0.82250315
4,residual_deviance,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
5,rmse,0.09904585,0.009688791,0.098007485,0.09077592,0.11548919,0.097734764,0.0932219
6,rmsle,0.06443256,0.015308772,0.06754833,0.054155853,0.089891285,0.057095427,0.053471938

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:45:36,0.000 sec,None,0.000000,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:45:39,27 min 55.032 sec,2919 obs/sec,3.233333,1,8245.0,0.142408,0.020280,0.110545,0.600168
2,,2020-12-23 13:45:46,28 min 1.597 sec,3624 obs/sec,12.943529,4,33006.0,0.104535,0.010928,0.080842,0.784558
3,,2020-12-23 13:45:51,28 min 7.201 sec,4007 obs/sec,22.678039,7,57829.0,0.097969,0.009598,0.075471,0.810772
4,,2020-12-23 13:45:56,28 min 12.288 sec,4292 obs/sec,32.380784,10,82571.0,0.096646,0.009340,0.075071,0.815848
5,,2020-12-23 13:46:03,28 min 18.433 sec,4606 obs/sec,45.314118,14,115551.0,0.098875,0.009776,0.076765,0.807256
6,,2020-12-23 13:46:08,28 min 24.042 sec,4882 obs/sec,58.244706,18,148524.0,0.090599,0.008208,0.069619,0.838172
7,,2020-12-23 13:46:14,28 min 29.403 sec,5116 obs/sec,71.207059,22,181578.0,0.090302,0.008154,0.069710,0.839231
8,,2020-12-23 13:46:19,28 min 34.589 sec,5312 obs/sec,84.152941,26,214590.0,0.105434,0.011116,0.082695,0.780837
9,,2020-12-23 13:46:25,28 min 40.765 sec,5526 obs/sec,100.275294,31,255702.0,0.090187,0.008134,0.069992,0.839639
10,,2020-12-23 13:46:30,28 min 46.299 sec,5612 obs/sec,113.212549,35,288692.0,0.084437,0.007130,0.064736,0.859435
11,,2020-12-23 13:46:36,28 min 51.711 sec,5697 obs/sec,126.183922,39,321769.0,0.094398,0.008911,0.074301,0.824315
12,,2020-12-23 13:46:42,28 min 57.993 sec,5716 obs/sec,139.075686,43,354643.0,0.082500,0.006806,0.062321,0.865812
13,,2020-12-23 13:46:50,29 min 5.557 sec,5836 obs/sec,158.520000,49,404226.0,0.101721,0.010347,0.080325,0.795998
14,,2020-12-23 13:46:56,29 min 11.611 sec,5945 obs/sec,174.715686,54,445525.0,0.091092,0.008298,0.070872,0.836404
15,,2020-12-23 13:47:02,29 min 17.664 sec,6037 obs/sec,190.857255,59,486686.0,0.084253,0.007099,0.065004,0.860048
16,,2020-12-23 13:47:03,29 min 19.049 sec,6063 obs/sec,194.127843,60,495026.0,0.099863,0.009973,0.078565,0.803384

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.131165
1        f2             0.637619           0.637619    0.083633
2        f4             0.589834           0.589834    0.077365
3        f3             0.481249           0.481249    0.063123
4       f12             0.394811           0.394811    0.051785
5       f10             0.389506           0.389506    0.051089
6        f8             0.378280           0.378280    0.049617
7        f6             0.348589           0.348589    0.045723
8       f15             0.329514           0.329514    0.043221
9       f13             0.306080           0.306080    0.040147
10       f9             0.305232           0.305232    0.040036
11      f18             0.301962           0.301962    0.039607
12       f5             0.297882           0.297882    0.039072
13      f17             0.293638           0.293638    0.038515
14      f16             0.285793           0.285793    0.037486
15      f19             0.275833           0.275833    0.036180
16      f14             0.267679           0.267679    0.035110
17      f11             0.261115           0.261115    0.034249
18       f7             0.240698           0.240698    0.031571
19      f20             0.238684           0.238684    0.031307

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_22


Model Summary:

     number_of_trees
0               43.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.002260333920867384
RMSE: 0.047542969205418624
MAE: 0.035049596801400185
RMSLE: 0.028076606198473145
Mean Residual Deviance: 0.002260333920867384

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.009986792238562525
RMSE: 0.09993393937278028
MAE: 0.07677360511147509
RMSLE: 0.05770586533382064
Mean Residual Deviance: 0.009986792238562525

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.076773606,7.063424E-4,0.07746537,0.075637944,0.07660845,0.076992534,0.07716373
1,mean_residual_deviance,0.009986793,2.471236E-4,0.0103765195,0.009879778,0.010000139,0.009974662,0.009702863
2,mse,0.009986793,2.471236E-4,0.0103765195,0.009879778,0.010000139,0.009974662,0.009702863
3,r2,0.80263644,0.0055270367,0.7937178,0.803361,0.8078076,0.8064734,0.8018224
4,residual_deviance,0.009986793,2.471236E-4,0.0103765195,0.009879778,0.010000139,0.009974662,0.009702863
5,rmse,0.099927865,0.0012321956,0.1018652,0.09939707,0.100000694,0.09987323,0.09850311
6,rmsle,0.05770098,8.3948066E-4,0.05862482,0.05716455,0.0581384,0.058045592,0.05653154

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:59,22.822 sec,0.0,0.321817,0.275443,0.103566
1,,2020-12-23 12:54:59,22.856 sec,5.0,0.110461,0.087462,0.012202
2,,2020-12-23 12:54:59,22.885 sec,10.0,0.082611,0.063498,0.006825
3,,2020-12-23 12:54:59,22.914 sec,15.0,0.071601,0.054183,0.005127
4,,2020-12-23 12:54:59,22.957 sec,20.0,0.064077,0.048107,0.004106
5,,2020-12-23 12:54:59,23.003 sec,25.0,0.059070,0.044043,0.003489
6,,2020-12-23 12:54:59,23.044 sec,30.0,0.054623,0.040475,0.002984
7,,2020-12-23 12:54:59,23.080 sec,35.0,0.050772,0.037537,0.002578
8,,2020-12-23 12:55:00,23.110 sec,40.0,0.048583,0.035902,0.002360
9,,2020-12-23 12:55:00,23.135 sec,43.0,0.047543,0.035050,0.002260

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1            63.723656           1.000000    0.451197
1       f10            18.385826           0.288524    0.130181
2        f3            15.180560           0.238225    0.107486
3        f2             8.255027           0.129544    0.058450
4        f6             5.159658           0.080969    0.036533
5        f8             4.830294           0.075801    0.034201
6        f4             3.801014           0.059648    0.026913
7       f12             3.482932           0.054657    0.024661
8       f18             1.998178           0.031357    0.014148
9       f15             1.832631           0.028759    0.012976
10      f19             1.802032           0.028279    0.012759
11       f9             1.725510           0.027078    0.012218
12      f17             1.669308           0.026196    0.011820
13      f20             1.665487           0.026136    0.011793
14      f16             1.629153           0.025566    0.011535
15       f7             1.409099           0.022113    0.009977
16      f13             1.376493           0.021601    0.009746
17      f11             1.118854           0.017558    0.007922
18      f14             1.109735           0.017415    0.007858
19       f5             1.076862           0.016899    0.007625

generic Model Build progress: |███████████████████████████████████████████| 100%
Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_23


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 11.001 weights/biases, 139,5 KB, 2.014.500 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,10.0,,,,,,,,,
1,,2,500,RectifierDropout,40.0,0.0,0.0,0.015278,0.039545,0.0,-0.034855,0.46779,-0.225568,0.247956
2,,3,1,Linear,,0.0,0.0,0.000839,0.00112,0.0,0.00287,0.137275,0.161724,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.01059203065966177
RMSE: 0.10291759159474036
MAE: 0.07008580920667913
RMSLE: NaN
Mean Residual Deviance: 0.01059203065966177

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.018538106477002252
RMSE: 0.13615471522133288
MAE: 0.08648347462326784
RMSLE: NaN
Mean Residual Deviance: 0.018538106477002252

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.08648347,0.013595644,0.07963748,0.078659646,0.0903095,0.10860648,0.07520426
1,mean_residual_deviance,0.018538106,0.010918572,0.01061485,0.014174043,0.034680642,0.024579972,0.008641028
2,mse,0.018538106,0.010918572,0.01061485,0.014174043,0.034680642,0.024579972,0.008641028
3,r2,0.63739175,0.20586833,0.7889799,0.71789145,0.33347374,0.5231038,0.82351005
4,residual_deviance,0.018538106,0.010918572,0.01061485,0.014174043,0.034680642,0.024579972,0.008641028
5,rmse,0.13160954,0.039003767,0.10302839,0.11905479,0.1862274,0.15678,0.092957124
6,rmsle,0.063862726,0.007297337,0.06902273,NaN,NaN,NaN,0.058702733

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:00:57,0.000 sec,None,0.0,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:00:58,4 min 59.344 sec,17477 obs/sec,10.0,1,25500.0,0.130693,0.017081,0.096803,0.663244
2,,2020-12-23 13:01:03,5 min 4.556 sec,19172 obs/sec,50.0,5,127500.0,0.119469,0.014273,0.084529,0.718604
3,,2020-12-23 13:01:08,5 min 9.602 sec,21841 obs/sec,100.0,10,255000.0,0.114910,0.013204,0.079086,0.739669
4,,2020-12-23 13:01:14,5 min 15.620 sec,21645 obs/sec,150.0,15,382500.0,0.101419,0.010286,0.075440,0.797208
5,,2020-12-23 13:01:19,5 min 20.803 sec,23452 obs/sec,210.0,21,535500.0,0.103660,0.010745,0.075042,0.788147
6,,2020-12-23 13:01:25,5 min 26.521 sec,25026 obs/sec,280.0,28,714000.0,0.096625,0.009336,0.072578,0.815926
7,,2020-12-23 13:01:31,5 min 32.100 sec,26182 obs/sec,350.0,35,892500.0,0.093654,0.008771,0.070713,0.827072
8,,2020-12-23 13:01:36,5 min 37.594 sec,27072 obs/sec,420.0,42,1071000.0,0.090748,0.008235,0.069063,0.837638
9,,2020-12-23 13:01:42,5 min 42.964 sec,27824 obs/sec,490.0,49,1249500.0,0.106152,0.011268,0.077234,0.777841
10,,2020-12-23 13:01:47,5 min 48.313 sec,28426 obs/sec,560.0,56,1428000.0,0.091660,0.008402,0.069275,0.834359
11,,2020-12-23 13:01:52,5 min 53.572 sec,28961 obs/sec,630.0,63,1606500.0,0.096519,0.009316,0.068617,0.816330
12,,2020-12-23 13:01:58,5 min 58.837 sec,29399 obs/sec,700.0,70,1785000.0,0.091186,0.008315,0.068045,0.836066
13,,2020-12-23 13:02:03,6 min 4.037 sec,29797 obs/sec,770.0,77,1963500.0,0.088535,0.007838,0.067604,0.845460
14,,2020-12-23 13:02:04,6 min 5.551 sec,29896 obs/sec,790.0,79,2014500.0,0.102918,0.010592,0.070086,0.791172

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.182564
1        f2             0.590345           0.590345    0.107776
2        f4             0.461556           0.461556    0.084263
3        f6             0.268595           0.268595    0.049036
4       f10             0.258141           0.258141    0.047127
5        f9             0.244056           0.244056    0.044556
6        f8             0.235102           0.235102    0.042921
7        f3             0.225633           0.225633    0.041193
8       f13             0.210254           0.210254    0.038385
9       f12             0.209692           0.209692    0.038282
10       f5             0.208619           0.208619    0.038086
11      f18             0.205397           0.205397    0.037498
12      f15             0.189973           0.189973    0.034682
13       f7             0.177541           0.177541    0.032413
14      f11             0.176335           0.176335    0.032192
15      f14             0.176137           0.176137    0.032156
16      f19             0.172673           0.172673    0.031524
17      f20             0.159926           0.159926    0.029197
18      f16             0.155611           0.155611    0.028409
19      f17             0.151946           0.151946    0.027740

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_18


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,70.0,70.0,56286.0,7.0,7.0,7.0,38.0,85.0,59.4

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.002796988672348969
RMSE: 0.0528865641949727
MAE: 0.03930626413839705
RMSLE: 0.02975009489215282
Mean Residual Deviance: 0.002796988672348969

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.008565752435562443
RMSE: 0.09255135026331297
MAE: 0.07075825450227256
RMSLE: 0.05327637685687936
Mean Residual Deviance: 0.008565752435562443

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07075825,0.0015950237,0.073111095,0.0697754,0.07021934,0.06911009,0.07157535
1,mean_residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
2,mse,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
3,r2,0.83073425,0.007195892,0.82004786,0.8361518,0.8382571,0.828117,0.83109754
4,residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
5,rmse,0.09253432,0.0019849439,0.09514227,0.090731815,0.091737635,0.09412287,0.09093701
6,rmsle,0.05326346,0.0013115642,0.054599006,0.051951602,0.05274927,0.05473171,0.052285712

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:16,2.644 sec,0.0,0.225214,0.185965,0.050721
1,,2020-12-23 12:54:16,2.682 sec,5.0,0.152731,0.126670,0.023327
2,,2020-12-23 12:54:16,2.703 sec,10.0,0.114317,0.094761,0.013068
3,,2020-12-23 12:54:16,2.723 sec,15.0,0.093848,0.076676,0.008807
4,,2020-12-23 12:54:16,2.746 sec,20.0,0.083360,0.066580,0.006949
5,,2020-12-23 12:54:16,2.779 sec,25.0,0.077449,0.060510,0.005998
6,,2020-12-23 12:54:16,2.804 sec,30.0,0.073213,0.056345,0.005360
7,,2020-12-23 12:54:16,2.827 sec,35.0,0.069713,0.053233,0.004860
8,,2020-12-23 12:54:16,2.850 sec,40.0,0.066686,0.050517,0.004447
9,,2020-12-23 12:54:16,2.876 sec,45.0,0.064059,0.048304,0.004104
10,,2020-12-23 12:54:16,2.909 sec,50.0,0.061136,0.045976,0.003738
11,,2020-12-23 12:54:16,2.934 sec,55.0,0.058957,0.044253,0.003476
12,,2020-12-23 12:54:16,2.961 sec,60.0,0.056785,0.042487,0.003225
13,,2020-12-23 12:54:16,2.983 sec,65.0,0.054885,0.040978,0.003012
14,,2020-12-23 12:54:16,3.006 sec,70.0,0.052887,0.039306,0.002797

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           417.634766           1.000000    0.691143
1       f10            30.944672           0.074095    0.051210
2        f3            29.945110           0.071702    0.049556
3       f15            11.459804           0.027440    0.018965
4        f5            10.429785           0.024973    0.017260
5       f20            10.251256           0.024546    0.016965
6        f2             9.859209           0.023607    0.016316
7       f19             8.878176           0.021258    0.014692
8       f12             8.301757           0.019878    0.013739
9       f18             8.120420           0.019444    0.013438
10      f13             7.664119           0.018351    0.012683
11       f4             7.198557           0.017236    0.011913
12       f8             7.032873           0.016840    0.011639
13       f6             6.048911           0.014484    0.010010
14       f7             5.914305           0.014161    0.009788
15       f9             5.534474           0.013252    0.009159
16      f16             5.280519           0.012644    0.008739
17      f17             4.892844           0.011716    0.008097
18      f14             4.451653           0.010659    0.007367
19      f11             4.423503           0.010592    0.007320

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_19


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 261.501 weights/biases, 3,0 MB, 481.090 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,10.0,,,,,,,,,
1,,2,500,RectifierDropout,40.0,0.0,0.0,0.03817,0.028977,0.0,-0.013168,0.330038,-0.19164,0.185584
2,,3,500,RectifierDropout,40.0,0.0,0.0,0.23029,0.195647,0.0,-0.050904,0.12373,0.491002,0.390195
3,,4,1,Linear,,0.0,0.0,0.004966,0.004063,0.0,0.007173,0.041931,-0.449505,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.00729760535706338
RMSE: 0.08542602271593464
MAE: 0.06745764204101454
RMSLE: 0.04904390537064369
Mean Residual Deviance: 0.00729760535706338

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.011205257468311535
RMSE: 0.10585488873127936
MAE: 0.07584706143863312
RMSLE: NaN
Mean Residual Deviance: 0.011205257468311535

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07584706,0.0043794643,0.07674681,0.0745725,0.08297606,0.07189869,0.07304125
1,mean_residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
2,mse,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
3,r2,0.7796035,0.081327595,0.7971968,0.8180189,0.6354796,0.82662797,0.82069415
4,residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
5,rmse,0.10451367,0.018780014,0.10100256,0.09562069,0.13771963,0.09452969,0.09369576
6,rmsle,0.05666129,0.0035071012,0.06182133,0.05573497,NaN,0.055020355,0.054068506

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:37:40,0.000 sec,None,0.000000,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:37:44,19 min 59.490 sec,2816 obs/sec,3.761961,1,9593.0,0.127662,0.016297,0.095618,0.678685
2,,2020-12-23 13:37:50,20 min 5.659 sec,3128 obs/sec,11.313725,3,28850.0,0.101872,0.010378,0.078483,0.795392
3,,2020-12-23 13:37:55,20 min 10.809 sec,3433 obs/sec,18.859216,5,48091.0,0.096810,0.009372,0.075154,0.815222
4,,2020-12-23 13:38:00,20 min 15.899 sec,3604 obs/sec,26.410588,7,67347.0,0.100598,0.010120,0.079679,0.800480
5,,2020-12-23 13:38:06,20 min 22.459 sec,3871 obs/sec,37.749412,10,96261.0,0.090665,0.008220,0.071071,0.837937
6,,2020-12-23 13:38:13,20 min 29.228 sec,4013 obs/sec,49.066667,13,125120.0,0.096235,0.009261,0.075875,0.817410
7,,2020-12-23 13:38:19,20 min 34.979 sec,4210 obs/sec,60.378824,16,153966.0,0.088622,0.007854,0.069724,0.845155
8,,2020-12-23 13:38:24,20 min 40.424 sec,4399 obs/sec,71.689412,19,182808.0,0.089274,0.007970,0.069652,0.842869
9,,2020-12-23 13:38:30,20 min 45.689 sec,4562 obs/sec,83.000000,22,211650.0,0.086114,0.007416,0.066870,0.853797
10,,2020-12-23 13:38:35,20 min 50.916 sec,4693 obs/sec,94.312549,25,240497.0,0.089938,0.008089,0.070322,0.840523
11,,2020-12-23 13:38:40,20 min 56.026 sec,4809 obs/sec,105.636471,28,269373.0,0.090976,0.008277,0.070919,0.836822
12,,2020-12-23 13:38:46,21 min 2.099 sec,4990 obs/sec,120.728235,32,307857.0,0.083847,0.007030,0.065468,0.861393
13,,2020-12-23 13:38:52,21 min 8.019 sec,5150 obs/sec,135.852941,36,346425.0,0.083117,0.006908,0.064599,0.863797
14,,2020-12-23 13:38:58,21 min 14.161 sec,5269 obs/sec,150.974118,40,384984.0,0.088831,0.007891,0.069896,0.844424
15,,2020-12-23 13:39:05,21 min 20.911 sec,5338 obs/sec,166.048627,44,423424.0,0.101316,0.010265,0.079926,0.797620
16,,2020-12-23 13:39:11,21 min 27.051 sec,5327 obs/sec,177.370196,47,452294.0,0.080107,0.006417,0.061539,0.873483
17,,2020-12-23 13:39:16,21 min 32.118 sec,5369 obs/sec,188.662745,50,481090.0,0.085426,0.007298,0.067458,0.856123

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.156319
1        f4             0.493175           0.493175    0.077093
2        f2             0.459908           0.459908    0.071892
3        f3             0.398930           0.398930    0.062360
4       f12             0.321844           0.321844    0.050310
5       f10             0.311592           0.311592    0.048708
6       f15             0.302689           0.302689    0.047316
7        f8             0.293541           0.293541    0.045886
8        f6             0.287389           0.287389    0.044924
9        f9             0.256456           0.256456    0.040089
10      f13             0.251343           0.251343    0.039290
11      f16             0.240312           0.240312    0.037565
12       f5             0.239611           0.239611    0.037456
13      f17             0.237875           0.237875    0.037184
14      f18             0.231972           0.231972    0.036262
15      f11             0.223080           0.223080    0.034872
16       f7             0.222850           0.222850    0.034836
17      f19             0.212779           0.212779    0.033261
18      f14             0.208843           0.208843    0.032646
19      f20             0.202992           0.202992    0.031731

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_20


Model Summary:

     number_of_trees
0               66.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.0025619836264292946
RMSE: 0.050616041196732235
MAE: 0.037218359029468365
RMSLE: 0.02969996879826354
Mean Residual Deviance: 0.0025619836264292946

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.00960723226988264
RMSE: 0.09801648978555925
MAE: 0.07469173306197513
RMSLE: 0.0567924452238901
Mean Residual Deviance: 0.00960723226988264

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.074691735,5.725854E-4,0.07488511,0.07421965,0.07481219,0.07405527,0.075486444
1,mean_residual_deviance,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
2,mse,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
3,r2,0.81016636,0.007088534,0.79900324,0.8179848,0.81403804,0.8101439,0.8096617
4,residual_deviance,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
5,rmse,0.09800092,0.0019531453,0.10055173,0.09562964,0.09836645,0.098921575,0.09653521
6,rmsle,0.056777377,0.0014626358,0.058009323,0.05469224,0.057631172,0.057767715,0.05578643

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:40,3.144 sec,0.0,0.321817,0.275443,0.103566
1,,2020-12-23 12:54:40,3.182 sec,5.0,0.126302,0.100556,0.015952
2,,2020-12-23 12:54:40,3.218 sec,10.0,0.094670,0.074348,0.008962
3,,2020-12-23 12:54:40,3.255 sec,15.0,0.083996,0.064563,0.007055
4,,2020-12-23 12:54:40,3.300 sec,20.0,0.077379,0.058583,0.005988
5,,2020-12-23 12:54:40,3.340 sec,25.0,0.072255,0.054362,0.005221
6,,2020-12-23 12:54:40,3.382 sec,30.0,0.067800,0.050808,0.004597
7,,2020-12-23 12:54:40,3.421 sec,35.0,0.064439,0.048038,0.004152
8,,2020-12-23 12:54:40,3.469 sec,40.0,0.061331,0.045627,0.003761
9,,2020-12-23 12:54:40,3.508 sec,45.0,0.058635,0.043507,0.003438
10,,2020-12-23 12:54:40,3.563 sec,50.0,0.056371,0.041778,0.003178
11,,2020-12-23 12:54:40,3.604 sec,55.0,0.054163,0.040042,0.002934
12,,2020-12-23 12:54:40,3.658 sec,60.0,0.052323,0.038622,0.002738
13,,2020-12-23 12:54:40,3.701 sec,65.0,0.050900,0.037458,0.002591
14,,2020-12-23 12:54:40,3.719 sec,66.0,0.050616,0.037218,0.002562

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           102.506783           1.000000    0.599223
1       f10            19.639147           0.191589    0.114804
2        f5            10.862881           0.105972    0.063501
3        f3             5.370502           0.052392    0.031394
4        f2             4.630992           0.045177    0.027071
5       f11             3.341065           0.032594    0.019531
6        f4             3.227701           0.031488    0.018868
7       f20             2.737843           0.026709    0.016005
8       f18             2.179754           0.021264    0.012742
9       f19             1.921421           0.018744    0.011232
10      f12             1.849532           0.018043    0.010812
11      f15             1.829120           0.017844    0.010692
12      f13             1.791575           0.017478    0.010473
13       f6             1.544740           0.015070    0.009030
14      f16             1.534647           0.014971    0.008971
15       f8             1.505961           0.014691    0.008803
16       f9             1.348663           0.013157    0.007884
17       f7             1.189082           0.011600    0.006951
18      f14             1.028377           0.010032    0.006012
19      f17             1.026396           0.010013    0.006000

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_21


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 261.501 weights/biases, 3,0 MB, 495.026 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,15.0,,,,,,,,,
1,,2,500,RectifierDropout,50.0,0.0,0.0,0.026827,0.025393,0.0,-0.009272,0.243334,-0.136184,0.159472
2,,3,500,RectifierDropout,50.0,0.0,0.0,0.149113,0.187165,0.0,-0.038966,0.083189,0.339939,0.256063
3,,4,1,Linear,,0.0,0.0,0.00539,0.00577,0.0,0.02981,0.06136,-0.760539,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.009972619466394538
RMSE: 0.09986300349175634
MAE: 0.07856480604502232
RMSLE: 0.056257833557788614
Mean Residual Deviance: 0.009972619466394538

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.009885179205877049
RMSE: 0.09942423852299322
MAE: 0.07551967978711813
RMSLE: 0.06587140651189652
Mean Residual Deviance: 0.009885179205877049

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07551968,0.006375736,0.07344144,0.071399465,0.086805485,0.072270736,0.073681265
1,mean_residual_deviance,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
2,mse,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
3,r2,0.8051752,0.03584341,0.8090461,0.83599246,0.7436621,0.8146722,0.82250315
4,residual_deviance,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
5,rmse,0.09904585,0.009688791,0.098007485,0.09077592,0.11548919,0.097734764,0.0932219
6,rmsle,0.06443256,0.015308772,0.06754833,0.054155853,0.089891285,0.057095427,0.053471938

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:45:36,0.000 sec,None,0.000000,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:45:39,27 min 55.032 sec,2919 obs/sec,3.233333,1,8245.0,0.142408,0.020280,0.110545,0.600168
2,,2020-12-23 13:45:46,28 min 1.597 sec,3624 obs/sec,12.943529,4,33006.0,0.104535,0.010928,0.080842,0.784558
3,,2020-12-23 13:45:51,28 min 7.201 sec,4007 obs/sec,22.678039,7,57829.0,0.097969,0.009598,0.075471,0.810772
4,,2020-12-23 13:45:56,28 min 12.288 sec,4292 obs/sec,32.380784,10,82571.0,0.096646,0.009340,0.075071,0.815848
5,,2020-12-23 13:46:03,28 min 18.433 sec,4606 obs/sec,45.314118,14,115551.0,0.098875,0.009776,0.076765,0.807256
6,,2020-12-23 13:46:08,28 min 24.042 sec,4882 obs/sec,58.244706,18,148524.0,0.090599,0.008208,0.069619,0.838172
7,,2020-12-23 13:46:14,28 min 29.403 sec,5116 obs/sec,71.207059,22,181578.0,0.090302,0.008154,0.069710,0.839231
8,,2020-12-23 13:46:19,28 min 34.589 sec,5312 obs/sec,84.152941,26,214590.0,0.105434,0.011116,0.082695,0.780837
9,,2020-12-23 13:46:25,28 min 40.765 sec,5526 obs/sec,100.275294,31,255702.0,0.090187,0.008134,0.069992,0.839639
10,,2020-12-23 13:46:30,28 min 46.299 sec,5612 obs/sec,113.212549,35,288692.0,0.084437,0.007130,0.064736,0.859435
11,,2020-12-23 13:46:36,28 min 51.711 sec,5697 obs/sec,126.183922,39,321769.0,0.094398,0.008911,0.074301,0.824315
12,,2020-12-23 13:46:42,28 min 57.993 sec,5716 obs/sec,139.075686,43,354643.0,0.082500,0.006806,0.062321,0.865812
13,,2020-12-23 13:46:50,29 min 5.557 sec,5836 obs/sec,158.520000,49,404226.0,0.101721,0.010347,0.080325,0.795998
14,,2020-12-23 13:46:56,29 min 11.611 sec,5945 obs/sec,174.715686,54,445525.0,0.091092,0.008298,0.070872,0.836404
15,,2020-12-23 13:47:02,29 min 17.664 sec,6037 obs/sec,190.857255,59,486686.0,0.084253,0.007099,0.065004,0.860048
16,,2020-12-23 13:47:03,29 min 19.049 sec,6063 obs/sec,194.127843,60,495026.0,0.099863,0.009973,0.078565,0.803384

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.131165
1        f2             0.637619           0.637619    0.083633
2        f4             0.589834           0.589834    0.077365
3        f3             0.481249           0.481249    0.063123
4       f12             0.394811           0.394811    0.051785
5       f10             0.389506           0.389506    0.051089
6        f8             0.378280           0.378280    0.049617
7        f6             0.348589           0.348589    0.045723
8       f15             0.329514           0.329514    0.043221
9       f13             0.306080           0.306080    0.040147
10       f9             0.305232           0.305232    0.040036
11      f18             0.301962           0.301962    0.039607
12       f5             0.297882           0.297882    0.039072
13      f17             0.293638           0.293638    0.038515
14      f16             0.285793           0.285793    0.037486
15      f19             0.275833           0.275833    0.036180
16      f14             0.267679           0.267679    0.035110
17      f11             0.261115           0.261115    0.034249
18       f7             0.240698           0.240698    0.031571
19      f20             0.238684           0.238684    0.031307

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_22


Model Summary:

     number_of_trees
0               43.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.002260333920867384
RMSE: 0.047542969205418624
MAE: 0.035049596801400185
RMSLE: 0.028076606198473145
Mean Residual Deviance: 0.002260333920867384

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.009986792238562525
RMSE: 0.09993393937278028
MAE: 0.07677360511147509
RMSLE: 0.05770586533382064
Mean Residual Deviance: 0.009986792238562525

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.076773606,7.063424E-4,0.07746537,0.075637944,0.07660845,0.076992534,0.07716373
1,mean_residual_deviance,0.009986793,2.471236E-4,0.0103765195,0.009879778,0.010000139,0.009974662,0.009702863
2,mse,0.009986793,2.471236E-4,0.0103765195,0.009879778,0.010000139,0.009974662,0.009702863
3,r2,0.80263644,0.0055270367,0.7937178,0.803361,0.8078076,0.8064734,0.8018224
4,residual_deviance,0.009986793,2.471236E-4,0.0103765195,0.009879778,0.010000139,0.009974662,0.009702863
5,rmse,0.099927865,0.0012321956,0.1018652,0.09939707,0.100000694,0.09987323,0.09850311
6,rmsle,0.05770098,8.3948066E-4,0.05862482,0.05716455,0.0581384,0.058045592,0.05653154

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:59,22.822 sec,0.0,0.321817,0.275443,0.103566
1,,2020-12-23 12:54:59,22.856 sec,5.0,0.110461,0.087462,0.012202
2,,2020-12-23 12:54:59,22.885 sec,10.0,0.082611,0.063498,0.006825
3,,2020-12-23 12:54:59,22.914 sec,15.0,0.071601,0.054183,0.005127
4,,2020-12-23 12:54:59,22.957 sec,20.0,0.064077,0.048107,0.004106
5,,2020-12-23 12:54:59,23.003 sec,25.0,0.059070,0.044043,0.003489
6,,2020-12-23 12:54:59,23.044 sec,30.0,0.054623,0.040475,0.002984
7,,2020-12-23 12:54:59,23.080 sec,35.0,0.050772,0.037537,0.002578
8,,2020-12-23 12:55:00,23.110 sec,40.0,0.048583,0.035902,0.002360
9,,2020-12-23 12:55:00,23.135 sec,43.0,0.047543,0.035050,0.002260

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1            63.723656           1.000000    0.451197
1       f10            18.385826           0.288524    0.130181
2        f3            15.180560           0.238225    0.107486
3        f2             8.255027           0.129544    0.058450
4        f6             5.159658           0.080969    0.036533
5        f8             4.830294           0.075801    0.034201
6        f4             3.801014           0.059648    0.026913
7       f12             3.482932           0.054657    0.024661
8       f18             1.998178           0.031357    0.014148
9       f15             1.832631           0.028759    0.012976
10      f19             1.802032           0.028279    0.012759
11       f9             1.725510           0.027078    0.012218
12      f17             1.669308           0.026196    0.011820
13      f20             1.665487           0.026136    0.011793
14      f16             1.629153           0.025566    0.011535
15       f7             1.409099           0.022113    0.009977
16      f13             1.376493           0.021601    0.009746
17      f11             1.118854           0.017558    0.007922
18      f14             1.109735           0.017415    0.007858
19       f5             1.076862           0.016899    0.007625

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_23


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 11.001 weights/biases, 139,5 KB, 2.014.500 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,10.0,,,,,,,,,
1,,2,500,RectifierDropout,40.0,0.0,0.0,0.015278,0.039545,0.0,-0.034855,0.46779,-0.225568,0.247956
2,,3,1,Linear,,0.0,0.0,0.000839,0.00112,0.0,0.00287,0.137275,0.161724,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.01059203065966177
RMSE: 0.10291759159474036
MAE: 0.07008580920667913
RMSLE: NaN
Mean Residual Deviance: 0.01059203065966177

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.018538106477002252
RMSE: 0.13615471522133288
MAE: 0.08648347462326784
RMSLE: NaN
Mean Residual Deviance: 0.018538106477002252

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.08648347,0.013595644,0.07963748,0.078659646,0.0903095,0.10860648,0.07520426
1,mean_residual_deviance,0.018538106,0.010918572,0.01061485,0.014174043,0.034680642,0.024579972,0.008641028
2,mse,0.018538106,0.010918572,0.01061485,0.014174043,0.034680642,0.024579972,0.008641028
3,r2,0.63739175,0.20586833,0.7889799,0.71789145,0.33347374,0.5231038,0.82351005
4,residual_deviance,0.018538106,0.010918572,0.01061485,0.014174043,0.034680642,0.024579972,0.008641028
5,rmse,0.13160954,0.039003767,0.10302839,0.11905479,0.1862274,0.15678,0.092957124
6,rmsle,0.063862726,0.007297337,0.06902273,NaN,NaN,NaN,0.058702733

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:00:57,0.000 sec,None,0.0,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:00:58,4 min 59.344 sec,17477 obs/sec,10.0,1,25500.0,0.130693,0.017081,0.096803,0.663244
2,,2020-12-23 13:01:03,5 min 4.556 sec,19172 obs/sec,50.0,5,127500.0,0.119469,0.014273,0.084529,0.718604
3,,2020-12-23 13:01:08,5 min 9.602 sec,21841 obs/sec,100.0,10,255000.0,0.114910,0.013204,0.079086,0.739669
4,,2020-12-23 13:01:14,5 min 15.620 sec,21645 obs/sec,150.0,15,382500.0,0.101419,0.010286,0.075440,0.797208
5,,2020-12-23 13:01:19,5 min 20.803 sec,23452 obs/sec,210.0,21,535500.0,0.103660,0.010745,0.075042,0.788147
6,,2020-12-23 13:01:25,5 min 26.521 sec,25026 obs/sec,280.0,28,714000.0,0.096625,0.009336,0.072578,0.815926
7,,2020-12-23 13:01:31,5 min 32.100 sec,26182 obs/sec,350.0,35,892500.0,0.093654,0.008771,0.070713,0.827072
8,,2020-12-23 13:01:36,5 min 37.594 sec,27072 obs/sec,420.0,42,1071000.0,0.090748,0.008235,0.069063,0.837638
9,,2020-12-23 13:01:42,5 min 42.964 sec,27824 obs/sec,490.0,49,1249500.0,0.106152,0.011268,0.077234,0.777841
10,,2020-12-23 13:01:47,5 min 48.313 sec,28426 obs/sec,560.0,56,1428000.0,0.091660,0.008402,0.069275,0.834359
11,,2020-12-23 13:01:52,5 min 53.572 sec,28961 obs/sec,630.0,63,1606500.0,0.096519,0.009316,0.068617,0.816330
12,,2020-12-23 13:01:58,5 min 58.837 sec,29399 obs/sec,700.0,70,1785000.0,0.091186,0.008315,0.068045,0.836066
13,,2020-12-23 13:02:03,6 min 4.037 sec,29797 obs/sec,770.0,77,1963500.0,0.088535,0.007838,0.067604,0.845460
14,,2020-12-23 13:02:04,6 min 5.551 sec,29896 obs/sec,790.0,79,2014500.0,0.102918,0.010592,0.070086,0.791172

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.182564
1        f2             0.590345           0.590345    0.107776
2        f4             0.461556           0.461556    0.084263
3        f6             0.268595           0.268595    0.049036
4       f10             0.258141           0.258141    0.047127
5        f9             0.244056           0.244056    0.044556
6        f8             0.235102           0.235102    0.042921
7        f3             0.225633           0.225633    0.041193
8       f13             0.210254           0.210254    0.038385
9       f12             0.209692           0.209692    0.038282
10       f5             0.208619           0.208619    0.038086
11      f18             0.205397           0.205397    0.037498
12      f15             0.189973           0.189973    0.034682
13       f7             0.177541           0.177541    0.032413
14      f11             0.176335           0.176335    0.032192
15      f14             0.176137           0.176137    0.032156
16      f19             0.172673           0.172673    0.031524
17      f20             0.159926           0.159926    0.029197
18      f16             0.155611           0.155611    0.028409
19      f17             0.151946           0.151946    0.027740

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_18


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,70.0,70.0,56286.0,7.0,7.0,7.0,38.0,85.0,59.4

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.002796988672348969
RMSE: 0.0528865641949727
MAE: 0.03930626413839705
RMSLE: 0.02975009489215282
Mean Residual Deviance: 0.002796988672348969

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.008565752435562443
RMSE: 0.09255135026331297
MAE: 0.07075825450227256
RMSLE: 0.05327637685687936
Mean Residual Deviance: 0.008565752435562443

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07075825,0.0015950237,0.073111095,0.0697754,0.07021934,0.06911009,0.07157535
1,mean_residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
2,mse,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
3,r2,0.83073425,0.007195892,0.82004786,0.8361518,0.8382571,0.828117,0.83109754
4,residual_deviance,0.008565753,3.6877935E-4,0.009052051,0.008232262,0.008415794,0.008859115,0.00826954
5,rmse,0.09253432,0.0019849439,0.09514227,0.090731815,0.091737635,0.09412287,0.09093701
6,rmsle,0.05326346,0.0013115642,0.054599006,0.051951602,0.05274927,0.05473171,0.052285712

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:16,2.644 sec,0.0,0.225214,0.185965,0.050721
1,,2020-12-23 12:54:16,2.682 sec,5.0,0.152731,0.126670,0.023327
2,,2020-12-23 12:54:16,2.703 sec,10.0,0.114317,0.094761,0.013068
3,,2020-12-23 12:54:16,2.723 sec,15.0,0.093848,0.076676,0.008807
4,,2020-12-23 12:54:16,2.746 sec,20.0,0.083360,0.066580,0.006949
5,,2020-12-23 12:54:16,2.779 sec,25.0,0.077449,0.060510,0.005998
6,,2020-12-23 12:54:16,2.804 sec,30.0,0.073213,0.056345,0.005360
7,,2020-12-23 12:54:16,2.827 sec,35.0,0.069713,0.053233,0.004860
8,,2020-12-23 12:54:16,2.850 sec,40.0,0.066686,0.050517,0.004447
9,,2020-12-23 12:54:16,2.876 sec,45.0,0.064059,0.048304,0.004104
10,,2020-12-23 12:54:16,2.909 sec,50.0,0.061136,0.045976,0.003738
11,,2020-12-23 12:54:16,2.934 sec,55.0,0.058957,0.044253,0.003476
12,,2020-12-23 12:54:16,2.961 sec,60.0,0.056785,0.042487,0.003225
13,,2020-12-23 12:54:16,2.983 sec,65.0,0.054885,0.040978,0.003012
14,,2020-12-23 12:54:16,3.006 sec,70.0,0.052887,0.039306,0.002797

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           417.634766           1.000000    0.691143
1       f10            30.944672           0.074095    0.051210
2        f3            29.945110           0.071702    0.049556
3       f15            11.459804           0.027440    0.018965
4        f5            10.429785           0.024973    0.017260
5       f20            10.251256           0.024546    0.016965
6        f2             9.859209           0.023607    0.016316
7       f19             8.878176           0.021258    0.014692
8       f12             8.301757           0.019878    0.013739
9       f18             8.120420           0.019444    0.013438
10      f13             7.664119           0.018351    0.012683
11       f4             7.198557           0.017236    0.011913
12       f8             7.032873           0.016840    0.011639
13       f6             6.048911           0.014484    0.010010
14       f7             5.914305           0.014161    0.009788
15       f9             5.534474           0.013252    0.009159
16      f16             5.280519           0.012644    0.008739
17      f17             4.892844           0.011716    0.008097
18      f14             4.451653           0.010659    0.007367
19      f11             4.423503           0.010592    0.007320

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_19


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 261.501 weights/biases, 3,0 MB, 481.090 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,10.0,,,,,,,,,
1,,2,500,RectifierDropout,40.0,0.0,0.0,0.03817,0.028977,0.0,-0.013168,0.330038,-0.19164,0.185584
2,,3,500,RectifierDropout,40.0,0.0,0.0,0.23029,0.195647,0.0,-0.050904,0.12373,0.491002,0.390195
3,,4,1,Linear,,0.0,0.0,0.004966,0.004063,0.0,0.007173,0.041931,-0.449505,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.00729760535706338
RMSE: 0.08542602271593464
MAE: 0.06745764204101454
RMSLE: 0.04904390537064369
Mean Residual Deviance: 0.00729760535706338

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.011205257468311535
RMSE: 0.10585488873127936
MAE: 0.07584706143863312
RMSLE: NaN
Mean Residual Deviance: 0.011205257468311535

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07584706,0.0043794643,0.07674681,0.0745725,0.08297606,0.07189869,0.07304125
1,mean_residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
2,mse,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
3,r2,0.7796035,0.081327595,0.7971968,0.8180189,0.6354796,0.82662797,0.82069415
4,residual_deviance,0.011205258,0.0043742545,0.010201517,0.009143317,0.018966697,0.008935862,0.008778895
5,rmse,0.10451367,0.018780014,0.10100256,0.09562069,0.13771963,0.09452969,0.09369576
6,rmsle,0.05666129,0.0035071012,0.06182133,0.05573497,NaN,0.055020355,0.054068506

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:37:40,0.000 sec,None,0.000000,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:37:44,19 min 59.490 sec,2816 obs/sec,3.761961,1,9593.0,0.127662,0.016297,0.095618,0.678685
2,,2020-12-23 13:37:50,20 min 5.659 sec,3128 obs/sec,11.313725,3,28850.0,0.101872,0.010378,0.078483,0.795392
3,,2020-12-23 13:37:55,20 min 10.809 sec,3433 obs/sec,18.859216,5,48091.0,0.096810,0.009372,0.075154,0.815222
4,,2020-12-23 13:38:00,20 min 15.899 sec,3604 obs/sec,26.410588,7,67347.0,0.100598,0.010120,0.079679,0.800480
5,,2020-12-23 13:38:06,20 min 22.459 sec,3871 obs/sec,37.749412,10,96261.0,0.090665,0.008220,0.071071,0.837937
6,,2020-12-23 13:38:13,20 min 29.228 sec,4013 obs/sec,49.066667,13,125120.0,0.096235,0.009261,0.075875,0.817410
7,,2020-12-23 13:38:19,20 min 34.979 sec,4210 obs/sec,60.378824,16,153966.0,0.088622,0.007854,0.069724,0.845155
8,,2020-12-23 13:38:24,20 min 40.424 sec,4399 obs/sec,71.689412,19,182808.0,0.089274,0.007970,0.069652,0.842869
9,,2020-12-23 13:38:30,20 min 45.689 sec,4562 obs/sec,83.000000,22,211650.0,0.086114,0.007416,0.066870,0.853797
10,,2020-12-23 13:38:35,20 min 50.916 sec,4693 obs/sec,94.312549,25,240497.0,0.089938,0.008089,0.070322,0.840523
11,,2020-12-23 13:38:40,20 min 56.026 sec,4809 obs/sec,105.636471,28,269373.0,0.090976,0.008277,0.070919,0.836822
12,,2020-12-23 13:38:46,21 min 2.099 sec,4990 obs/sec,120.728235,32,307857.0,0.083847,0.007030,0.065468,0.861393
13,,2020-12-23 13:38:52,21 min 8.019 sec,5150 obs/sec,135.852941,36,346425.0,0.083117,0.006908,0.064599,0.863797
14,,2020-12-23 13:38:58,21 min 14.161 sec,5269 obs/sec,150.974118,40,384984.0,0.088831,0.007891,0.069896,0.844424
15,,2020-12-23 13:39:05,21 min 20.911 sec,5338 obs/sec,166.048627,44,423424.0,0.101316,0.010265,0.079926,0.797620
16,,2020-12-23 13:39:11,21 min 27.051 sec,5327 obs/sec,177.370196,47,452294.0,0.080107,0.006417,0.061539,0.873483
17,,2020-12-23 13:39:16,21 min 32.118 sec,5369 obs/sec,188.662745,50,481090.0,0.085426,0.007298,0.067458,0.856123

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.156319
1        f4             0.493175           0.493175    0.077093
2        f2             0.459908           0.459908    0.071892
3        f3             0.398930           0.398930    0.062360
4       f12             0.321844           0.321844    0.050310
5       f10             0.311592           0.311592    0.048708
6       f15             0.302689           0.302689    0.047316
7        f8             0.293541           0.293541    0.045886
8        f6             0.287389           0.287389    0.044924
9        f9             0.256456           0.256456    0.040089
10      f13             0.251343           0.251343    0.039290
11      f16             0.240312           0.240312    0.037565
12       f5             0.239611           0.239611    0.037456
13      f17             0.237875           0.237875    0.037184
14      f18             0.231972           0.231972    0.036262
15      f11             0.223080           0.223080    0.034872
16       f7             0.222850           0.222850    0.034836
17      f19             0.212779           0.212779    0.033261
18      f14             0.208843           0.208843    0.032646
19      f20             0.202992           0.202992    0.031731

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_20


Model Summary:

     number_of_trees
0               66.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.0025619836264292946
RMSE: 0.050616041196732235
MAE: 0.037218359029468365
RMSLE: 0.02969996879826354
Mean Residual Deviance: 0.0025619836264292946

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.00960723226988264
RMSE: 0.09801648978555925
MAE: 0.07469173306197513
RMSLE: 0.0567924452238901
Mean Residual Deviance: 0.00960723226988264

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.074691735,5.725854E-4,0.07488511,0.07421965,0.07481219,0.07405527,0.075486444
1,mean_residual_deviance,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
2,mse,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
3,r2,0.81016636,0.007088534,0.79900324,0.8179848,0.81403804,0.8101439,0.8096617
4,residual_deviance,0.009607232,3.8295155E-4,0.01011065,0.009145028,0.009675957,0.009785479,0.009319047
5,rmse,0.09800092,0.0019531453,0.10055173,0.09562964,0.09836645,0.098921575,0.09653521
6,rmsle,0.056777377,0.0014626358,0.058009323,0.05469224,0.057631172,0.057767715,0.05578643

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:40,3.144 sec,0.0,0.321817,0.275443,0.103566
1,,2020-12-23 12:54:40,3.182 sec,5.0,0.126302,0.100556,0.015952
2,,2020-12-23 12:54:40,3.218 sec,10.0,0.094670,0.074348,0.008962
3,,2020-12-23 12:54:40,3.255 sec,15.0,0.083996,0.064563,0.007055
4,,2020-12-23 12:54:40,3.300 sec,20.0,0.077379,0.058583,0.005988
5,,2020-12-23 12:54:40,3.340 sec,25.0,0.072255,0.054362,0.005221
6,,2020-12-23 12:54:40,3.382 sec,30.0,0.067800,0.050808,0.004597
7,,2020-12-23 12:54:40,3.421 sec,35.0,0.064439,0.048038,0.004152
8,,2020-12-23 12:54:40,3.469 sec,40.0,0.061331,0.045627,0.003761
9,,2020-12-23 12:54:40,3.508 sec,45.0,0.058635,0.043507,0.003438
10,,2020-12-23 12:54:40,3.563 sec,50.0,0.056371,0.041778,0.003178
11,,2020-12-23 12:54:40,3.604 sec,55.0,0.054163,0.040042,0.002934
12,,2020-12-23 12:54:40,3.658 sec,60.0,0.052323,0.038622,0.002738
13,,2020-12-23 12:54:40,3.701 sec,65.0,0.050900,0.037458,0.002591
14,,2020-12-23 12:54:40,3.719 sec,66.0,0.050616,0.037218,0.002562

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           102.506783           1.000000    0.599223
1       f10            19.639147           0.191589    0.114804
2        f5            10.862881           0.105972    0.063501
3        f3             5.370502           0.052392    0.031394
4        f2             4.630992           0.045177    0.027071
5       f11             3.341065           0.032594    0.019531
6        f4             3.227701           0.031488    0.018868
7       f20             2.737843           0.026709    0.016005
8       f18             2.179754           0.021264    0.012742
9       f19             1.921421           0.018744    0.011232
10      f12             1.849532           0.018043    0.010812
11      f15             1.829120           0.017844    0.010692
12      f13             1.791575           0.017478    0.010473
13       f6             1.544740           0.015070    0.009030
14      f16             1.534647           0.014971    0.008971
15       f8             1.505961           0.014691    0.008803
16       f9             1.348663           0.013157    0.007884
17       f7             1.189082           0.011600    0.006951
18      f14             1.028377           0.010032    0.006012
19      f17             1.026396           0.010013    0.006000

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_21


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 261.501 weights/biases, 3,0 MB, 495.026 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,15.0,,,,,,,,,
1,,2,500,RectifierDropout,50.0,0.0,0.0,0.026827,0.025393,0.0,-0.009272,0.243334,-0.136184,0.159472
2,,3,500,RectifierDropout,50.0,0.0,0.0,0.149113,0.187165,0.0,-0.038966,0.083189,0.339939,0.256063
3,,4,1,Linear,,0.0,0.0,0.00539,0.00577,0.0,0.02981,0.06136,-0.760539,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.009972619466394538
RMSE: 0.09986300349175634
MAE: 0.07856480604502232
RMSLE: 0.056257833557788614
Mean Residual Deviance: 0.009972619466394538

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.009885179205877049
RMSE: 0.09942423852299322
MAE: 0.07551967978711813
RMSLE: 0.06587140651189652
Mean Residual Deviance: 0.009885179205877049

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07551968,0.006375736,0.07344144,0.071399465,0.086805485,0.072270736,0.073681265
1,mean_residual_deviance,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
2,mse,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
3,r2,0.8051752,0.03584341,0.8090461,0.83599246,0.7436621,0.8146722,0.82250315
4,residual_deviance,0.009885179,0.0020151224,0.009605467,0.008240268,0.013337754,0.009552084,0.008690324
5,rmse,0.09904585,0.009688791,0.098007485,0.09077592,0.11548919,0.097734764,0.0932219
6,rmsle,0.06443256,0.015308772,0.06754833,0.054155853,0.089891285,0.057095427,0.053471938

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:45:36,0.000 sec,None,0.000000,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:45:39,27 min 55.032 sec,2919 obs/sec,3.233333,1,8245.0,0.142408,0.020280,0.110545,0.600168
2,,2020-12-23 13:45:46,28 min 1.597 sec,3624 obs/sec,12.943529,4,33006.0,0.104535,0.010928,0.080842,0.784558
3,,2020-12-23 13:45:51,28 min 7.201 sec,4007 obs/sec,22.678039,7,57829.0,0.097969,0.009598,0.075471,0.810772
4,,2020-12-23 13:45:56,28 min 12.288 sec,4292 obs/sec,32.380784,10,82571.0,0.096646,0.009340,0.075071,0.815848
5,,2020-12-23 13:46:03,28 min 18.433 sec,4606 obs/sec,45.314118,14,115551.0,0.098875,0.009776,0.076765,0.807256
6,,2020-12-23 13:46:08,28 min 24.042 sec,4882 obs/sec,58.244706,18,148524.0,0.090599,0.008208,0.069619,0.838172
7,,2020-12-23 13:46:14,28 min 29.403 sec,5116 obs/sec,71.207059,22,181578.0,0.090302,0.008154,0.069710,0.839231
8,,2020-12-23 13:46:19,28 min 34.589 sec,5312 obs/sec,84.152941,26,214590.0,0.105434,0.011116,0.082695,0.780837
9,,2020-12-23 13:46:25,28 min 40.765 sec,5526 obs/sec,100.275294,31,255702.0,0.090187,0.008134,0.069992,0.839639
10,,2020-12-23 13:46:30,28 min 46.299 sec,5612 obs/sec,113.212549,35,288692.0,0.084437,0.007130,0.064736,0.859435
11,,2020-12-23 13:46:36,28 min 51.711 sec,5697 obs/sec,126.183922,39,321769.0,0.094398,0.008911,0.074301,0.824315
12,,2020-12-23 13:46:42,28 min 57.993 sec,5716 obs/sec,139.075686,43,354643.0,0.082500,0.006806,0.062321,0.865812
13,,2020-12-23 13:46:50,29 min 5.557 sec,5836 obs/sec,158.520000,49,404226.0,0.101721,0.010347,0.080325,0.795998
14,,2020-12-23 13:46:56,29 min 11.611 sec,5945 obs/sec,174.715686,54,445525.0,0.091092,0.008298,0.070872,0.836404
15,,2020-12-23 13:47:02,29 min 17.664 sec,6037 obs/sec,190.857255,59,486686.0,0.084253,0.007099,0.065004,0.860048
16,,2020-12-23 13:47:03,29 min 19.049 sec,6063 obs/sec,194.127843,60,495026.0,0.099863,0.009973,0.078565,0.803384

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.131165
1        f2             0.637619           0.637619    0.083633
2        f4             0.589834           0.589834    0.077365
3        f3             0.481249           0.481249    0.063123
4       f12             0.394811           0.394811    0.051785
5       f10             0.389506           0.389506    0.051089
6        f8             0.378280           0.378280    0.049617
7        f6             0.348589           0.348589    0.045723
8       f15             0.329514           0.329514    0.043221
9       f13             0.306080           0.306080    0.040147
10       f9             0.305232           0.305232    0.040036
11      f18             0.301962           0.301962    0.039607
12       f5             0.297882           0.297882    0.039072
13      f17             0.293638           0.293638    0.038515
14      f16             0.285793           0.285793    0.037486
15      f19             0.275833           0.275833    0.036180
16      f14             0.267679           0.267679    0.035110
17      f11             0.261115           0.261115    0.034249
18       f7             0.240698           0.240698    0.031571
19      f20             0.238684           0.238684    0.031307

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_22


Model Summary:

     number_of_trees
0               43.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.002260333920867384
RMSE: 0.047542969205418624
MAE: 0.035049596801400185
RMSLE: 0.028076606198473145
Mean Residual Deviance: 0.002260333920867384

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.009986792238562525
RMSE: 0.09993393937278028
MAE: 0.07677360511147509
RMSLE: 0.05770586533382064
Mean Residual Deviance: 0.009986792238562525

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.076773606,7.063424E-4,0.07746537,0.075637944,0.07660845,0.076992534,0.07716373
1,mean_residual_deviance,0.009986793,2.471236E-4,0.0103765195,0.009879778,0.010000139,0.009974662,0.009702863
2,mse,0.009986793,2.471236E-4,0.0103765195,0.009879778,0.010000139,0.009974662,0.009702863
3,r2,0.80263644,0.0055270367,0.7937178,0.803361,0.8078076,0.8064734,0.8018224
4,residual_deviance,0.009986793,2.471236E-4,0.0103765195,0.009879778,0.010000139,0.009974662,0.009702863
5,rmse,0.099927865,0.0012321956,0.1018652,0.09939707,0.100000694,0.09987323,0.09850311
6,rmsle,0.05770098,8.3948066E-4,0.05862482,0.05716455,0.0581384,0.058045592,0.05653154

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:59,22.822 sec,0.0,0.321817,0.275443,0.103566
1,,2020-12-23 12:54:59,22.856 sec,5.0,0.110461,0.087462,0.012202
2,,2020-12-23 12:54:59,22.885 sec,10.0,0.082611,0.063498,0.006825
3,,2020-12-23 12:54:59,22.914 sec,15.0,0.071601,0.054183,0.005127
4,,2020-12-23 12:54:59,22.957 sec,20.0,0.064077,0.048107,0.004106
5,,2020-12-23 12:54:59,23.003 sec,25.0,0.059070,0.044043,0.003489
6,,2020-12-23 12:54:59,23.044 sec,30.0,0.054623,0.040475,0.002984
7,,2020-12-23 12:54:59,23.080 sec,35.0,0.050772,0.037537,0.002578
8,,2020-12-23 12:55:00,23.110 sec,40.0,0.048583,0.035902,0.002360
9,,2020-12-23 12:55:00,23.135 sec,43.0,0.047543,0.035050,0.002260

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1            63.723656           1.000000    0.451197
1       f10            18.385826           0.288524    0.130181
2        f3            15.180560           0.238225    0.107486
3        f2             8.255027           0.129544    0.058450
4        f6             5.159658           0.080969    0.036533
5        f8             4.830294           0.075801    0.034201
6        f4             3.801014           0.059648    0.026913
7       f12             3.482932           0.054657    0.024661
8       f18             1.998178           0.031357    0.014148
9       f15             1.832631           0.028759    0.012976
10      f19             1.802032           0.028279    0.012759
11       f9             1.725510           0.027078    0.012218
12      f17             1.669308           0.026196    0.011820
13      f20             1.665487           0.026136    0.011793
14      f16             1.629153           0.025566    0.011535
15       f7             1.409099           0.022113    0.009977
16      f13             1.376493           0.021601    0.009746
17      f11             1.118854           0.017558    0.007922
18      f14             1.109735           0.017415    0.007858
19       f5             1.076862           0.016899    0.007625

Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_23


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 11.001 weights/biases, 139,5 KB, 2.014.500 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,10.0,,,,,,,,,
1,,2,500,RectifierDropout,40.0,0.0,0.0,0.015278,0.039545,0.0,-0.034855,0.46779,-0.225568,0.247956
2,,3,1,Linear,,0.0,0.0,0.000839,0.00112,0.0,0.00287,0.137275,0.161724,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.01059203065966177
RMSE: 0.10291759159474036
MAE: 0.07008580920667913
RMSLE: NaN
Mean Residual Deviance: 0.01059203065966177

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.018538106477002252
RMSE: 0.13615471522133288
MAE: 0.08648347462326784
RMSLE: NaN
Mean Residual Deviance: 0.018538106477002252

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.08648347,0.013595644,0.07963748,0.078659646,0.0903095,0.10860648,0.07520426
1,mean_residual_deviance,0.018538106,0.010918572,0.01061485,0.014174043,0.034680642,0.024579972,0.008641028
2,mse,0.018538106,0.010918572,0.01061485,0.014174043,0.034680642,0.024579972,0.008641028
3,r2,0.63739175,0.20586833,0.7889799,0.71789145,0.33347374,0.5231038,0.82351005
4,residual_deviance,0.018538106,0.010918572,0.01061485,0.014174043,0.034680642,0.024579972,0.008641028
5,rmse,0.13160954,0.039003767,0.10302839,0.11905479,0.1862274,0.15678,0.092957124
6,rmsle,0.063862726,0.007297337,0.06902273,NaN,NaN,NaN,0.058702733

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:00:57,0.000 sec,None,0.0,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:00:58,4 min 59.344 sec,17477 obs/sec,10.0,1,25500.0,0.130693,0.017081,0.096803,0.663244
2,,2020-12-23 13:01:03,5 min 4.556 sec,19172 obs/sec,50.0,5,127500.0,0.119469,0.014273,0.084529,0.718604
3,,2020-12-23 13:01:08,5 min 9.602 sec,21841 obs/sec,100.0,10,255000.0,0.114910,0.013204,0.079086,0.739669
4,,2020-12-23 13:01:14,5 min 15.620 sec,21645 obs/sec,150.0,15,382500.0,0.101419,0.010286,0.075440,0.797208
5,,2020-12-23 13:01:19,5 min 20.803 sec,23452 obs/sec,210.0,21,535500.0,0.103660,0.010745,0.075042,0.788147
6,,2020-12-23 13:01:25,5 min 26.521 sec,25026 obs/sec,280.0,28,714000.0,0.096625,0.009336,0.072578,0.815926
7,,2020-12-23 13:01:31,5 min 32.100 sec,26182 obs/sec,350.0,35,892500.0,0.093654,0.008771,0.070713,0.827072
8,,2020-12-23 13:01:36,5 min 37.594 sec,27072 obs/sec,420.0,42,1071000.0,0.090748,0.008235,0.069063,0.837638
9,,2020-12-23 13:01:42,5 min 42.964 sec,27824 obs/sec,490.0,49,1249500.0,0.106152,0.011268,0.077234,0.777841
10,,2020-12-23 13:01:47,5 min 48.313 sec,28426 obs/sec,560.0,56,1428000.0,0.091660,0.008402,0.069275,0.834359
11,,2020-12-23 13:01:52,5 min 53.572 sec,28961 obs/sec,630.0,63,1606500.0,0.096519,0.009316,0.068617,0.816330
12,,2020-12-23 13:01:58,5 min 58.837 sec,29399 obs/sec,700.0,70,1785000.0,0.091186,0.008315,0.068045,0.836066
13,,2020-12-23 13:02:03,6 min 4.037 sec,29797 obs/sec,770.0,77,1963500.0,0.088535,0.007838,0.067604,0.845460
14,,2020-12-23 13:02:04,6 min 5.551 sec,29896 obs/sec,790.0,79,2014500.0,0.102918,0.010592,0.070086,0.791172

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.182564
1        f2             0.590345           0.590345    0.107776
2        f4             0.461556           0.461556    0.084263
3        f6             0.268595           0.268595    0.049036
4       f10             0.258141           0.258141    0.047127
5        f9             0.244056           0.244056    0.044556
6        f8             0.235102           0.235102    0.042921
7        f3             0.225633           0.225633    0.041193
8       f13             0.210254           0.210254    0.038385
9       f12             0.209692           0.209692    0.038282
10       f5             0.208619           0.208619    0.038086
11      f18             0.205397           0.205397    0.037498
12      f15             0.189973           0.189973    0.034682
13       f7             0.177541           0.177541    0.032413
14      f11             0.176335           0.176335    0.032192
15      f14             0.176137           0.176137    0.032156
16      f19             0.172673           0.172673    0.031524
17      f20             0.159926           0.159926    0.029197
18      f16             0.155611           0.155611    0.028409
19      f17             0.151946           0.151946    0.027740

generic Model Build progress: |███████████████████████████████████████████| 100%
Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_24


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,100.0,100.0,17477.0,5.0,5.0,5.0,6.0,13.0,9.26

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.008956455818044997
RMSE: 0.09463855355004638
MAE: 0.07420112879691171
RMSLE: 0.0549020560027839
Mean Residual Deviance: 0.008956455818044997

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.010778559840122921
RMSE: 0.10381984319061034
MAE: 0.08092231929522892
RMSLE: 0.060514083431216656
Mean Residual Deviance: 0.010778559840122921

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.08092232,9.5537934E-4,0.080300145,0.0813628,0.081625596,0.079557166,0.0817659
1,mean_residual_deviance,0.01077856,4.1169173E-4,0.0109422775,0.010492673,0.010975158,0.011255157,0.010227534
2,mse,0.01077856,4.1169173E-4,0.0109422775,0.010492673,0.010975158,0.011255157,0.010227534
3,r2,0.7870875,0.0046846885,0.7824707,0.79116243,0.78906876,0.78162944,0.7911062
4,residual_deviance,0.01077856,4.1169173E-4,0.0109422775,0.010492673,0.010975158,0.011255157,0.010227534
5,rmse,0.10380462,0.0019880275,0.10460534,0.10243375,0.10476239,0.10609032,0.10113127
6,rmsle,0.060496956,0.0016095095,0.060201738,0.059232537,0.06202033,0.062297624,0.058732558

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:55:44,11.321 sec,0.0,0.225214,0.185965,0.050721
1,,2020-12-23 12:55:44,11.332 sec,5.0,0.173855,0.142379,0.030226
2,,2020-12-23 12:55:44,11.343 sec,10.0,0.145927,0.119247,0.021295
3,,2020-12-23 12:55:44,11.350 sec,15.0,0.127904,0.104293,0.016359
4,,2020-12-23 12:55:44,11.361 sec,20.0,0.117183,0.094882,0.013732
5,,2020-12-23 12:55:44,11.369 sec,25.0,0.111845,0.089993,0.012509
6,,2020-12-23 12:55:44,11.378 sec,30.0,0.108594,0.086845,0.011793
7,,2020-12-23 12:55:44,11.389 sec,35.0,0.106268,0.084578,0.011293
8,,2020-12-23 12:55:44,11.397 sec,40.0,0.104192,0.082696,0.010856
9,,2020-12-23 12:55:44,11.406 sec,45.0,0.102765,0.081350,0.010561
10,,2020-12-23 12:55:44,11.414 sec,50.0,0.101787,0.080382,0.010361
11,,2020-12-23 12:55:44,11.422 sec,55.0,0.100975,0.079587,0.010196
12,,2020-12-23 12:55:44,11.431 sec,60.0,0.099911,0.078652,0.009982
13,,2020-12-23 12:55:44,11.439 sec,65.0,0.099213,0.078123,0.009843
14,,2020-12-23 12:55:44,11.447 sec,70.0,0.098404,0.077423,0.009683
15,,2020-12-23 12:55:44,11.463 sec,75.0,0.097701,0.076774,0.009545
16,,2020-12-23 12:55:44,11.482 sec,80.0,0.097067,0.076289,0.009422
17,,2020-12-23 12:55:44,11.494 sec,85.0,0.096482,0.075721,0.009309
18,,2020-12-23 12:55:44,11.519 sec,90.0,0.095944,0.075294,0.009205
19,,2020-12-23 12:55:44,11.535 sec,95.0,0.095225,0.074638,0.009068

See the whole table with table.as_data_frame()

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           107.417511           1.000000    0.229121
1        f5            48.755306           0.453886    0.103995
2        f9            46.582294           0.433656    0.099360
3       f10            46.352245           0.431515    0.098869
4       f11            45.714684           0.425579    0.097509
5        f8            36.979729           0.344262    0.078877
6       f19            24.047108           0.223866    0.051292
7        f2            16.129063           0.150153    0.034403
8       f14            13.831702           0.128766    0.029503
9       f15            12.339588           0.114875    0.026320
10       f6            11.534179           0.107377    0.024602
11       f4            10.480007           0.097563    0.022354
12      f18             7.840743           0.072993    0.016724
13      f20             7.628046           0.071013    0.016271
14       f7             7.585384           0.070616    0.016180
15       f3             6.675276           0.062143    0.014238
16      f17             5.814903           0.054134    0.012403
17      f16             5.155358           0.047994    0.010996
18      f12             3.997064           0.037211    0.008526
19      f13             3.965103           0.036913    0.008458

generic Model Build progress: |███████████████████████████████████████████| 100%
Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_25


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,44.0,44.0,785746.0,20.0,20.0,20.0,1191.0,1562.0,1418.6818

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.009261560968830232
RMSE: 0.09623700415552341
MAE: 0.07427468631490734
RMSLE: 0.05544307423127023
Mean Residual Deviance: 0.009261560968830232

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.009002184962659494
RMSE: 0.09487984487054926
MAE: 0.07311162217022903
RMSLE: 0.05474948314537026
Mean Residual Deviance: 0.009002184962659494

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.07311162,0.0015803846,0.07436499,0.073341645,0.07096661,0.07211077,0.0747741
1,mean_residual_deviance,0.009002185,5.876716E-4,0.009766531,0.008697557,0.0084334,0.009489699,0.008623738
2,mse,0.009002185,5.876716E-4,0.009766531,0.008697557,0.0084334,0.009489699,0.008623738
3,r2,0.8220799,0.01203328,0.80584425,0.82689095,0.83791876,0.81588256,0.82386315
4,residual_deviance,0.009002185,5.876716E-4,0.009766531,0.008697557,0.0084334,0.009489699,0.008623738
5,rmse,0.09483983,0.0030803648,0.09882576,0.0932607,0.09183354,0.09741509,0.09286408
6,rmsle,0.054724272,0.0018574534,0.056827717,0.05333804,0.05320981,0.056679014,0.053566772

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:54:06,7.534 sec,0.0,NaN,NaN,NaN
1,,2020-12-23 12:54:06,7.736 sec,5.0,0.121461,0.091650,0.014753
2,,2020-12-23 12:54:07,7.953 sec,10.0,0.110056,0.083824,0.012112
3,,2020-12-23 12:54:07,8.202 sec,15.0,0.104418,0.079731,0.010903
4,,2020-12-23 12:54:07,8.378 sec,20.0,0.101433,0.077833,0.010289
5,,2020-12-23 12:54:07,8.512 sec,25.0,0.098817,0.075904,0.009765
6,,2020-12-23 12:54:07,8.629 sec,30.0,0.097618,0.075167,0.009529
7,,2020-12-23 12:54:07,8.782 sec,35.0,0.097066,0.074775,0.009422
8,,2020-12-23 12:54:08,8.945 sec,40.0,0.096458,0.074416,0.009304
9,,2020-12-23 12:54:08,9.037 sec,44.0,0.096237,0.074275,0.009262

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1          1721.668091           1.000000    0.401657
1       f10           429.380402           0.249398    0.100172
2        f3           353.572571           0.205366    0.082487
3        f2           308.968567           0.179459    0.072081
4        f5           282.315857           0.163978    0.065863
5        f8           161.609070           0.093868    0.037703
6       f11           121.306862           0.070459    0.028300
7        f6           112.214584           0.065178    0.026179
8        f9            97.871674           0.056847    0.022833
9        f4            85.202934           0.049489    0.019877
10      f19            76.272614           0.044302    0.017794
11      f20            71.911705           0.041769    0.016777
12      f12            71.882881           0.041752    0.016770
13      f18            64.592789           0.037518    0.015069
14      f13            63.496731           0.036881    0.014813
15      f15            61.563427           0.035758    0.014362
16      f16            59.842098           0.034758    0.013961
17      f14            52.242825           0.030344    0.012188
18      f17            48.500198           0.028170    0.011315
19       f7            41.997066           0.024393    0.009798

generic Model Build progress: |███████████████████████████████████████████| 100%
Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_26


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 512.001 weights/biases, 5,9 MB, 456.799 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,15.0,,,,,,,,,
1,,2,500,RectifierDropout,50.0,0.0,0.0,0.028521,0.028995,0.0,0.006497,0.246205,-0.130264,0.120105
2,,3,500,RectifierDropout,50.0,0.0,0.0,0.21979,0.22087,0.0,-0.043669,0.083438,0.131149,0.353391
3,,4,500,RectifierDropout,50.0,0.0,0.0,0.222538,0.190809,0.0,-0.024841,0.062566,0.463345,0.228103
4,,5,1,Linear,,0.0,0.0,0.00254,0.001887,0.0,-0.018468,0.027049,0.538805,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.006683327558445712
RMSE: 0.08175162113649925
MAE: 0.06396702971054734
RMSLE: 0.047474489636314864
Mean Residual Deviance: 0.006683327558445712

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.00838116849522992
RMSE: 0.09154872197485839
MAE: 0.06973636469963795
RMSLE: 0.05422856825661656
Mean Residual Deviance: 0.00838116849522992

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.06973636,0.0018706348,0.06921403,0.06720385,0.07088775,0.069243565,0.07213263
1,mean_residual_deviance,0.008381168,5.16069E-4,0.008436591,0.0075988956,0.008944884,0.008706871,0.0082186
2,mse,0.008381168,5.16069E-4,0.008436591,0.0075988956,0.008944884,0.008706871,0.0082186
3,r2,0.83446765,0.008164559,0.832283,0.8487578,0.8280885,0.83107084,0.83213794
4,residual_deviance,0.008381168,5.16069E-4,0.008436591,0.0075988956,0.008944884,0.008706871,0.0082186
5,rmse,0.09151342,0.0028424077,0.09185092,0.087171644,0.094577394,0.09331062,0.0906565
6,rmsle,0.054064233,0.0047165314,0.052231304,0.04995333,0.06213143,0.053836055,0.052169036

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 14:26:48,0.000 sec,None,0.000000,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 14:26:51,39 min 46.607 sec,1484 obs/sec,1.736471,1,4428.0,0.150251,0.022575,0.121364,0.554913
2,,2020-12-23 14:26:58,39 min 53.513 sec,1895 obs/sec,6.969412,4,17772.0,0.115115,0.013252,0.092591,0.738738
3,,2020-12-23 14:27:04,40 min 0.035 sec,2018 obs/sec,12.179216,7,31057.0,0.105040,0.011034,0.083073,0.782468
4,,2020-12-23 14:27:10,40 min 5.735 sec,1940 obs/sec,15.661961,9,39938.0,0.102171,0.010439,0.080182,0.794189
5,,2020-12-23 14:27:16,40 min 11.904 sec,2029 obs/sec,20.853725,12,53177.0,0.100491,0.010098,0.077667,0.800904
6,,2020-12-23 14:27:22,40 min 17.651 sec,2114 obs/sec,26.062353,15,66459.0,0.096326,0.009279,0.074867,0.817066
7,,2020-12-23 14:27:27,40 min 23.214 sec,2184 obs/sec,31.264314,18,79724.0,0.095673,0.009153,0.073718,0.819536
8,,2020-12-23 14:27:33,40 min 28.537 sec,2254 obs/sec,36.515294,21,93114.0,0.100143,0.010029,0.077284,0.802279
9,,2020-12-23 14:27:38,40 min 33.701 sec,2317 obs/sec,41.750588,24,106464.0,0.093171,0.008681,0.071037,0.828854
10,,2020-12-23 14:27:44,40 min 40.076 sec,2399 obs/sec,48.705882,28,124200.0,0.091976,0.008460,0.068262,0.833214
11,,2020-12-23 14:27:50,40 min 46.124 sec,2478 obs/sec,55.689412,32,142008.0,0.089261,0.007968,0.069445,0.842916
12,,2020-12-23 14:27:57,40 min 52.417 sec,2535 obs/sec,62.613725,36,159665.0,0.088768,0.007880,0.067997,0.844645
13,,2020-12-23 14:28:03,40 min 58.664 sec,2588 obs/sec,69.596863,40,177472.0,0.087828,0.007714,0.068720,0.847918
14,,2020-12-23 14:28:10,41 min 5.559 sec,2665 obs/sec,78.301176,45,199668.0,0.086680,0.007513,0.064788,0.851868
15,,2020-12-23 14:28:16,41 min 12.036 sec,2745 obs/sec,87.047843,50,221972.0,0.086249,0.007439,0.066733,0.853339
16,,2020-12-23 14:28:22,41 min 18.264 sec,2819 obs/sec,95.711765,55,244065.0,0.081960,0.006717,0.062653,0.867562
17,,2020-12-23 14:28:28,41 min 24.298 sec,2890 obs/sec,104.377647,60,266163.0,0.082621,0.006826,0.062141,0.865417
18,,2020-12-23 14:28:34,41 min 30.227 sec,2957 obs/sec,113.069804,65,288328.0,0.081245,0.006601,0.060938,0.869863
19,,2020-12-23 14:28:40,41 min 35.986 sec,3022 obs/sec,121.745490,70,310451.0,0.081851,0.006700,0.062484,0.867914

See the whole table with table.as_data_frame()

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f2             1.000000           1.000000    0.087970
1        f1             0.879053           0.879053    0.077330
2        f4             0.874134           0.874134    0.076898
3        f3             0.822560           0.822560    0.072361
4       f10             0.660798           0.660798    0.058130
5        f8             0.642588           0.642588    0.056528
6       f12             0.634408           0.634408    0.055809
7        f6             0.551594           0.551594    0.048524
8       f15             0.487802           0.487802    0.042912
9       f18             0.477671           0.477671    0.042021
10      f17             0.475335           0.475335    0.041815
11      f13             0.467579           0.467579    0.041133
12      f19             0.460418           0.460418    0.040503
13       f9             0.459222           0.459222    0.040398
14      f16             0.445025           0.445025    0.039149
15      f11             0.440972           0.440972    0.038792
16       f5             0.420087           0.420087    0.036955
17      f14             0.416040           0.416040    0.036599
18      f20             0.387766           0.387766    0.034112
19       f7             0.364453           0.364453    0.032061

generic Model Build progress: |███████████████████████████████████████████| 100%
Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_27


Model Summary:

     number_of_trees
0               42.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.0025953606528064024
RMSE: 0.05094468228192617
MAE: 0.039433264812710235
RMSLE: 0.028994029038830353
Mean Residual Deviance: 0.0025953606528064024

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.009568565749445724
RMSE: 0.09781904594426243
MAE: 0.0761773002600553
RMSLE: 0.05648130666452936
Mean Residual Deviance: 0.009568565749445724

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.0761773,9.7601285E-4,0.07674356,0.075770155,0.07464003,0.076791845,0.07694092
1,mean_residual_deviance,0.0095685655,4.147909E-4,0.00982876,0.00911974,0.009368463,0.010152459,0.009373406
2,mse,0.0095685655,4.147909E-4,0.00982876,0.00911974,0.009368463,0.010152459,0.009373406
3,r2,0.81092364,0.007851595,0.8046071,0.8184882,0.8199478,0.80302376,0.80855143
4,residual_deviance,0.0095685655,4.147909E-4,0.00982876,0.00911974,0.009368463,0.010152459,0.009373406
5,rmse,0.097800806,0.0021120075,0.0991401,0.095497325,0.09679082,0.10075942,0.09681635
6,rmsle,0.05646901,0.0013176936,0.056679845,0.054989494,0.056200277,0.058552593,0.055922836

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-12-23 12:53:57,1.247 sec,0.0,0.321817,0.275443,0.103566
1,,2020-12-23 12:53:57,1.293 sec,5.0,0.106925,0.084817,0.011433
2,,2020-12-23 12:53:57,1.359 sec,10.0,0.083244,0.064612,0.006930
3,,2020-12-23 12:53:57,1.410 sec,15.0,0.075687,0.058213,0.005728
4,,2020-12-23 12:53:57,1.455 sec,20.0,0.069042,0.053024,0.004767
5,,2020-12-23 12:53:57,1.503 sec,25.0,0.063617,0.049155,0.004047
6,,2020-12-23 12:53:57,1.529 sec,30.0,0.058250,0.045188,0.003393
7,,2020-12-23 12:53:57,1.560 sec,35.0,0.054483,0.042382,0.002968
8,,2020-12-23 12:53:57,1.584 sec,40.0,0.052163,0.040479,0.002721
9,,2020-12-23 12:53:57,1.612 sec,42.0,0.050945,0.039433,0.002595

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1           119.157349           1.000000    0.596770
1        f5            29.433113           0.247010    0.147408
2       f10             6.186218           0.051916    0.030982
3        f3             5.474494           0.045943    0.027418
4       f15             4.174787           0.035036    0.020908
5       f20             3.503574           0.029403    0.017547
6       f18             3.128119           0.026252    0.015666
7       f14             3.088315           0.025918    0.015467
8        f2             2.814577           0.023621    0.014096
9       f19             2.789908           0.023414    0.013973
10      f12             2.536249           0.021285    0.012702
11      f11             2.467705           0.020710    0.012359
12       f8             2.245251           0.018843    0.011245
13      f16             2.223260           0.018658    0.011135
14       f6             1.871714           0.015708    0.009374
15       f7             1.800820           0.015113    0.009019
16       f9             1.798695           0.015095    0.009008
17      f17             1.701743           0.014281    0.008523
18       f4             1.639352           0.013758    0.008210
19      f13             1.635155           0.013723    0.008189

generic Model Build progress: |███████████████████████████████████████████| 100%
Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_28


Status of Neuron Layers: predicting REDSHIFT_SPEC, regression, gaussian distribution, Quadratic loss, 11.001 weights/biases, 139,5 KB, 1.632.000 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,20,Input,15.0,,,,,,,,,
1,,2,500,RectifierDropout,50.0,0.0,0.0,0.033264,0.0822,0.0,-0.022781,0.353285,-0.167413,0.208907
2,,3,1,Linear,,0.0,0.0,0.001615,0.001679,0.0,0.018816,0.20858,0.392716,0.0

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.010119117894754778
RMSE: 0.10059382632525109
MAE: 0.07053849490458243
RMSLE: 0.08327143541217236
Mean Residual Deviance: 0.010119117894754778

ModelMetricsRegressionGeneric: generic
** Reported on cross-validation data. **

MSE: 0.02523608989968343
RMSE: 0.15885871049358116
MAE: 0.09181894948690594
RMSLE: NaN
Mean Residual Deviance: 0.02523608989968343

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,0.09181895,0.016472602,0.09492648,0.077991426,0.092100315,0.117409416,0.076667115
1,mean_residual_deviance,0.02523609,0.017155012,0.016735999,0.013892996,0.049640402,0.036562294,0.009348761
2,mse,0.02523609,0.017155012,0.016735999,0.013892996,0.049640402,0.036562294,0.009348761
3,r2,0.5072841,0.32525766,0.66729325,0.7234852,0.045962542,0.2906249,0.8090548
4,residual_deviance,0.02523609,0.017155012,0.016735999,0.013892996,0.049640402,0.036562294,0.009348761
5,rmse,0.15158783,0.053118,0.1293677,0.11786855,0.22280125,0.19121268,0.09668899
6,rmsle,0.14360249,0.12040384,0.22874086,NaN,NaN,NaN,0.058464114

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2
0,,2020-12-23 13:05:01,0.000 sec,None,0.0,0,0.0,NaN,NaN,NaN,NaN
1,,2020-12-23 13:05:02,9 min 3.774 sec,21144 obs/sec,10.0,1,25500.0,0.180827,0.032698,0.107908,0.355331
2,,2020-12-23 13:05:08,9 min 9.089 sec,27465 obs/sec,70.0,7,178500.0,0.133895,0.017928,0.085197,0.646541
3,,2020-12-23 13:05:13,9 min 14.297 sec,30549 obs/sec,140.0,14,357000.0,0.119946,0.014387,0.079987,0.716351
4,,2020-12-23 13:05:19,9 min 19.853 sec,32574 obs/sec,220.0,22,561000.0,0.103672,0.010748,0.075256,0.788100
5,,2020-12-23 13:05:24,9 min 25.194 sec,33936 obs/sec,300.0,30,765000.0,0.112788,0.012721,0.073213,0.749195
6,,2020-12-23 13:05:29,9 min 30.435 sec,34910 obs/sec,380.0,38,969000.0,0.094370,0.008906,0.070437,0.824421
7,,2020-12-23 13:05:34,9 min 35.622 sec,35628 obs/sec,460.0,46,1173000.0,0.102555,0.010518,0.071795,0.792640
8,,2020-12-23 13:05:39,9 min 40.717 sec,36239 obs/sec,540.0,54,1377000.0,0.094432,0.008917,0.069297,0.824188
9,,2020-12-23 13:05:44,9 min 45.783 sec,36731 obs/sec,620.0,62,1581000.0,0.092872,0.008625,0.068595,0.829950
10,,2020-12-23 13:05:46,9 min 47.125 sec,36786 obs/sec,640.0,64,1632000.0,0.100594,0.010119,0.070538,0.800496

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0        f1             1.000000           1.000000    0.188632
1        f2             0.546066           0.546066    0.103005
2        f4             0.380889           0.380889    0.071848
3        f3             0.265035           0.265035    0.049994
4       f10             0.261296           0.261296    0.049289
5        f6             0.245289           0.245289    0.046269
6        f8             0.225120           0.225120    0.042465
7       f12             0.220099           0.220099    0.041518
8        f5             0.205127           0.205127    0.038693
9       f15             0.197386           0.197386    0.037233
10       f9             0.193582           0.193582    0.036516
11      f11             0.192723           0.192723    0.036354
12      f18             0.189651           0.189651    0.035774
13      f19             0.185193           0.185193    0.034933
14      f17             0.182086           0.182086    0.034347
15      f13             0.178263           0.178263    0.033626
16      f16             0.167458           0.167458    0.031588
17      f20             0.159350           0.159350    0.030059
18      f14             0.154851           0.154851    0.029210
19       f7             0.151874           0.151874    0.028648

generic Model Build progress: |███████████████████████████████████████████| 100%
Model Details
=============
H2OGenericEstimator :  Import MOJO Model
Model Key:  Generic_model_python_1666773046559_29


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,89.0,89.0,22956.0,4.0,4.0,4.0,14.0,16.0,15.932584

ModelMetricsRegressionGeneric: generic
** Reported on train data. **

MSE: 0.006003262640218573
RMSE: 0.07748072431397743
MAE: 0.06056312762200832
RMSLE: 0.04387543964373978
Mean Residual Deviance: 0.006003262640218573

In [ ]:
df_predictions = gen_models_predictions(df, read_models('../../models/models/mojo_50_ensemble'))

In [ ]:
df_predictions

In [ ]:
best_model = h2o.import_mojo(f'../../models/mojo_50_ensemble/{BEST_MODEL}')
predictions = df_predictions.loc[:,df_predictions.columns[1]:df_predictions.columns[-1]].values.reshape(len(df_predictions),52)
y_best_pred = df_predictions[f'{BEST_MODEL}'].values
y_real = df_predictions['REDSHIFT_SPEC'].values

In [ ]:
for i in range(4):
    print_gaussian_kde(gen_gaussian_kde(predictions[i])[0], predictions[i], y_real[i], y_best_pred[i], df_predictions.index[i])

In [ ]:
df_kde = gen_df_gaussian_kde(df_predictions,
                             export_csv = True,
                             best_model = BEST_MODEL,
                             path = '../../data/enriched/pdf_redshift_preds.csv')

In [ ]:
df_kde

In [ ]:
len(df_kde['predictions'][0])